### ISSUE TITLE
Reverse proxy with `TASMO_BASEURL` broke on v3.1.3 caused by PR #1005

### ISSUE THREAD

**Issue by vincejv** [TasmoAdmin/TasmoAdmin#1009]
Reverse proxy with `TASMO_BASEURL` broke on v3.1.3 caused by PR #1005

## Expected Behavior

Reverse proxy with path should work when `TASMO_BASEURL` is set

## Current Behavior

Reverse proxy with path is NO longer working when `TASMO_BASEURL` is set
![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/1276544/a4a6e22c-a2dd-430d-9b05-14956cfa1661)

## Possible Solution

Revert PR #1005

## Steps to Reproduce

1. Reverse proxy with subfolder/path
2. Set `TASMO_BASEURL` as env variable
3. Load tasmoadmin ui
4. Cannot control tasmota plug due to error below
![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/1276544/706e3c38-5d56-49d7-9ebe-1c03f8acd0ba)

## Context (Environment)

Docker, TasmoAdmin v3.1.3, Nginx 1.25.3 as reverse proxy
Last known working version: TasmoAdmin v3.1.2

## Context (Device)

irrelevant

## Detailed Description

Reverse proxy with `TASMO_BASEURL` broke on v3.1.3 caused by PR #1005

## Possible Implementation

Revert PR #1005

**Comment by inverse** [comment]
@vincejv are you able to verify fixed in https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v3.1.4-beta.1?

**Comment by vincejv** [comment]
Yes, it's working already on v3.1.4, thanks for the quick fix @inverse
