### ISSUE TITLE
Unclear how to reset password using TasmoAdmin HA Addon

### ISSUE THREAD

**Issue by reslip1** [TasmoAdmin/TasmoAdmin#1016]
Using tasmoAdmin add-on in home assistant it prompts for username/password. Attempted to install and reinstall, but still had login prompt

## Expected Behavior
On uninstall and reinstall user should be able to register again

## Current Behavior
Login page

## Possible Solution
Resolve issues for users that need to login and want to use Tasmo Admin

## Steps to Reproduce

1. Setup tasmo admin with username/password
2. Unfortunately, forget what you put in
3. Attempt the defaults to no luck
4. Try to uninstall
5. Try to reinstall

## Context (Environment)
Tasmoadmin 0.25.1 / HA OS 11.0

**Comment by inverse** [comment]
This might need to be registered on https://github.com/hassio-addons/addon-tasmoadmin

I would expect a an uninstall and install to flush all data to nuke all data. 

Altenratively you could.

- create a backup of the addon
- Modify the backup editing `/data/tasmoadmin/MyConfig.json` changing the `login` prop to `0` and applying to the tar
- Restore the tar 
- Change password and enable login from setting
