### ISSUE TITLE
Self update page shows old changelog

### ISSUE THREAD

**Issue by gzone156** [TasmoAdmin/TasmoAdmin#1017]
## Expected Behavior

Show the current changelog of TasmoAdmin releases

## Current Behavior

The page shows a changelog with the v2.1.0 as the latest release

## Steps to Reproduce

1. Open TasmoAdmin
2. Go to self update page
3. Watch the ancient changelog 🤣 

## Context (Environment)

Webserver nginx on php8.2 fpm

## Context (Device)

Debian bookworm on Raspi4

**Comment by inverse** [comment]
Thanks for reporting! This is expected as changelogs are now enscapsulated in releases which are linked from that page.

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/713525/5d1c87ec-afda-4358-9b66-31640a9e5df9)

**Comment by gzone156** [comment]
Have a look at the PR, that could be a more "dynamic" solution.

**Comment by inverse** [comment]
A much nicer solution - there may be some API limits with using Github API unauthenticated but that shouldn't affect the majority of folks

**Comment by gzone156** [comment]
Glad to contribute. I didn't think about the API limitations for unauthenticated GitHub users, could it cause some issues?

**Comment by inverse** [comment]
Shouldn't do - I only noticed it when developing this. I guess we could fail more gracefully in such cases. But we can add that independant of your PR.
