### ISSUE TITLE
Tasmota Admin 3.2.0 not loading on Docker

### ISSUE THREAD

**Issue by MarcelMertens** [TasmoAdmin/TasmoAdmin#1038]
Fresh deployed Tasmota Admin 3.2.0 on Docker.
Webserver output just delivers some php statements

`
s6-rc: info: service nginx: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service init-nginx: starting
Symlinking /etc/nginx.conf from persistent storage location...
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service init-nginx successfully started
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-tasmoadmin: starting
Symlinking /data/tasmoadmin directory to persistent storage location...
rm: can't remove '/var/www/tasmoadmin/data': Invalid argument
Docker env does not exist, doing that now...
s6-rc: info: service init-tasmoadmin successfully started
s6-rc: info: service php-fpm: starting
s6-rc: info: service php-fpm successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
`

Webfrontend shows

`array(3) { [0]=> array(7) { ["file"]=> string(42) "/var/www/tasmoadmin/includes/container.php" ["line"]=> int(13) ["function"]=> string(11) "__construct" ["class"]=> string(17) "TasmoAdmin\Config" ["object"]=> object(TasmoAdmin\Config)#4 (6) { ["debug":"TasmoAdmin\Config":private]=> bool(false) ["dataDir":"TasmoAdmin\Config":private]=> string(25) "/var/www/tasmoadmin/data/" ["appRoot":"TasmoAdmin\Config":private]=> string(20) "/var/www/tasmoadmin/" ["cfgFile":"TasmoAdmin\Config":private]=> string(38) "/var/www/tasmoadmin/data/MyConfig.json" ["filesystem":"TasmoAdmin\Config":private]=> object(Symfony\Component\Filesystem\Filesystem)#5 (0) { } ["defaults":"TasmoAdmin\Config":private]=> array(21) { ["ota_server_ip"]=> string(10) "172.17.0.3" ["ota_server_port"]=> string(2) "80" ["username"]=> string(0) "" ["password"]=> string(0) "" ["refreshtime"]=> string(1) "8" ["current_git_tag"]=> string(0) "" ["update_automatic_lang"]=> string(15) "tasmota-sensors" ["nightmode"]=> string(4) "auto" ["login"]=> string(1) "1" ["scan_from_ip"]=> string(10) "172.17.0.2" ["scan_to_ip"]=> string(12) "172.17.0.254" ["homepage"]=> string(5) "start" ["check_for_updates"]=> string(1) "3" ["minimize_resources"]=> string(1) "1" ["update_channel"]=> string(6) "docker" ["hide_copyright"]=> string(1) "1" ["show_search"]=> string(1) "1" ["update_fe_check"]=> string(1) "0" ["update_be_check"]=> string(1) "1" ["auto_update_channel"]=> string(6) "stable" ["force_upgrade"]=> string(1) "0" } } ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(25) "/var/www/tasmoadmin/data/" [1]=> string(20) "/var/www/tasmoadmin/" } } [1]=> array(4) { ["file"]=> string(42) "/var/www/tasmoadmin/includes/bootstrap.php" ["line"]=> int(63) ["args"]=> array(1) { [0]=> string(42) "/var/www/tasmoadmin/includes/container.php" } ["function"]=> string(7) "require" } [2]=> array(4) { ["file"]=> string(29) "/var/www/tasmoadmin/index.php" ["line"]=> int(12) ["args"]=> array(1) { [0]=> string(42) "/var/www/tasmoadmin/includes/bootstrap.php" } ["function"]=> string(12) "include_once" } } /var/www/tasmoadmin/data/ is NOT WRITEABLE! | __construct()`

**Comment by inverse** [comment]
What's your docker command?

I tried with

```bash
docker run -it -p 8080:80 -v $(pwd)/data:/data ghcr.io/tasmoadmin/tasmoadmin:v3.2.0
```

Where `./data` is an empty dir and was unable to reproduce it.

**Comment by MarcelMertens** [comment]
ok, tried a different docker host, here it's working.
Will check it. Thank you

**Comment by inverse** [comment]
@MarcelMertens did you manage to get it working?

**Comment by MarcelMertens** [comment]
My issue was / is related to my my docker on proxmox running as lxc.
Now i am running tasmota admin as a addon on HA. Works fine.
