### ISSUE TITLE
Tasmoadmin team doesn't exist on Transifex

### ISSUE THREAD

**Issue by DominikPalo** [TasmoAdmin/TasmoAdmin#1040]
I'd like to create a new translation (Slovak). Unfortunately, it seems the Tasmoadmin team no longer exist on Transifex
## Expected Behavior
After clicking on the "Join [our team](https://app.transifex.com/tasmoadmin/)" link in the README, I'm able to join the Tasmoadmin team on Transifex

## Current Behavior
After visiting https://app.transifex.com/tasmoadmin I ended up with a 404 error:

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/1623257/558d56e2-0f65-4486-8ea2-ffccaaaf8dd8)

**Comment by inverse** [comment]
Not that familiar with Transifex but had other folks contribute in the past with no problems.

is this still problematic? When I navigate to that URL it works.

**Comment by DominikPalo** [comment]
It still doesn't work for me when I'm logged into Transifex with my account. By the way, when I try to open the link in incognito mode (or when logged out from Transifex), it works fine. However, after logging in with my account, the link starts behaving as described - showing a 404 error. 🤔

**Comment by inverse** [comment]
That's super strange - I changed the rules to automatically acccept translators - does that change anything?

**Comment by DominikPalo** [comment]
I've just discovered that I can find and join the Tasmoadmin project through the Transifex explore functionality. However, I ended up on a different project URL: https://explore.transifex.com/tasmoadmin/tasmoadmin/. Interestingly, this URL works fine in both cases - for both logged-in and not logged-in users.

**Comment by inverse** [comment]
I'll update the URL to be this one :+1:

**Comment by DominikPalo** [comment]
Thank you!
