### ISSUE TITLE
self update fail with errormessage

### ISSUE THREAD

**Issue by Boebbele** [TasmoAdmin/TasmoAdmin#1052]
Tasmoadmin 3.3.0
OS: dietpi x86

 php -v
PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

Self update on Webinterface fail with error:

Warning: Undefined array key "release_url" in /var/www/tasmoadmin/pages/selfupdate.php on line 20

Warning: Undefined array key "latest_tag" in /var/www/tasmoadmin/pages/selfupdate.php on line 20

Fatal error: Uncaught TypeError: TasmoAdmin\SelfUpdate::update(): Argument #1 ($releaseUrl) must be of type string, null given, called in /var/www/tasmoadmin/pages/selfupdate.php on line 20 and defined in /var/www/tasmoadmin/src/SelfUpdate.php:28 Stack trace: #0 /var/www/tasmoadmin/pages/selfupdate.php(20): TasmoAdmin\SelfUpdate->update() #1 /var/www/tasmoadmin/index.php(66): include('...') #2 /var/www/tasmoadmin/index.php(111): render_template() #3 {main} thrown in /var/www/tasmoadmin/src/SelfUpdate.php on line 28

IP adress and port in setting are okay. Please help.
![Screenshot_20231215-193420_Iodé Browser](https://github.com/TasmoAdmin/TasmoAdmin/assets/77356505/23c20ca8-e4d1-427b-9077-3d5165593be6)

**Comment by Boebbele** [comment]
It is a problem with lighthtpd!
It ist fixed for dietpi:

https://github.com/MichaIng/DietPi/issues/6805

**Comment by inverse** [comment]
glad it was fixed!
