### ISSUE TITLE
Automatic update fails

### ISSUE THREAD

**Issue by smoldersonline** [TasmoAdmin/TasmoAdmin#1060]
Running TasmoAdmin 0.28.0 (HA Add-On)

Automatic Update fails and triggers below error message:

> Minimal Firmware is not accessible on the server at http://xxx.xxx.xxx.xx:9541/data/firmwares/tasmota-minimal.bin.gz Please check the OTA IP address and port are correct Full Firmware is not accessible on the server at http://xxx.xxx.xxx.xx:9541/data/firmwares/tasmota.bin.gz Please check the OTA IP address and port are correct

In another (similar?) Bug report #427 it was suggested that http needs to be updated to https. Maybe?

Thank you!

**Comment by Deviantgit** [comment]
Also experiencing this. Never successfully been able to update through Tasmoadmin, have to do each device manually.

**Comment by inverse** [comment]
is tasmoasmin running with tls? afaik tasmota devices dont support tls so you will need to run it without this.

**Comment by c0nsaw** [comment]
> Also experiencing this. Never successfully been able to update through Tasmoadmin, have to do each device manually.

Same

**Comment by honikos** [comment]
Same for me now. Tried all variants ... no success. 

Add-on: TasmoAdmin
-----------------------------------------------------------
Add-on version: 0.30.0
You are running the latest version of this add-on.
System: Home Assistant OS 12.1  (armv7 / raspberrypi4)
Home Assistant Core: 2024.3.3
Home Assistant Supervisor: 2024.03.0
Operating System 12.1
Frontend 20240307.0
