### ISSUE TITLE
Docker image leaves around >100,000 tmp/sessions/sess_* files

### ISSUE THREAD

**Issue by jensb** [TasmoAdmin/TasmoAdmin#1066]
I have been running TasmoAdmin on my Raspi for some time now as a docker image.
I just noticed by pure coincidence that my backup script was taking ages to back up the docker image, and this is apparently due to >173370 temporary session files (all empty) left over by TasmoAdmin.

```
root@raspberry:/var/lib/docker/overlay2/a2970......../diff/var/www/tasmoadmin/tmp/sessions# ls -l | nl | tail
173373  -rw-r--r-- 1 _apt systemd-timesync   0 26. Nov 19:08 sess_vvur5pi0egojapd6u49f5u1v4v
173374  -rw-r--r-- 1 _apt systemd-timesync   0 10. Dez 22:51 sess_vvus2dblgl8f7rcrpooom0p587
173375  -rw-r--r-- 1 _apt systemd-timesync   0  4. Dez 15:48 sess_vvv53sb5cqgrl8t5977hegmb0s
173376  -rw-r--r-- 1 _apt systemd-timesync   0 28. Nov 20:57 sess_vvv60n552omdeln79sb673ifgt
173377  -rw------- 1 _apt systemd-timesync   0 31. Dez 00:13 sess_vvvcnj4bteddp5ifdph21a810c
173378  -rw-r--r-- 1 _apt systemd-timesync   0 23. Dez 20:04 sess_vvvncjcgq87r5d4qeugknfosnm
173379  -rw-r--r-- 1 _apt systemd-timesync   0 14. Nov 12:36 sess_vvvnr2lck9ja0icjjj8684qcfo
173380  -rw-r--r-- 1 _apt systemd-timesync   0  8. Nov 09:35 sess_vvvoqkvtkjtsgch0bmbvkg9or0
173381  -rw-r--r-- 1 _apt systemd-timesync   0  7. Nov 03:18 sess_vvvq2h7edu59asmjf6eabqth5l
173382  -rw-r--r-- 1 _apt systemd-timesync   0 23. Nov 22:24 sess_vvvvpjhh5lrdom0kopei9p81qc
```

## Expected Behavior
I would expect the TasmoAdmin to remove these session files regularly.
Also - update - it seems TasmoAdmin regularly creates these files twice a minute by itself because it's regularly called by `curl`:
```
...... /diff/var/log/nginx# tail -f access.log 
127.0.0.1 - - [31/Dec/2023:17:25:29 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
127.0.0.1 - - [31/Dec/2023:17:25:59 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
127.0.0.1 - - [31/Dec/2023:17:26:30 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
127.0.0.1 - - [31/Dec/2023:17:27:00 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
127.0.0.1 - - [31/Dec/2023:17:27:30 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
127.0.0.1 - - [31/Dec/2023:17:28:00 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
127.0.0.1 - - [31/Dec/2023:17:28:31 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
127.0.0.1 - - [31/Dec/2023:17:29:01 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
127.0.0.1 - - [31/Dec/2023:17:29:31 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
127.0.0.1 - - [31/Dec/2023:17:30:01 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/8.0.1"
```

## Current Behavior
See above.

## Possible Solution
The docker image should include a cronjob or similar to regularly remove stale session files, and possibly other temp files.

## Steps to Reproduce
1. Run TasmoAdmin for some months.
2. Look at the above directory.
3.
4.

## Context (Environment)
Raspi 4b, 4GB, Raspbian OS, Docker image:
```
pi@raspberry:~ $ docker ps
CONTAINER ID   IMAGE                                  COMMAND   CREATED        STATUS                PORTS                           NAMES
0d0927e2b1e0   ghcr.io/tasmoadmin/tasmoadmin:latest   "/init"   2 months ago   Up 2 days (healthy)   443/tcp, 0.0.0.0:8000->80/tcp   TasmoAdmin
```

## Possible Implementation
https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container

**Comment by inverse** [comment]
Nice investigation! not noticed this before when developing due to using kinda emphermal environments.

**Comment by inverse** [comment]
Would you be able to try this release to see if it fixes your issues and report any other problems? like being asked to login more often or anything around that?

**Comment by jensb** [comment]
Sure!
Can I just pull a new docker image, or do I have to hack this into the currently running image?

**Comment by inverse** [comment]
I changed it to to the default of 24 minutes before gc - but with the default of 1% so will be around 1/100 will do the cleanup

**Comment by inverse** [comment]
Didn't mean to close this ticket. @jensb did it solve your problems?

**Comment by jensb** [comment]
The new image works, but it still creates a new empty "sess_xxxx" file every 30 seconds, despite no TasmoAdmin client (browser) being active anywhere. I can't say (yet) if the old sess_ files are being deleted propertly.

**Comment by inverse** [comment]
it should start garbage collecting them after 24 minutes with a 1% probability per request ;/ 

I tried it with 1 minute gc for 50% and it seemed to work.

**Comment by inverse** [comment]
It could be the ajax calls when requesting device updates, but that does seem a bit excessive.

**Comment by jensb** [comment]
OK, let's see :-)
But what is the `curl` call every 30 seconds for?

**Comment by inverse** [comment]
the UI should be polling each device for it's status  on some frequency.  I think it's each 8 seconds by default.

**Comment by jensb** [comment]
After a day, I see no sess_* files that are older than ~30 minutes in the sessions directory.
Also I did not experience any weird login issues, like being logged out repeatedly or something.
The patch seems to work well.

Thanks :-)

**Comment by inverse** [comment]
Awesome :+1: glad it worked - will push a proper fix with this in!
