### ISSUE TITLE
Firmware upload to OTA server not working

### ISSUE THREAD

**Issue by raihei** [TasmoAdmin/TasmoAdmin#1086]
The "Update Devices" page does not upload the firmwares to the OTA server.

## Expected Behavior
"Update Devices" uploads firmware files to OTA server after selecting firmware files and clicking "Next"

## Current Behavior
After selecting the two firmware files from my local disk (minimal and full) and clicking "Next", the following error is shown:

> Minimal Firmware is not accessible on the server at http://172.17.17.16:9541/data/firmwares/tasmota-minimal.bin.gz
> Please check the OTA IP address and port are correct
> Full Firmware is not accessible on the server at http://172.17.17.16:9541/data/firmwares/tasmota.bin.gz
> Please check the OTA IP address and port are correct 

In my understanding, the page is supposed to upload the selected firmware files to the OTA server.
The OTA server IP and port is the same as where TasmoAdmin is running on.

## Steps to Reproduce
1. Select firmware files on "Update Devices" page
2. Press "Next"
3.
4.

## Context (Environment)
Home-Assistant OS with TasmoAdmin Add-On

## Context (Device)
Home Assistant 2024.1.3
TasmoAdmin 0.29.1

**Comment by inverse** [comment]
That IP address looks like the internal one for the docker network. Did you try changing it to the IP address your PI is running on?

**Comment by raihei** [comment]
No, that is the address from my HAOS Server, my home network uses 172.17.17.0/24.

Also 172.17.17.16:9541 opens the TasmoAdmin page

**Comment by inverse** [comment]
TasmoAdmin can only be accessible by HTTP for now as Tasmota from my understanding cannot fetch the firmware by HTTPS so we need to leave it that way.

**Comment by raihei** [comment]
Thanks for your answers, inverse 👍 

Yes, I know that this is a tasmota limitation, but when I set up TasmoAdmin I did not thought about that, and enabled HTTPS in the options. Now, with HTTP it works as expected.

Thanks again!
