### ISSUE TITLE
Change language on iPhone -> Warning

### ISSUE THREAD

**Issue by RaymondMouthaan** [TasmoAdmin/TasmoAdmin#109]
Hi @reloxx13,

I've reproduced the warnings regarding changing the language on my iPhone X. 

*Default language is NL, because it's the iPhone language:*
![img_0588 2](https://user-images.githubusercontent.com/25717738/40574005-feb38ea4-60ca-11e8-9aeb-9917937f84fb.png)

*Select EN:*
![img_0589](https://user-images.githubusercontent.com/25717738/40574007-033529a6-60cb-11e8-8d81-c64f29a68c71.png)

*Warnings about EN.php*
![img_0590](https://user-images.githubusercontent.com/25717738/40574009-0a5a3cc6-60cb-11e8-9dd6-a70487aea35c.png)

Switching a page via the menu however does apply the language. Reopening TasmoAdmin after closing it does start with NL again.

btw I am not sure if it is iPhone specific, i've not tested it on a different phone.

**Comment by inverse** [comment]
Closing as stale - please comment if its still an issue.
