### ISSUE TITLE
 Automatic update fails #1060 

### ISSUE THREAD

**Issue by honikos** [TasmoAdmin/TasmoAdmin#1133]
can't update tasmota firmeware on frontend

## Expected Behavior
same error, see:
[https://github.com/TasmoAdmin/TasmoAdmin/issues/1060#issue-2052288505)]

## Context (Environment)
Same for me now. Tried all variants ... no success.
Add-on: TasmoAdmin

Add-on version: 0.30.0
You are running the latest version of this add-on.
System: Home Assistant OS 12.1 (armv7 / raspberrypi4)
Home Assistant Core: 2024.3.3
Home Assistant Supervisor: 2024.03.0
Operating System 12.1
Frontend 20240307.0

**Comment by honikos** [comment]
hmm, it didn't work.  There where only various error massages. 
Only after deinstallation, reinstallation and home assistant restart it did what it should.
No error messages anymore.
Very strange.

**Comment by cmariegaard** [comment]
Thanks @honikos
Same solution solved my HA issue as well.
After reinstall TasmoAdmin OTA update works with with both 127.0.0.1 or HA IP address

**Comment by james3126** [comment]
> Only after deinstallation, reinstallation and home assistant restart it did what it should.
Thankyou @honikos
After an hour of searching and digging, I've found your suggestion. Went ahead with the reinstall and immediately all errors resolved and OTA's completed. I assume some old versions left-overs was causing problems in the newer versions.
