### ISSUE TITLE
zbbridge found with 2 

### ISSUE THREAD

**Issue by fragolinux** [TasmoAdmin/TasmoAdmin#1140]
hi, i'm scanning my network (tasmoadmin v4.0.1), and it found all my devices, but for no reason it's asking me to put in a second name for my zbbridge, not allowing me to save if i do not put in that...

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/21192010/2aeb7b02-afa9-4e61-b518-f117f45d4994)

and if i 2, it appears twice in the list... why? thanks in advance

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/21192010/1b277235-e8c6-4ba0-ab9c-1fb3ca98687d)

**Comment by inverse** [comment]
Haven't looked much at this part of the code base since contributing here. 

Would you be able to share the status json with sensative information removed?

e.g. `http://192.168.1.102/cm?cmnd=status%200`
