### ISSUE TITLE
Can't connect to the device

### ISSUE THREAD

**Issue by k-matti** [TasmoAdmin/TasmoAdmin#1143]
Hi all,

I bought this plug https://www.athom.tech/blank-1/tasmota-esp32-c3-eu-plug-v3 it has tasmota already instaleed

but cannot make plugin to display information from it
![3](https://github.com/TasmoAdmin/TasmoAdmin/assets/66017397/e856c39d-39ec-4a94-8c57-864d89bc3674)

**Comment by inverse** [comment]
It looks like it's running [ESPhome](https://esphome.io/index.html) and not Tasmota. We don't have plans to support ESPHome as that ecosystem is heavily maintained already by Home Assistant.

**Comment by inverse** [comment]
No problem :)
