### ISSUE TITLE
Started getting invalid config errors in Home Assistant.  Uninstalling add on doesn't fix it

### ISSUE THREAD

**Issue by jeremeyi** [TasmoAdmin/TasmoAdmin#1174]
I started getting invalid config errors in Home Assistant several versions ago.  

Logger: homeassistant.setup
Source: setup.py:271
First occurred: May 10, 2024 at 11:20:58 PM (1 occurrences)
Last logged: May 10, 2024 at 11:20:58 PM

Setup failed for 'tasmoadmin': Integration not found.Logger: homeassistant.helpers.translation
Source: helpers/translation.py:220
First occurred: May 10, 2024 at 11:20:57 PM (1 occurrences)
Last logged: May 10, 2024 at 11:20:57 PM

Failed to load integration for translation: Integration 'tasmoadmin' not found.

I have tried uninstalling and reinstalling the addon but still get the same errors.  As a last resort I uninstalled the addon and did not reinstall but still get these errors.

**Comment by inverse** [comment]
TasmoAdmin is provided as an addon which runs along side Home Assistant not as an integration itself. Not sure what's configured to cuase these errors you're seeing. 

How did you configure it within Home Assistant?

**Comment by jeremeyi** [comment]
I still had a reference to it in me configuration.yaml to show it in the sidebar with a custom icon I believe is what I was doing with that.  Sorry about that, could have sworn I had checked through that.  All cleared up now.
