### ISSUE TITLE
Issue: Unable to Edit Values in Detail View Forms

### ISSUE THREAD

**Issue by slimline33** [TasmoAdmin/TasmoAdmin#1185]
The detail view no longer allows editing values such as Hostname, MQTT, LED, etc., in forms. For some time now, an error occurs whenever attempting to make changes.

**Description:**

Previously, it was possible to edit form fields in the detail view to adjust values such as Hostname, MQTT, LED, etc. However, this functionality has ceased to work. When attempting to change a value and submit the form, an error is displayed in the Chrome Developer Console:

```
devices.min.js?_=v410:1 Uncaught ReferenceError: input is not defined
    at HTMLInputElement.<anonymous> (devices.min.js?_=v410:1:23205)
    at HTMLDocument.dispatch (vendor.min.js?_=v410:1:40404)
    at m.handle (vendor.min.js?_=v410:1:38395)
```

**Steps to Reproduce:**

Navigate to the detail view of a device.
Attempt to change a value such as Hostname, MQTT, LED, etc.
Observe the error in the Chrome Developer Console.

**Expected Behavior:**

Users should be able to edit values in forms within the detail view and successfully save these changes without encountering an error.

**Additional Information:**

Operating System: Windows 10
Browser: Chrome Version 98.0.4758.109 (Official Build) (64-bit)
Version in Use: The latest stable version

**Proposed Solution:**

It appears there is an error in the JavaScript code (devices.min.js) preventing the editing of forms in the detail view. Thoroughly reviewing the code and addressing the reference error should resolve the issue. Additionally, verifying the consistency of dependencies and versions may be helpful to ensure all components are working together correctly.

**Comment by inverse** [comment]
I'm unable to reproduce the issue locally and modified the hostname of a device I have configured locally.

`devices.min.js` is more on the device listing pages rather than device eidting page so not sure where that interaction is coming from.

I wonder where that issue is coming from :/

**Comment by slimline33** [comment]
![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/3323812/942e606b-3713-4c60-bb58-6bf6db4b0be7)

It's worth noting that the functionality was working previously, and it appears that I'm the only one encountering this problem. Despite this, I've tested it on both Edge and Chrome browsers, my default being Chrome, and unfortunately, the issue persists. At this point, it's unclear where the problem originates, but I'm actively investigating it by reviewing the codebase, implementing error logging, and seeking input from other team members. It's a puzzling situation, especially considering its previous functionality, but I'm committed to resolving it as soon as possible.

**Comment by inverse** [comment]
Ahhh I see what you're referring to and I can reproduce the issue.  Interesting, I didn't even know that functionality existed to edit fields from that view.

**Comment by inverse** [comment]
I think I fixed it in https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v4.1.1-beta.1

Are you able to test it and verify?

**Comment by slimline33** [comment]
The issue has been resolved with the beta version, and now you can smoothly change the values again with a double-click without any errors in the file.

Thank you very much for your support and understanding throughout this process! It's greatly appreciated.

**Comment by inverse** [comment]
Glad to hear! will publish the non-beta build than!
