### ISSUE TITLE
Clean devices no longer works

### ISSUE THREAD

**Issue by Mattrees007** [TasmoAdmin/TasmoAdmin#1206]
As i dotn assign static IP addresses to all of my tasmota devices, i use the clean devices function to remove all devices and then readd with an autoscan.

For a number of weeks now the clean devices function has worked.
The browser displays the address with the clean devices, no error message is displayed but no devices are removed.

## Expected Behavior
I would all devices to be removed.

## Current Behavior
No device is removed.

## Steps to Reproduce

1. Address I'm attempting to use, https://192.168.100.30:9541/?clean=devices
2.
3.
4.

## Context (Environment)
I use Tasmo Admin as an addon in Home Assistant.

## Context (Device)
I run HA on a PC as the operating system

## Detailed Description
not applicable

## Possible Implementation
not applicable

**Comment by inverse** [comment]
Check the updated Wiki https://github.com/TasmoAdmin/TasmoAdmin/wiki/FAQ#freeup-disk-space

This route got changes during the v3 release from `/?clean=devices` to `/actions?clean=devices`

**Comment by Mattrees007** [comment]
> Check the updated Wiki https://github.com/TasmoAdmin/TasmoAdmin/wiki/FAQ#freeup-disk-space
> 
> 
> 
> This route got changes during the v3 release from `/?clean=devices` to `/actions?clean=devices`
> 
> 

Thankyou :-)
