### ISSUE TITLE
TasmoAdmin config in Home Assistant add-on

### ISSUE THREAD

**Issue by plumbington** [TasmoAdmin/TasmoAdmin#1220]
I recently upgraded my Home Assistant installation to current version (2014.07). That upgrade went without a hitch, but after I upgraded TasmoAdmin, I realized that I'd forgotten my password for the TasmoAdmin web page.  I thought I could delete the add-on from Home Assistant (and therefore delete its associated config files) and start over. When I re-insatalled the add-on, I could no longer make changes to the configuration (eg turn off SSL). When I did make a change, and saved changes, no error was displayed, but the change was not saved.

Any thoughts as to how I might fix this issue?

Thanks

**Comment by inverse** [comment]
hmm interesting - reinstall should put it into default state. 

Perhaps its worth asking in the Home Assistant community. Perhaps on the addon repo - https://github.com/hassio-addons/addon-tasmoadmin

**Comment by plumbington** [comment]
Sorry for posting in the wrong place. I guess we can close this one, and I'll re-post where you suggested.

Thanks for your response!
