### ISSUE TITLE
TasmoAdmin 4.1.2 findet keine neuen Geräte mehr

### ISSUE THREAD

**Issue by mafrei2019** [TasmoAdmin/TasmoAdmin#1229]
Ich habe TA auf Docker jetzt Version 4.1.2 installiert. Bisher lief alles ohne Probleme. Nun habe ich, zwei neue Geräte in Betrieb genommen, diese werden aber durchTA nicht mehr gefunden. Der alte Bestand ist noch da. Kann einer was dazu sagen ?
Die WebGui der neuen Geräte kann ich aufrufen, Vergabe der IP via DHCP

**Comment by mafrei2019** [comment]
Nein, alles IPv4 funktionsfähige Geräte. und noch einiges frei. Habe aber mittlerweile 99 Tasmota Geräte in TA. Gibts da eine Grenze ?
(IPv6 ist nicht aktiviert)

**Comment by mafrei2019** [comment]
Fehler lag bei mir, hatte den faslchen Port eingetragen.

**Comment by inverse** [comment]
Glad it worked out. There shouldn't be a limit on the number of devices but I can imagine things would be slow with fetching all that state from each one.
