### ISSUE TITLE
Login data incorrect - since updating to HASSIO-TasmoAdmin-Add-on version 0.31.0 + TasmoAdmin V4.2

### ISSUE THREAD

**Issue by 7542** [TasmoAdmin/TasmoAdmin#1267]
## Expected Behavior
login working for webservices

## Current Behavior
since Updating to HASSIO-TasmoAdmin-Add-on version 0.31.0  including TasmoAdmin V4.2 i can not login to webservices -  Login data incorrect!

## Possible Solution
dont know

## Steps to Reproduce
1. reboot server
2. stop/start service
3. set loglevel to debug - look for authetification issues - nothing to find 
4.
5.

## Context (Environment)
HASSIO image on Raspberrypi 4
 System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.11.2
 Home Assistant Supervisor: 2024.11.3

## Context (Device)
TasmoAdmin-Add-on version: 0.31.0
TasmoAdmin V4.2

i am sure login credentials are correct! Using passkey! ... and several clients which are caching Username and Password

**Comment by 7542** [comment]
logging:

> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service nginx: stopping
> [13:03:21] INFO: Service NGINX exited with code 0 (by signal 0)
> s6-rc: info: service nginx successfully stopped
> s6-rc: info: service init-nginx: stopping
> s6-rc: info: service php-fpm: stopping
> s6-rc: info: service init-nginx successfully stopped
> [13:03:21] INFO: Service PHP-FPM exited with code 0 (by signal 0)
> s6-rc: info: service php-fpm successfully stopped
> s6-rc: info: service init-tasmoadmin: stopping
> s6-rc: info: service init-tasmoadmin successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service base-addon-log-level: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service base-addon-log-level successfully stopped
> s6-rc: info: service base-addon-banner: stopping
> s6-rc: info: service base-addon-banner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service base-addon-banner: starting
> -----------------------------------------------------------
>  Add-on: TasmoAdmin
>  Centrally manage all your Sonoff-Tasmota devices
> -----------------------------------------------------------
>  Add-on version: 0.31.0
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2024.11.2
>  Home Assistant Supervisor: 2024.11.3
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> s6-rc: info: service base-addon-banner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service base-addon-log-level: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service base-addon-log-level successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service init-tasmoadmin: starting
> s6-rc: info: service init-nginx: starting
> s6-rc: info: service init-tasmoadmin successfully started
> s6-rc: info: service php-fpm: starting
> s6-rc: info: service php-fpm successfully started
> s6-rc: info: service init-nginx successfully started
> s6-rc: info: service nginx: starting
> s6-rc: info: service nginx successfully started
> s6-rc: info: service legacy-services: starting
> [13:04:40] INFO: Starting PHP-FPM server...
> s6-rc: info: service legacy-services successfully started
> [13:04:40] INFO: Starting NGINX server...
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service nginx: stopping
> [13:12:16] INFO: Service NGINX exited with code 0 (by signal 0)
> s6-rc: info: service nginx successfully stopped
> s6-rc: info: service init-nginx: stopping
> s6-rc: info: service php-fpm: stopping
> s6-rc: info: service init-nginx successfully stopped
> [13:12:16] INFO: Service PHP-FPM exited with code 0 (by signal 0)
> s6-rc: info: service php-fpm successfully stopped
> s6-rc: info: service init-tasmoadmin: stopping
> s6-rc: info: service init-tasmoadmin successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service base-addon-log-level: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service base-addon-log-level successfully stopped
> s6-rc: info: service base-addon-banner: stopping
> s6-rc: info: service base-addon-banner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service base-addon-banner: starting
> -----------------------------------------------------------
>  Add-on: TasmoAdmin
>  Centrally manage all your Sonoff-Tasmota devices
> -----------------------------------------------------------
>  Add-on version: 0.31.0
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2024.11.2
>  Home Assistant Supervisor: 2024.11.3
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> s6-rc: info: service base-addon-banner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service base-addon-log-level: starting
> s6-rc: info: service base-addon-banner: stopping
> s6-rc: info: service base-addon-banner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service base-addon-banner: starting
> -----------------------------------------------------------
>  Add-on: TasmoAdmin
>  Centrally manage all your Sonoff-Tasmota devices
> -----------------------------------------------------------
>  Add-on version: 0.31.0
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2024.11.2
>  Home Assistant Supervisor: 2024.11.3
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> s6-rc: info: service base-addon-banner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service base-addon-log-level: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service base-addon-log-level successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service init-tasmoadmin: starting
> s6-rc: info: service init-nginx: starting
> s6-rc: info: service init-tasmoadmin successfully started
> s6-rc: info: service php-fpm: starting
> s6-rc: info: service php-fpm successfully started
> s6-rc: info: service init-nginx successfully started
> s6-rc: info: service nginx: starting
> s6-rc: info: service nginx successfully started
> s6-rc: info: service legacy-services: starting
> [13:04:40] INFO: Starting PHP-FPM server...
> s6-rc: info: service legacy-services successfully started
> [13:04:40] INFO: Starting NGINX server...
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service nginx: stopping
> [13:12:16] INFO: Service NGINX exited with code 0 (by signal 0)
> s6-rc: info: service nginx successfully stopped
> s6-rc: info: service init-nginx: stopping
> s6-rc: info: service php-fpm: stopping
> s6-rc: info: service init-nginx successfully stopped
> [13:12:16] INFO: Service PHP-FPM exited with code 0 (by signal 0)
> s6-rc: info: service php-fpm successfully stopped
> s6-rc: info: service init-tasmoadmin: stopping
> s6-rc: info: service init-tasmoadmin successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service base-addon-log-level: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service base-addon-log-level successfully stopped
> s6-rc: info: service base-addon-banner: stopping
> s6-rc: info: service base-addon-banner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service base-addon-banner: starting
> -----------------------------------------------------------
>  Add-on: TasmoAdmin
>  Centrally manage all your Sonoff-Tasmota devices
> -----------------------------------------------------------
>  Add-on version: 0.31.0
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2024.11.2
>  Home Assistant Supervisor: 2024.11.3
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> s6-rc: info: service base-addon-banner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service base-addon-log-level: starting
> s6-rc: info: service fix-attrs successfully started
> Log level is set to DEBUG
> s6-rc: info: service base-addon-log-level successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service init-tasmoadmin: starting
> s6-rc: info: service init-nginx: starting
> [13:12:22] DEBUG: Symlinking data directory to persistent storage location...
> s6-rc: info: service init-tasmoadmin successfully started
> s6-rc: info: service php-fpm: starting
> s6-rc: info: service php-fpm successfully started
> s6-rc: info: service init-nginx successfully started
> s6-rc: info: service nginx: starting
> s6-rc: info: service nginx successfully started
> s6-rc: info: service legacy-services: starting
> [13:12:22] INFO: Starting PHP-FPM server...
> s6-rc: info: service legacy-services successfully started
> [13:12:22] INFO: Starting NGINX server...

**Comment by 7542** [comment]
done Restore to V0.30.6 => Login working
new Upgrade to V0.31.0 => Login working
=> Problem solved ... don't know what got wrong.

**Comment by inverse** [comment]
Very odd - nothing much changed between the two versions.

https://github.com/hassio-addons/addon-tasmoadmin/releases/tag/v0.31.0

TasmoAdmin got bumped, but the login layer didnt get changed.
