### ISSUE TITLE
Ability to define URL base if using reverse proxy

### ISSUE THREAD

**Issue by jamieshaw** [TasmoAdmin/TasmoAdmin#140]
Is it possible to get the ability to define a custom base for reverse proxying?

If possible, I'd much rather use `https://domain/tasmota` rather than `https://tasmota.domain`. Unfortunately, the current setup strips out the request URI on page load, and rewriting isn't an option as it'll capture _all_ URLs, not just those for TasmoAdmin.

Cheers 👍

**Comment by reloxx13** [comment]
this should work already, guess it got broken, need to test-

**Comment by jamieshaw** [comment]
Thanks. Keep me posted :)

**Comment by reloxx13** [comment]
soo this is still working, you just need the "http://domain" webserver config and place tasmoadmin in it.

the sub directory is detected automatic as base. even in the device update process their is a handling for the subdirectory detection to set teh correct ota url on the devices.

**Comment by jamieshaw** [comment]
My setup is a little convoluted, but it works most of the time. I have two Mac minis, one running macOS which is public facing, one running ESXi which is not.
```
Public Internet => Mac mini server [macOS] => Mac mini server [ESXi] => Photon OS / Docker => TasmoAdmin
```

The Mac mini has a reverse proxy configured to direct traffic from `https://tasmota.domain.com` to the VM containing the Docker image. I'd prefer to use the `https://domain.com/tasmota/` URL so I don't have so many subdomains floating around – the problem is that the docker image sees itself at `/` opposed to `/tasmota`, so cannot rewrite the URLs accordingly.

This causes the issue where TasmoAdmin can't pull it's own assets from the URL because it's trying `https://domain.com/{{ query }}`, whilst `tasmota` needs adding before the query as a URL base.

I did try dropping TasmoAdmin into the default VirtualHost of my _macOS_ Mac mini but that could only load `index.php`, all other pages could not be found…

**Comment by bachya** [comment]
Same here (I believe): I have a NGINX container that proxies WAN traffic to various Docker containers (including this one). Having a heck of a time rewriting URLs so that the TasmoAdmin container works.

**Comment by bpjobin** [comment]
+1

**Comment by cmosek** [comment]
+1

**Comment by vincejv** [comment]
Hi @inverse @reloxx13, everything is working except the `/actions` POST request, it's not respecting the baseUrl setting, see screenshot, can we reopen this issue or create a separate issue...
![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/1276544/42b5647d-2df0-48e9-acd4-afbc83ba398a)
