### ISSUE TITLE
can't add device, curl error

### ISSUE THREAD

**Issue by ChrisPrefect** [TasmoAdmin/TasmoAdmin#197]
Hi!

I just installed hass.io on a raspi 3+B and added TasmoAdmin. I wanted to add my first tasmota device, but it always fails:

![image](https://user-images.githubusercontent.com/3579863/43426818-5f5e236c-9457-11e8-97f0-94321a96c03f.png)

CURL FEHLER => 28: Operation timed out after 5001 milliseconds with 0 bytes received

I know that the IP address is correct, when I enter it in chrome the web gui of the device shows up.

I tried setting and removing a password on the device, I tried it with or without "admin" as username, but nothing helps.

What could be the problem?

Thanks!
Chris

**Comment by mike2nl** [comment]
Have you tried to add the device manually to tasmo?

**Comment by ChrisPrefect** [comment]
Hi! Where and how can I do that? In Home Assistant? Or in TasmoAdmin? I some configuration yaml file?

**Comment by reloxx13** [comment]
Heya,

im sorry, im late :X

Did you get it fixed? Looks like TasmoAdmin cannot Access the network.

**Comment by 7542** [comment]
i have a similar problem? since i have more than 15 items in tasmoadmin on raspi4-buster i get "CURL-Fehler => 28" on a few device which before did´nt make problems.

**Comment by 7542** [comment]
also a few new flashed i can not add to tasmoadmin. all the items can be reached by webUI

**Comment by buliwyf42** [comment]
Same Error here.

**Comment by 7542** [comment]
it sucks ... today everthing worked fine ... i can not find the annoying link

**Comment by ChrisPrefect** [comment]
> Heya,
> 
> im sorry, im late :X
> 
> Did you get it fixed? Looks like TasmoAdmin cannot Access the network.

Sorry, I didn't get notifications for this reply. It's more than a year since you answered :-D

Yes, I fixed it. I formated the SD card of the raspberry, installed ioBroker, installed the Sonoff-Adapter and all my Tasmota-Devices were recognized and added instantly. It works with ioBroker since very nicely ;-)

**Comment by 7542** [comment]
ioBroker ... Sonoff-Adapter ?
Ar´nt we talking about TasmoAdmin?

**Comment by ChrisPrefect** [comment]
Yeah, I solved my problem with TasmoAdmin by switching to a whole different platform ;-)

**Comment by pitucorto** [comment]
Hello,

I have the same problem.

![image](https://user-images.githubusercontent.com/3027950/71594387-0d541a80-2b38-11ea-91d5-395acc479c83.png)
