### ISSUE TITLE
Send command error

### ISSUE THREAD

**Issue by riddik14** [TasmoAdmin/TasmoAdmin#221]
I have add command for setup WiFi to multiple device, there use a error. If I send ssid1 WiFi name to SonOff arrive wifiname+space and the device don’t connect

**Comment by reloxx13** [comment]
heya, this will be fixed in 1.16.0 and is fixed in the beta.

if you are using docker you can easily install the beta and test with the "beta" tag.
raymondmm/tasmoadmin:beta

**Comment by riddik14** [comment]
I have master version, can I download develop version on master ?

**Comment by riddik14** [comment]
I use raspberry with apache2

**Comment by inverse** [comment]
Closing due to 4 years stale
