### ISSUE TITLE
TasmoAdmin blips output on start

### ISSUE THREAD

**Issue by pmknowles** [TasmoAdmin/TasmoAdmin#230]
Each time TasmoAdmin starts it seems to 'blip' a relay output on the Tasmota that is a watchdog on my PC so it turns the PC off.
This Tasmota gets a Backlog Delay 3600; Power On command and, if openHAB receives an MQTT response within 5 minutes, the backlog is aborted so the relay doesn't trip.
When TasmoAdmin starts it seems to end the Delay so that the relay blips.
Is it possible to stop that happening?

**Comment by inverse** [comment]
Is this still an issue?

**Comment by pmknowles** [comment]
No idea. Stopped using it shortly afterwards

**Comment by inverse** [comment]
Closing as stale then
