### ISSUE TITLE
Update devices skipping step 1

### ISSUE THREAD

**Issue by PierreScerri** [TasmoAdmin/TasmoAdmin#233]
Update devices is giving this:

```
[23-09-2018 11:43:11][GLOBAL] Start update process
[23-09-2018 11:43:11][ID-3][STEP-2][GLOBAL] Start Step 2
[23-09-2018 11:43:11][ID-3][STEP-2][CHECK] Check Connection | TRY => 1
[23-09-2018 11:43:11][ID-3][STEP-2][CHECK] Connection Successfully! | Current Version => 6.1.1
[23-09-2018 11:43:11][ID-3][STEP-2][OTAURL] Set OTA URL for Firmware => NEW FW
[23-09-2018 11:43:11][ID-3][STEP-2][OTAURL] OTA Url => https://192.168.1.200:9541/data/firmwares/sonoff.bin
[23-09-2018 11:43:11][ID-3][STEP-1][OTAURL] OTA URL set for Firmware => NEW FW
[23-09-2018 11:43:11][ID-3][STEP-2][UPDATE] Trigger device update...
[23-09-2018 11:43:11][ID-3][STEP-2][UPDATE] Device update triggered
[23-09-2018 11:43:11][ID-3][STEP-2][CHECK UPDATE] Wait for update | Seconds => 60
[23-09-2018 11:44:11][ID-3][STEP-2][DONE] ============= Update done! =============
```

and no update takes place.

Tried Automatic and manual update methods to no avail.

Looks like it's not updating to minimal first.

**Comment by reloxx13** [comment]
This is correct, the devices load the minimal themself (see OTAMagic in Tasmota Wiki).

This was made later, thats why it starts with Step2.


Try to update manual and see what is going wrong and check if you can reach the firmware in your browser and the download starts with
https://192.168.1.200:9541/data/firmwares/sonoff.bin
and
https://192.168.1.200:9541/data/firmwares/sonoff-minimal.bin
if not, its a network problem.

**Comment by PierreScerri** [comment]
The urls you suggest give Error 403 forbidden.

I have tried 'manual' from the Tasmoadmin update section.
![tasmoadmin](https://user-images.githubusercontent.com/34303331/45942856-73bcc580-bfe4-11e8-8539-7312ff5bdcda.jpeg)

**Comment by Mar1u503** [comment]
Same Problem here

**Comment by Mar1u503** [comment]
You have to disable ssl in your config of the component in hass.io, then it will work. I had the same problem and without ssl it worked for me.

It seams like you can't download the firmwares from TasmoAdmin over https. The option in TasmoAdmin for downloading over ssl or not doesn't work as it should. You have to completly disable ssl for TasmoAdmin in the hass.io config and then the ui of TasmoAdmin and the downloads work without ssl as they should.

**Comment by PierreScerri** [comment]
You are right. It worked.  Thanks.

**Comment by shawly** [comment]
Disabling security is not a fix...
If I disable SSL then I can't integrate TasmoAdmin into the Home Assistant interface and why would anyone want to run it without SSL?

**Comment by mprins** [comment]
@shawly Yes because using http from a server on the internet is more secure than using http from a server on your LAN which is protected by WPA encryption

**Comment by shawly** [comment]
Your home security is only as secure as the weakest link in the chain. If my LAN ever gets compromised it's better to not leave open doors, so keep your sarcasm for yourself.

**Comment by inverse** [comment]
From what I understand tasmota itself cannot flash when OTA is served up over HTTPS see #730

**Comment by shawly** [comment]
> From what I understand tasmota itself cannot flash when OTA is served up over HTTPS see #730

It cannot, but since the Docker image of TasmoAdmin is using Nginx, you could serve OTA updates over a different port. That would allow users to use a reverse proxy with SSL for the webinterface and still be able to access the updates from a different port which is not reverse proxied with SSL.

I don't think this issue needs to be closed when it could technically be fixed.
