### ISSUE TITLE
[RFE] Send list of commands, per device

### ISSUE THREAD

**Issue by MaceMoneta** [TasmoAdmin/TasmoAdmin#239]
For some of my devices, I use a list of commands to perform additional configuration (e.g., PulseTime<x> <y>, static IP, custom gateway, etc.). It would be nice to be able to associate a list of commands with each device, and have the list of commands resent, manually triggered.

This serves two purposes: If the device needs to be reset, it can be quickly reconfigured, and it documents any special configuration associated with the device.

**Comment by th-s-op** [comment]
+1  That would be an extremely useful feature for the administration of multiple devices!
