### ISSUE TITLE
remove portable app

### ISSUE THREAD

**Issue by riddik14** [TasmoAdmin/TasmoAdmin#251]
is possible remove portable app from package? the problem is who the update download all packet, is toobig from rpi. can you create a folder for portable app as docker xaamp etc?

**Comment by reloxx13** [comment]
uhh you are right, i did not thought about it.

but i would also suggets you to use docker for easier handling and you wont have the zips in it.

i dont know when i can remove/rework the xampp zips.

**Comment by stefan-sherwood** [comment]
It looks like this has been done because I'm looking for it and can't find it :(

**Comment by stefan-sherwood** [comment]
I am looking for a standalone native Windows app. Not a huge deal.
