### ISSUE TITLE
Feature Request: allow devices' Web Interface port to be configured

### ISSUE THREAD

**Issue by th-s-op** [TasmoAdmin/TasmoAdmin#257]
I would like to request that in the "+ Add Device" Dialog, there is an optional entry field for the Web Server port, defaulting to 80.

Being able to change the default port here has two use cases:
- the WEB_PORT is a user configurable option for those who compile Tasmota themselves
- I want to administer some Tasmota devices remotely using SSH tunnels. That means that I will only be able to access several Tasmotas using different ports with the server IP. Ie. device 1 would be 192.168.2.100:10001, the next 192.168.2.100:10002 and so on.

**Comment by th-s-op** [comment]
And just to make sure that I am not misunderstood: I am not talking about the TASMOADMIN web interfaces port on the web server (default 9999). I mean a single Tasmota device listenting to anything else than port 80 with its web server. I couldn't add such a device as of now.

**Comment by inverse** [comment]
@th-s-op finally added support for this edge case
