### ISSUE TITLE
energy monitoring graph

### ISSUE THREAD

**Issue by obbardc** [TasmoAdmin/TasmoAdmin#258]
just installed this, very excited as the sonoff firmware contains no logs.

Are there any plans to add a graph view of energy over time?

cheers!

**Comment by reloxx13** [comment]
i would like that too, but doing it without a database will be really dirty :X

also there is no service in background which could track it 24/7, so the tasmoadmin page needs to be open on atleast one device.

which leads to another issue, if the page is open on multiple devices log duplicates could appear.
i would suggest to use iobroker or a similar ha for this which uses mqtt.

**Comment by obbardc** [comment]
I’m looking into emoncms but it seems very bulky :/

**Comment by Frogmore42** [comment]
There are lots of solutions for this already.  Many Home Automation systems provide a method to persist data and graph it.  Influxdb is a good solution for saving data.  Grafana is a good system for providing graphs and other nice UI to build dashboards.  All of these might seem "bulky" if all you have is a single device and just want a graph from it.  If so, NodeRED and some plug-ins could probably do that.  It all depends on how long you want to keep the data and how much effort you want to put into it, and what type of access you need (local only or remote too).

**Comment by inverse** [comment]
This feels like it's out of scope for what this tool is designed for
