### ISSUE TITLE
interlock

### ISSUE THREAD

**Issue by fragolinux** [TasmoAdmin/TasmoAdmin#265]
hi, does tasmoadmin support setting interlock between relays, for example on a sonoff dual to be used for blinds/curtains, as they never should be ON at the same time to avoid burning the motor? Thanks

**Comment by j0se** [comment]
Interesting. Perhaps a "Blind Mode" in device config

**Comment by fragolinux** [comment]
commands are already in tasmota, just need to be set... even though in case of blinds/curtains, many prefer Stefan Bode tasmota's fork

**Comment by j0se** [comment]
Where I config at dual this feature ?

**Comment by fragolinux** [comment]
SetOption14

**Comment by reloxx13** [comment]
moment: u want to just set this setoption over tasmoadmin?
or u want tasmoadmin to work like this?

**Comment by fragolinux** [comment]
> moment: u want to just set this setoption over tasmoadmin?
> or u want tasmoadmin to work like this?

i mean, in the config page, in general tab or on a new one, some basic settings, like connect or not the physical button to the relay (if a sonoff), allow to set the interlock between the 2 relays in a sonoff dual (like allows Espurna firmware, for example), and so on... instead of remembering or checking the docs to see what each setoption does, it would be very nice and useful to have their options listed with respective real meaning, for an easy setup... it would be a useful addition :)
