### ISSUE TITLE
Update error Incorrect format

### ISSUE THREAD

**Issue by rm369** [TasmoAdmin/TasmoAdmin#270]
After selecting V.6.4.1 binaries downloaded from https://github.com/arendst/Sonoff-Tasmota/releases I get these error messages in the overview screen: (german)
Minimal Firmware: Falsches Format! Bitte eine Minimal Firmware BIN Datei auswählen! application/x-sega-cd-rom!
Full Firmware: Falsches Format! Bitte eine Full Firmware BIN Datei auswählen! application/x-sega-cd-rom!

Indeed the MIME type is identified as
$ xdg-mime query filetype Downloads/sonoff-minimal.bin 
application/x-sega-cd-rom

/usr/share/mime/packages/freedesktop.org.xml seems to identify every *.bin as application/x-sega-cd-rom:
`<mime-type type="application/x-sega-cd-rom">
    
    <comment>Sega CD disc image</comment>
    <comment xml:lang="ast">Imaxe de discu de Sega CD</comment>
    <comment xml:lang="ca">imatge de disc de Sega CD</comment>
    <comment xml:lang="cs">obraz disku CD pro Sega</comment>
    <comment xml:lang="da">Sega CD-diskaftryk</comment>
    <comment xml:lang="de">Sega-CD-Datenträgerabbild</comment>
    <comment xml:lang="en_GB">Sega CD disc image</comment>
    <comment xml:lang="es">imagen de disco CD de Sega</comment>
    <comment xml:lang="eu">Sega CD disko irudia</comment>
    <comment xml:lang="fi">Sega CD -levykuva</comment>
    <comment xml:lang="fr">image disque Sega CD</comment>
    <comment xml:lang="ga">íomhá dlúthdhiosca Sega</comment>
    <comment xml:lang="he">דמות כונן Sega CD</comment>
    <comment xml:lang="hr">Sega CD slika diska</comment>
    <comment xml:lang="hu">Sega CD-lemezkép</comment>
    <comment xml:lang="id">image cakram CD Sega</comment>
    <comment xml:lang="it">Immagine disco Sega Mega CD</comment>
    <comment xml:lang="kk">Sega CD диск бейнесі</comment>
    <comment xml:lang="ko">세가 CD 디스크 이미지</comment>
    <comment xml:lang="pl">Obraz płyty konsoli Mega-CD</comment>
    <comment xml:lang="pt_BR">Imagem de disco Sega CD</comment>
    <comment xml:lang="ru">Образ диска CD Sega</comment>
    <comment xml:lang="sk">Obraz disku CD Sega</comment>
    <comment xml:lang="sr">одраз диска Сега ЦД-а</comment>
    <comment xml:lang="sv">Mega-CD-skivavbild</comment>
    <comment xml:lang="tr">Sega CD disk kalıbı</comment>
    <comment xml:lang="uk">образ диска Sega CD</comment>
    <comment xml:lang="zh_CN">Sega CD 光盘映像</comment>
    <comment xml:lang="zh_TW">Sega CD 光碟映像檔</comment>
    <generic-icon name="application-x-executable"/>
    
    <magic priority="60">
      <match value="SEGADISCSYSTEM" type="string" offset="0">
        <match value="SEGA" type="string" offset="256"/>
      </match>
      <match value="SEGADISCSYSTEM" type="string" offset="16">
        <match value="SEGA" type="string" offset="272"/>
      </match>
    </magic>
    <glob pattern="*.bin"/>
    <glob pattern="*.iso"/>
  </mime-type>`

After renaming the files they are identified as application/octet-stream, copied to /var/www/tasmoadmin/tasmoadmin/data/firmwares/, and updating starts, but after the update the info page still shows the old version number 6.2.1.3.

What can I do?

**Comment by inverse** [comment]
Closing as stale - feel free to open a new issue if this still persists.
