### ISSUE TITLE
Autoscan fails:

### ISSUE THREAD

**Issue by SoundGuy** [TasmoAdmin/TasmoAdmin#273]
I'm running Autoscan for the first time and i'm getting this:

Recoverable fatal error: Object of class stdClass could not be converted to string in /var/www/tasmoadmin/tasmoadmin/includes/Sonoff.php on line 1000

I'm on the latest versnion of Tasmoadmin 0.6.0 and HASS 141 on RPI 1b

**Comment by inverse** [comment]
Closing due to old issue
