### ISSUE TITLE
[Question] SSL support on TasmoAdmin but not on Tasmota

### ISSUE THREAD

**Issue by gabrielboliveira** [TasmoAdmin/TasmoAdmin#274]
Hello! First of all, thanks for this amazing software 🎉 

I have a few questions regarding SSL support. From [Tasmota Upgrade wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Upgrade#firmware-binary-sources), HTTPS upgrade is not supported by Tasmota.

I'm using TasmoAdmin as Home Assistant add-on, and by default the `ssl` config is set to true. If I try to do an Update via TasmoAdmin and set OTA Server IP to `whatever-my-hassio-domain-is.com`, enable `OTA Use SSL` and upload my own builded `.bin` file, it won't work. If I try to access the file, I get a 403.

It only works if I disable `ssl` at HassIO **and** disable the `OTA Use SSL`. If I only disable `ssl` option, it gives a `400 Bad Request`, since it only accepts HTTPS requests.

Is this a Home Assistant add-on error? Why do we have a `OTA Use SSL` option if Tasmota doesn't support it?

Thanks!

**Comment by Mace404** [comment]
Can confirm this behaviour.

**Comment by Wihanh** [comment]
I am seeing this behavior as well.
If you use tasmoadmin with ssl enabled, the web UI works fine over HTTPS, but the links that gets used for OTA updates give a 403 error, and you can obviously not use these links over HTTP while the add on is set to enable SSL.  It is not that tasmota doesn't support SSL, it is that the SSL links for the OTA process does not work, you can't pull the file from there.
If you disable SSL, and use tasmoadmin over HTTP, and untick the OTA over SSL , the link to the firmwares change to HTTP and that does work.
Obviously using the HTTP link while SSL is set to true in the add on will not work either.

**Comment by garymcleanuk** [comment]
Still happening.. Cant update.. 

Errors.. The plain HTTP request was sent to HTTPS port

**Comment by hapklaar** [comment]
Running into this as well. Is there a solution?

**Comment by inverse** [comment]
As far as I understand it's an issue with Tasmota itself being unable to use HTTPS with OTA updates. See #730
