### ISSUE TITLE
Undefined property error

### ISSUE THREAD

**Issue by Funkem** [TasmoAdmin/TasmoAdmin#280]
I've got a probably fixed error again. Maybe is the case our special environment. The IP range with tasmota devices are from 172.16.24.1 - 172.16.25.254. And the special case is different passwords on my tasmota devices.
Maybe is this the reason for the exception:

undefined property: stdclass::$statusnet in /var/www/tasmoadmin/tasmoadmin/pages/devices_autoscan.php
Trying to get property of non-object in /var/www/tasmoadmin/tasmoadmin/pages/devices_autoscan.php

The latest TasmoAdmin was installed on XAMP@Windows 10 and on a Raspi 3B+ device. So I think, the fix 

    if ( empty ($device)  || ! empty($device->error))            <---  Added
        continue;                                                                    <---  Added

is included. The exception occurs on both devices. Furthermore, the TasmoAdmin AutoScan works fine in the same devices and in another network with IP Range 192.168.178.1-254, but there are no password settings on the devices.

Additional. Different Tasmota versions from 5.1 up to 6.3.

Can you check this @reloxx13 ? Do you need more informations from me? Thanks a lot for your work.

**Comment by inverse** [comment]
Closing as stale - feel free to open a new issue if this issue still persists on the latest version.
