### ISSUE TITLE
The Page of tasmoadnub won't load, why?

### ISSUE THREAD

**Issue by shayshtern** [TasmoAdmin/TasmoAdmin#281]
![image](https://user-images.githubusercontent.com/4135420/52350501-6a7f4300-2a31-11e9-8081-002cee0f7fd7.png)

**Comment by j0se** [comment]
Where do you installed tasmoadmin ? Perhaps issue in enviroment, webserver or php

**Comment by bennybubble** [comment]
I have a similar issue, tried to install it on Ubuntu 18.0.4 LTS but cannot get it to work.
I noticed that the default document root in 18 is in /var/www/html.
Something is already running at port 80, so I changed this to port 8010 but without any luck, is there a updated installer for ubuntu 18 ?

Thanks

**Comment by j0se** [comment]
@bennybubble  if you open http://localhost you see the apache default web ??? if YES... you could uncompress the zip with TasmoAdmin in **DocumentRoot** ( /var/www/html )
