### ISSUE TITLE
Is it possible to find all McLighting eps8266 device in TasmoAdmin? 

### ISSUE THREAD

**Issue by lampenschakelen** [TasmoAdmin/TasmoAdmin#286]
First of all thanks a lot for making TasmoAdmin! 
Iam very happy with the easy interface to control and find my devices!! Keep up the good work!

Is it possible to find also other devices? In TasmoAdmin? 

I am using McLighting for controling ws2812 led strips. 
https://github.com/toblum/McLighting

I would be great to control and update the device directly from TasmoAdmin.

**Comment by debsahu** [comment]
Interested in what response we get here, let me know what needs to be added to McLighting.
