### ISSUE TITLE
Permissions issue in docker container when using persistent storage/volume

### ISSUE THREAD

**Issue by bigcookie** [TasmoAdmin/TasmoAdmin#287]
Hello,

not sure, if this is the right place to phrase the request. I installed the Docker image (tag:latest) based on the wiki installation and used the option to mount a local host folder to the /data folder inside the container.
Environment: QNAP TS-653B, QNAP 253 Pro.
I had no problem creating and testing the container without external volume, but when using the volume option, nginx couldnt access "devices.csv" nor "MyConfig.json". At first, the file was not found. Then I change the ownership of the files to "chown nginx:nginx FILENAME", which ended up in "permission denied".
I had to do the following for the whole "/data" folder within the container to make it work:
"chown nginx:nginx -R /data".
The issue is reproducible 100% on both of my QNAP NAS using Container Station. When inspecting the container, the volume was mounted correctly. Also other files have been created properly without any permission modification (tasmoadmin folder, nginx folder with its files...)

As I havent read from this issue in any other case, it might be QNAP specific - but I am not sure. Any chance to fix this? Which other information is needed?

regards,

André

**Comment by rAdziuB** [comment]
I have the same issue on my QNAP TS-453Be
