### ISSUE TITLE
Changing the username in settings doesnt work without restarting container

### ISSUE THREAD

**Issue by bigcookie** [TasmoAdmin/TasmoAdmin#288]
I used the settings page after a complete setup to change username and password. The MyConfig.json shows the new username. Container was not restarted.
Unfortunately login only works with the "old" username "admin", even though I chose another one. Only restarting the container made TasmoAdmin use the changed username.

**Comment by inverse** [comment]
I'm unable to reproduce this... 

- Changed username in backend
- Logged out
- Logged in with new username
