### ISSUE TITLE
Unraid HA not showing contents of tasmoadmin - blank page

### ISSUE THREAD

**Issue by balvant813** [TasmoAdmin/TasmoAdmin#289]
oops!

**Comment by Cristi46** [comment]
Hi balvant, I run into the same issue. Din you manage to see why this behavior?

**Comment by balvant813** [comment]
It just takes long time to discover all  devices. Do a test and Try  a smaller range of IPS (e.g .xxx.101-110

 

It will work fine

 

Patel
