### ISSUE TITLE
Autoupdate w/ thehackbox binaries

### ISSUE THREAD

**Issue by raulvasquez** [TasmoAdmin/TasmoAdmin#295]
Is it possible to set thehackbox as an update option over the GitHub repo? Between the different cores and versions, they have more available. I've played around with the MyConfig.json, but it doesn't seem quite as simple as just changing the URL.

http://thehackbox.org/tasmota/020502/

**Comment by reloxx13** [comment]
Future plan is to choose a version from thehackbox.

**Comment by inverse** [comment]
Closing as stale and domain looks expired.
