### ISSUE TITLE
Server config - 404 Not found

### ISSUE THREAD

**Issue by emmenne** [TasmoAdmin/TasmoAdmin#301]
Hi to all!
On Raspian Buster Tasmoadmin seems not to work: <b>ERROR: PHP Curl is missing.Please install PHP Curl sudo apt-get install php7.0-curl and restart webserver</b>.  Any solutions?

**Comment by yann1420** [comment]
Same here (on raspbian buster) , and per the instruction fired
- sudo apt-get install php-curl php-zip
- sudo a2enmod rewrite
- sudo /etc/init.d/apache2 restart

but get a 404 . After typing an explicit index.php , the first screen pops up, but all follow up actions and again in a 404 error. The apache errorlog shows e.g. this line  
_PHP Fatal error:  Uncaught Error: Call to a member function readAll() on null in /var/www/html/tasmoadmin/pages/devices_autoscan.php:100\nStack trace:\n#0 {main}\n  thrown in /var/www/html/tasmoadmin/pages/devices_autoscan.php on line 100_

**Comment by gknauf** [comment]
@yann1420 that sounds as if the .htaccess is not activated; you need to allow to process it;
for this you need to set the AllowOverride-Directive for the tasmoadmin directory:
http://httpd.apache.org/docs/current/de/mod/core.html#allowoverride

**Comment by reloxx13** [comment]
Still problems?

**Comment by inverse** [comment]
Closing as stale
