### ISSUE TITLE
Problem to update Firmware

### ISSUE THREAD

**Issue by alesoft73** [TasmoAdmin/TasmoAdmin#314]
Dear,
when i press to update and automatic i receive this message :    
                                                         
Notice: Undefined property: stdClass::$assets in /var/www/tasmoadmin/tasmoadmin/pages/upload.php on line 174

Warning: Invalid argument supplied for foreach() in /var/www/tasmoadmin/tasmoadmin/pages/upload.php on line 174

Many thanks for your work!

**Comment by mprins** [comment]
have you updated to the latest release yet? https://github.com/reloxx13/TasmoAdmin/releases/tag/v1.6.1-beta3

**Comment by reloxx13** [comment]
sonoff-tasmota changed its name to tasmota.
latest tasmoadmin is prepared for this.

its still in beta thats why you dont get it.

for now just download the minimal and normal bin files from tasmota and use manual update.

the renaming is still in progress.

bin files:
https://github.com/arendst/Tasmota/releases

**Comment by alesoft73** [comment]
Many thanks, 
Yes i have work in this mode....
I attend the update.
Thanks another and sorry if i disturb!
BYE!
