### ISSUE TITLE
Error 500 after Update 1.6.1

### ISSUE THREAD

**Issue by flolo81** [TasmoAdmin/TasmoAdmin#316]
Unfortunately I receive the error 500 after updating to version 1.6.1. The issue occurs directly after opening the tasmoadmin-url in the following enviroments:

- Appache 2.2 with PHP 7.0
- Appache 2.4 with PHP 7.3

I was only able to solve the problem by downgrading to 1.6.0

**Comment by reloxx13** [comment]
Heya,

you have to take a look into `/var/log/apache2/error.log`

you can tail it and then call the website to see the live error msg.

`sudo tail -fn300 /var/log/apache2/error.log`

I need this error message or log to fix it.

**Comment by inverse** [comment]
Closing as old - please create a new ticket if you notice this on the latest version.
