### ISSUE TITLE
json error after updating curl and python on raspberry

### ISSUE THREAD

**Issue by tjareson** [TasmoAdmin/TasmoAdmin#317]
Unfortunately I cannot reopen the issue, as I didn't close it (see #306)

So here is the follow-up:
The error wasn't actually only for one device, but for all of them. The device names as such also didn't change. The problem occured right after the update of raspbian.
I meanwhile deleted the docker container and reinstalled it including pulling the docker image, in case there was an update.
In the new installation of the docker version of TasmoAdmin I've tried to search for devices (I have approx. 20 of it based on sonoff) the search returned no devices found within a second or so.
So I guess it must be something more fundamental. Any hint where I could start with debugging?
IP range is x.x.x.20 to x.x.x.200, so 180 IPs.
I can't imagine that the scan could work within one second only, as there is a timeout per address for sure. So there is something else wrong.

-----------------------------------------------------------------------------

i dont thionk this is related to ur update.

the json response from the device seems to be wrong.

you need to check it in ur browser with
http://YOURDEVICEID/cm?cmnd=status%200

usually there is a hidden newline in hostname/mqttname cause of copypaste destroying the json.

reopen if the issue persists.
---------------------------------------------------------------------------
Hi,
I'm using tasmoadmin 1.6.0 in docker.
I've updated my raspbian jessie today, mainly curl and python related updates (details see below).
Since then I get an error when tasmoadmin tries to get the status from the sonoff modules:
JSON FEHLER => 4: Syntax error

Any ideas what might be the issue here?

The updates done on raspbian jessie are:
Commandline: apt upgrade
Upgrade: libpython2.7-minimal:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), python2.7:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), libpython2.7-stdlib:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), libcupsimage2:armhf (1.7.5-11+deb8u4, 1.7.5-11+deb8u6), libssl-dev:armhf (1.0.1t-1+deb8u11, 1.0.1t-1+deb8u12), libcurl3:armhf (7.38.0-4+deb8u15, 7.38.0-4+deb8u16), libgcrypt20:armhf (1.6.3-2+deb8u5, 1.6.3-2+deb8u7), libssl-doc:armhf (1.0.1t-1+deb8u11, 1.0.1t-1+deb8u12), curl:armhf (7.38.0-4+deb8u15, 7.38.0-4+deb8u16), openssl:armhf (1.0.1t-1+deb8u11, 1.0.1t-1+deb8u12), libcurl3-gnutls:armhf (7.38.0-4+deb8u15, 7.38.0-4+deb8u16), python2.7-minimal:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), libcups2:armhf (1.7.5-11+deb8u4, 1.7.5-11+deb8u6), libpython2.7:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), wpasupplicant:armhf (2.3-1+deb8u8, 2.3-1+deb8u9), libssl1.0.0:armhf (1.0.1t-1+deb8u11, 1.0.1t-1+deb8u12)

Thanks,
Tjareson

**Comment by reloxx13** [comment]
Heya,

what is the repsone from

**Comment by tjareson** [comment]
That is what one of the sonoff devices are sending back:
- I've overwritten the ssid 
- all sonoffs are on version 6.5.0


{"Status":{"Module":1,"FriendlyName":["sensor-heating01"],"Topic":"sensor-heating01","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"SaveData":0,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-DE.bin","RestartReason":"Power on","Uptime":"57T17:49:13","StartupUTC":"2019-09-07T15:09:55","Sleep":50,"CfgHolder":4617,"BootCount":10,"SaveCount":30,"SaveAddress":"F6000"},"StatusFWR":{"Version":"6.5.0(release-sonoff)","BuildDateTime":"2019.03.19 12:30:37","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["xxxxxxxx",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]},"StatusMEM":{"ProgramSize":508,"Free":492,"Heap":13,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000407","0FDAE394","000783A0","23B617CE","00003BC0"]},"StatusNET":{"Hostname":"sensor-heating01-1330","IPAddress":"192.168.2.61","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1","Mac":"5C:CF:7F:42:25:32","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"192.168.2.3","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_422532","MqttUser":"DVES_USER","MqttCount":1768,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Mon Nov 04 08:59:08 2019","Local":"Mon Nov 04 09:59:08 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"07:41","Sunset":"17:25"},"StatusSNS":{"Time":"2019-11-04T09:59:08","DS18B20-1":{"Id":"0316B550E7FF","Temperature":16.4},"DS18B20-2":{"Id":"0316B587A4FF","Temperature":16.3},"TempUnit":"C"},"StatusSTS":{"Time":"2019-11-04T09:59:08","Uptime":"57T17:49:13","Vcc":3.239,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"xxxxxxxx","BSSId":"18:D6:C7:CA:7A:5C","Channel":11,"RSSI":34,"LinkCount":8,"Downtime":"0T00:02:20"}}}

**Comment by tjareson** [comment]
This is what I get back when searching for devices. The reply happens within less than a second.

![image](https://user-images.githubusercontent.com/7828028/68109523-0370bb00-feeb-11e9-9fd9-d04a04ba653a.png)

**Comment by reloxx13** [comment]
Thank you, this is valid json.

I have to investigate further in autoscan.

**Comment by tjareson** [comment]
What is maybe important: there was no change in the configuration as such. Neither on Tasmota-firmware version nor its configuration (like hostname etc). Also the docker image didn't change before the error occured. The only thing that happened was the linux update. Afterwards the error occured and also scan doesn't work anymore. Then I've reinstalled the docker image incl. pulling it again.
Let me know if I can provide any logs or something. 
The change log shows:
Upcoming
v1.6.2-beta1
...
v1.6.1

So I'm assuming my current TasmoAdmin version is v1.6.1 now.

**Comment by reloxx13** [comment]
just to be sure, your SSID does not have any special chars.

special "/" or "\" 

"-_.," should not be a problem.

**Comment by tjareson** [comment]
Not it doesn't. Just letters, no special characters at all. It also didn't change.

**Comment by tjareson** [comment]
Is there any further information I can provide for technical analysis? I'm still facing the same issue...
