### ISSUE TITLE
New Curl version

### ISSUE THREAD

**Issue by maxbec** [TasmoAdmin/TasmoAdmin#320]
I just installed tasmoadmin with the Linux tutorial.
The package php7.0-curl is not available anymore on apt. So i installed 7.2

Now i got this error:
ERROR: PHP Curl is missing.Please install PHP Curlsudo apt-get install php7.0-curland restart webserver

**Comment by reloxx13** [comment]
hey,
check which php version is install

php -v

and install the correct curl.

latest php is 7.3.

**Comment by LucReynders** [comment]
I faced the same problem. I used the guide according to the linux tutorial.
Could not install with the php 7.0 version only php 7.3.
The apache server is working,  it shows the standard debian apache2 index.html file in the browser.
Why is the tasmoadmin page not loaded ?  the index.php (and other files) is located in the /var/www/tasmoadmin/tasmoadmin as it should be.

**Comment by Icefox2k** [comment]
I had the same Problem installing Tasmoadmin on Debian Buster
you have to install curl and zip for php 7.3 with the following command

`apt-get install  php7.3-curl php7.3-zip`

the directorys you have to edit are also renamed with "7.3"

**Comment by inverse** [comment]
Closing as old - please open a new ticket if you notice this happening
