### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by rookie7799** [TasmoAdmin/TasmoAdmin#324]
Running docker image:

`sudo docker run -d --restart unless-stopped -v /home/homeassistant/.homeassistant/docker:/data -p 8124:80 --name tasmoadmin raymondmm/tasmoadmin`

I can see the page when going to the web browser and entering: http://192.168.1.13:8124

But when do a curl from the same server the docker is running on I get:

curl "http://192.168.1.13:8124"
\<html\>
\<head>\<title>301 Moved Permanently</title></head>
\<body bgcolor="white">
\<center>\<h1>301 Moved Permanently</h1></center>
\<hr>\<center>nginx/1.14.0</center>
\</body>
\</html>

And as a result (I think) home assistant cannot load this page as well.

**Comment by reloxx13** [comment]
heya, 

nope, this wont be the reason. 
tasmoadmins docker is blocking bots and no user agent sends

https://github.com/reloxx13/TasmoAdmin/blob/master/.docker/rootfs/etc/nginx/nginx.conf
```
if ($http_user_agent = "") {
    return  301 $scheme://www.google.com/;
}

if ($limit_bots = 1) {
    return  301 $scheme://www.google.com/;
}
```

you can set a custom user agent in ur curl request an it should work then.

would be interesting if HA is sending a user agent.

**Comment by reloxx13** [comment]
try it with a custom nginx config

https://github.com/reloxx13/TasmoAdmin/wiki/Custom-nginx.config

copy the content of the default nginx config and remove one
```
if ($http_user_agent = "") {
    return  301 $scheme://www.google.com/;
}
```
try again

if still not working remove
```
if ($limit_bots = 1) {
    return  301 $scheme://www.google.com/;
}
```
and try again.

Please post feedback that we can fix it by either allow emty or remove a bot-detected HA user agent.

**Comment by rookie7799** [comment]
Hi, thanks for the feedback, the issue is - i'm running docker, so that complicates things a bit?

**Comment by reloxx13** [comment]
the nginx config is shared in your data directory.

**Comment by rookie7799** [comment]
removed those IFs and it now works if I call it via console but HA is still having issues - likely a HA issue then. I think we can close out the ticket. Thank you!
