### ISSUE TITLE
Update TasmoAdmin on Docker (Synology)

### ISSUE THREAD

**Issue by hwiedermann** [TasmoAdmin/TasmoAdmin#329]
Hi there,

i have installed Docker on Synology, in there TasmoAdmin. Now would like to have the newest tasmoAdmin version 1.6.3, without reconnect all my Tasmota Devices to TasmoAdmin.

What to do?

**Comment by reloxx13** [comment]
Heya,
you should have a data volume where your device list and config is saved.
in dont own a synology nas, but im sure u have the options to set thi data dir.

**Comment by inverse** [comment]
Closing as stale  - please open another issue if you're still struggling.
