### ISSUE TITLE
403 error in hassio on RasPi

### ISSUE THREAD

**Issue by alekseyn1** [TasmoAdmin/TasmoAdmin#331]
Hello,
Apologies if this has been discussed before.
Trying to use the latest Hassio on RasPi to upgrade devices.
used an automated and manual methods. Every option I use - update fails.

When trying to access the bin location using a browser 
https://CEN.CORED.org:9541/data/firmwares/tasmota.bin
I am getting 403 (forbidden) error.

Any way to fix this?

**Comment by SxthGear** [comment]
Apparently updates over SSL are not supported right now. You'll have to go into the addon config and disable SSL support for the addon and then untick the "OTA use SSL". It should work after that.

**Comment by alekseyn1** [comment]
Thanks you @SxthGear . This works.  For anyone who will find this issue: 
1. Disable SSL in the addon config ("ssl: false")
2. Restart addon
3. During addon Update command untick the "OTA use SSL" (tested with 'Automatic')
should work after that

**Comment by inverse** [comment]
This should be cleaned up with #730
