### ISSUE TITLE
Curl 28

### ISSUE THREAD

**Issue by 7542** [TasmoAdmin/TasmoAdmin#334]
anyone here who can helb me with Curl 28? since i have more than 15 items in tasmoadmin on raspi4-buster i get "CURL-Fehler => 28" on a few device which before did´nt make problems.

**Comment by 7542** [comment]
for example status 0 of one of the devices that can not be connected any more by tasmoadmin:
12:54:32 CMD: status 0
12:54:32 RSL: STATUS = {"Status":{"Module":4,"FriendlyName":["TempKuehlschrankKueche"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
12:54:32 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.10.48:9999/data/firmwares/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:21","StartupUTC":"2019-12-15T11:54:11","Sleep":50,"CfgHolder":4617,"BootCount":49,"SaveCount":133,"SaveAddress":"F6000"}}
12:54:32 RSL: STATUS2 = {"StatusFWR":{"Version":"6.7.1(sonoff)","BuildDateTime":"2019.10.26 13:25:04","Boot":6,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)"}}
12:54:32 RSL: STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":1,"LogHost":"192.168.10.48","LogPort":514,"SSId":["fritz-kabel","NETGEAR_11gn"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008005","2805C8000100060000005AFF000000000000","00000008"]}}
12:54:32 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":564,"Free":436,"Heap":28,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000407","8FDAE397","043683A0","22B617CD","01001BC0","0000F081"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,30","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
12:54:32 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoff-5938","IPAddress":"192.168.10.119","Gateway":"192.168.10.3","Subnetmask":"255.255.255.0","DNSServer":"192.168.10.3","Mac":"5C:CF:7F:68:77:32","Webserver":2,"WifiConfig":4}}
12:54:32 RSL: STATUS7 = {"StatusTIM":{"UTC":"Sun Dec 15 11:54:32 2019","Local":"Sun Dec 15 12:54:32 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:36","Sunset":"16:53"}}
12:54:32 RSL: STATUS10 = {"StatusSNS":{"Time":"2019-12-15T12:54:32","DS18B20-1":{"Id":"01187A3E59FF","Temperature":28.6},"DS18B20-2":{"Id":"01187A5C72FF","Temperature":6.2},"DS18B20-3":{"Id":"01187A5DDFFF","Temperature":-13.7},"DS18B20-4":{"Id":"01187B308CFF","Temperature":7.7},"TempUnit":"C"}}
12:54:32 RSL: STATUS11 = {"StatusSTS":{"Time":"2019-12-15T12:54:32","Uptime":"0T00:00:21","UptimeSec":21,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":20,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"fritz-kabel","BSSId":"34:31:C4:54:23:CB","Channel":13,"RSSI":82,"LinkCount":1,"Downtime":"0T00:00:05"}}}

**Comment by inverse** [comment]
curl 28 is when the connection times out - are you still seeing this issue? What actions cause it to happen?
