### ISSUE TITLE
OTA address IP-how setup

### ISSUE THREAD

**Issue by ghost** [TasmoAdmin/TasmoAdmin#339]
Hi
How setup in TasmoAdmin address IP to donwload latest version from github ?
Example how setup to download version PL....

**Comment by reloxx13** [comment]
In tasmoadmin settings you set it to polski (i saw u did this in your other issue).
This language is taken when using "automatic mode" on the device update page.

**Comment by inverse** [comment]
Closing as stale - feel free to open a new issue if this issue still persists on the latest version.
