### ISSUE TITLE
Support OpenBSD/Non-Apache Webserver (no mod_rewrite)

### ISSUE THREAD

**Issue by psergiu** [TasmoAdmin/TasmoAdmin#34]
It seems that most of the pages require Apache's mod_rewrite in order to make "nice" URLs.

Is there a setting to use the standard "ugly" URLs in order to be able to run SonWEB on web servers without support for Apache's mod_rewrite ( like OpenBSD's httpd )

Thanks.

**Comment by davidlb** [comment]
It's not related to OpenBSD but also for all non apache webserver, Nginx (on Linux, *BSD, ...)

**Comment by jaysuk** [comment]
I second that. I also run nginx

**Comment by tprelog** [comment]
This works now! I am running TasmoAdmin on FreeNAS (iocage-jail) using nginx and php72.

I installed the following packages:
nginx
php72
php72-zip
php72-curl
php72-json
php72-session
php72-filter

I used the nginx/nginx.conf and php-fpm.d/www.conf provided for docker and made some minor changes to reflect running on freenas.

I also made a v2plugin (based on iocage) for FreeNAS as well.

**Comment by inverse** [comment]
This should probably be turned into a wiki for other server configurations. gonna close for now as its kinda stale
