### ISSUE TITLE
Device double in the list

### ISSUE THREAD

**Issue by chrisgott** [TasmoAdmin/TasmoAdmin#355]
After scanning the network for tasmota devices some devices are double in the list. in my case all of them are powerplugs wich come with rgb-led and power monitoring.

rescanning (even if deleted manually before) brings back all devices and their doubles.

All fields in the table (ip, status,...) are the same for the original and its copy exept the name who differs. The names are taken from Friendly Name 1 and Friendly Name 2 from the 'other parameters' in the device config.

**Comment by alexhk** [comment]
Actually I assumed that was be design when two outputs are present.

For instance, I have some Gosund SP112 which have two outputs (one power and one USB). They show up twice in the list and I can control the outputs individually, but they show up using the same Pos. No.

![image](https://user-images.githubusercontent.com/1495412/75312816-66e87500-585b-11ea-9d2f-30cd1f78f209.png)

**Comment by herrlado** [comment]
I have also several devices with two or more switches. But if the sofware manages tasmota devices, why it does show mqtt friendly names?  I quest it must be a setting telling, show me just physical devices.

**Comment by reloxx13** [comment]
@herrlado it shows the friendly name set for the alexa/google emulators (hue/wemo).

So actually, yes it shows a duplicate for every switch (powerX in status 0).

@chrisgott can you provide a status 0 json response?

I dont understand if this is a bug or not.

**Comment by chrisgott** [comment]
here is status0:

{"Status":{"Module":0,"DeviceName":"charger_c","FriendlyName":["charger_c","Tasmota2"],"Topic":"sonoff/charger_c","ButtonTopic":"0","Power":1,"PowerOnState":1,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}

this random device (a plug with powermonitoring) is listet as charger_c and as Tasmota2. it appears for all plugs with powermonitoring. all of them are listet twice with the same ip adress and the same version, runtime, energy,... only name and status differs.

**Comment by daballiemo** [comment]
My status0

`16:00:38 MQT: stat/tasmota_D542CF/STATUS = {"Status":{"Module":18,"DeviceName":"tasmota_D542CF LED Keukentafel","FriendlyName":["tasmota_D542CF LED Keukentafel","Tasmota2"],"Topic":"tasmota_D542CF","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}`
Device is a QuinLED, double LED dimmer. And as mentioned before the extra friendly names are added as devices (even if given the same name)

**Comment by daballiemo** [comment]
Hi, any update on this?

Kr,

Han
