### ISSUE TITLE
Proper dependency management?

### ISSUE THREAD

**Issue by inverse** [TasmoAdmin/TasmoAdmin#358]
How open is this community for adopting proper dependency management?

- composer for php 
- npm for front end assets? 

It'll make the barrier for entry slightly higher but the reward will pay off.

**Comment by reloxx13** [comment]
Heya,
i know, this sucks :D
To much work to change now, i would rather make a remake in nodejs and expressjs of tasmoadmin :X

**Comment by inverse** [comment]
Woah pivoting away completely from PHP would be a big change. 

Whatever motivates you and helps the project move forward!

**Comment by inverse** [comment]
Related #455
