### ISSUE TITLE
"All Off" button not working correctly for Sonoff T1 modules

### ISSUE THREAD

**Issue by aschoelzhorn** [TasmoAdmin/TasmoAdmin#364]
I have a Sonoff T1 2CH Module and the "All off" switches off only the first of the  two switches

**Comment by reloxx13** [comment]
Can you provide a status 0 from this device?

i dont have a 2 channel switch here, but i can emulate one with the json from your device.

**Comment by aschoelzhorn** [comment]
> Can you provide a status 0 from this device?
> 
How do I do this?

**Comment by aschoelzhorn** [comment]
@reloxx13 
`
{"Status":{"Module":29,"DeviceName":"Wohnzimmer Lichtschalter 1","FriendlyName":["Wohnzimmer Lichtschalter 1","Wohnzimmer Lichtschalter 2"],"Topic":"tasmota_86E1C3","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
`
