### ISSUE TITLE
Multiple select option for devices.php? 

### ISSUE THREAD

**Issue by HighOnVoltage** [TasmoAdmin/TasmoAdmin#366]
When it comes to deleting or configuring I'd really love the ability to select multiple devices. 

Currently we have to individually select them. When you delete a device it asks for conformation then displays another page "Device deleted", this is quite time consuming if there are multiple devices.

**Comment by alekseyn1** [comment]
This would be very handy when deleting multiple devices (due to dynamic IP change for example)

**Comment by inverse** [comment]
Multiple device delete will be coming in the next release
