### ISSUE TITLE
Column sort device list

### ISSUE THREAD

**Issue by jimtng** [TasmoAdmin/TasmoAdmin#376]
It would be nice to be able to sort on the column names on the device list screen, ascending/descending. Sort by name, ip, state, version, etc.

**Comment by zuhair68** [comment]
I have more than 60 devices, sorting at least by device name will make my life much easier.

**Comment by reloxx13** [comment]
Heya,

i undertand the trouble, but right now i see no fast solution for this.
Would need to completly rebuild the table logic :(

Someday ill remake this with nodejs and try to remember to make it sortable :D

For now, i sort them myself with the device positions or at desktop with ctrl+f to find one.

**Comment by daballiemo** [comment]
+1

**Comment by netstx** [comment]
This would be an absolutely awesome feature to have, everything else works great for me.

**Comment by PhilipWhiteside** [comment]
For those that **must** have this feature, it can be accomplished with a user script, mostly. It can sort the table, except the 1st line, as it falls out of the table for some reason. 59 rows out of 60 isn't bad for 2 minutes of work.

A user script can be run with either a violentmonkey, greesemonkey, or tampermonkey, etc browser extension. Original JS code is from this post https://stackoverflow.com/questions/14267781/sorting-html-table-with-javascript.

On the device page, select the extension, and make a new script for it. Then add the code from the stackoverflow post.

```javascript
// ==UserScript==
// @name        <WHAT YOU WANT TO CALL IT>
// @namespace   Violentmonkey Scripts
// @match       <YOUR TASMOADMIN PAGE PATH>
// @grant       none
// @version     1.0
// @author      -
// @description 09/11/2021, 19:48:27
// ==/UserScript==

const getCellValue = (tr, idx) => tr.children[idx].innerText || tr.children[idx].textContent;

const comparer = (idx, asc) => (a, b) => ((v1, v2) => 
    v1 !== '' && v2 !== '' && !isNaN(v1) && !isNaN(v2) ? v1 - v2 : v1.toString().localeCompare(v2)
    )(getCellValue(asc ? a : b, idx), getCellValue(asc ? b : a, idx));

// do the work...
document.querySelectorAll('th').forEach(th => th.addEventListener('click', (() => {
    const table = th.closest('table');
    Array.from(table.querySelectorAll('tr:nth-child(n+2)'))
        .sort(comparer(Array.from(th.parentNode.children).indexOf(th), this.asc = !this.asc))
        .forEach(tr => table.appendChild(tr) );
})));
```

Reload and click the headings. 

![Screenshot from 2021-11-09 19-48-11 150040209](https://user-images.githubusercontent.com/22427598/140994735-1cfdba5a-175f-4ceb-8ff6-931a8cd0cffe.png)

![Screenshot from 2021-11-09 19-45-08 914455953](https://user-images.githubusercontent.com/22427598/140994753-3e8d4b36-dfd6-409e-9e42-b1fa539ddf2e.png)

![Screenshot from 2021-11-09 19-44-59 464259729](https://user-images.githubusercontent.com/22427598/140994757-6e423cd8-20bd-4125-ba7e-75b602424c41.png)

**Comment by alexdelprete** [comment]
@inverse if you can take a look at this, it is really important: I had to reorganize all my devices (40 of them) and without sorting I had to switch back and forth to find things. Hope it's not too complicated to implement. :)

**Comment by inverse** [comment]
Sorting is now available since https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.2.0

**Comment by alexdelprete** [comment]
Thanks a lot. :)
