### ISSUE TITLE
Enhancement suggestions

### ISSUE THREAD

**Issue by gknauf** [TasmoAdmin/TasmoAdmin#391]
Hi,
I think it would be useful if the colors of the rows of the devices view could be configured; f.e. the grey color of a hovered row is very hard to see ...
It might be useful (at least for me) to temporarily switch devices offline, f.e. if one works on a device for improvements which might probably take few days.

@reloxx13 please tell me in which file the colors for the rows of the devices view are set, then I might play a bit with different colors. Also I would like to know how/where the on/off times of the auto night mode are calculated; for me these do not match to sunrise/sunset.

**Comment by reloxx13** [comment]
Heya,
its not calculated because i dont have a position atm.
It takes the browser clock.
  
https://github.com/reloxx13/TasmoAdmin/blob/6db3cef7bb5fe8caa188bf393669ae9a220df465/tasmoadmin/resources/js/app.js#L790-L791


You can make own styles in resources/css/custom.css

I include it if it exists
```
<?php if (@file_exists(_RESOURCESDIR_ . "css/custom.css")): ?>
   <link href="<?php echo UrlHelper::STYLES("custom"); ?>" rel="stylesheet">
<?php endif; ?>
```
