### ISSUE TITLE
JSON CONFIG ERROR because of empty MyConfig.json file

### ISSUE THREAD

**Issue by antonio-fiol** [TasmoAdmin/TasmoAdmin#401]
I was seeing this JSON CONFIG ERROR when trying to access tasmoadmin (addon), which had been working in the past, possibly after some upgrades.
After some time trying to understand the meaning and seeing that no logs were helping, by inspecting the code I found that the error was coming from this line:
https://github.com/reloxx13/TasmoAdmin/blob/4deb32146270ee373721280bcf41a597cc59f20f/tasmoadmin/includes/Config.php#L112

That obviously meant that the MyConfig.json file was there, readable and all, but then the JSON parser failed.

 I attached to the docker container of the addon and found that the MyConfig.json file was empty (zero bytes long).

I have no clue how the file became empty... possibly after some corner case migrating from 1.4.0 config, I really don't know and have no way to reproduce it.

I removed the MyConfig.json file (actually, renamed), and then it got working again.

So, may I suggest that the empty config case is tested, and acted upon?

**Comment by inverse** [comment]
Is this still an issue?
