### ISSUE TITLE
Operation across VLANs

### ISSUE THREAD

**Issue by unmesh59** [TasmoAdmin/TasmoAdmin#402]
I'm running the Windows Portable XAMPP version on my main VLAN whereas the Tasmotized devices are on another VLAN. My router/firewall does allow access across VLANs so that I can, for example, access the device Web GUIs. TasmoAdmin however does not work.

Is it expecting the devices to be on the same L2 network as XAMPP?

Thanks

**Comment by rapi3** [comment]
No problem for me. I am having my devices on another (v)lan than TasmoAdmin web server so in Auto Scan I enter lan IP range for Tasmota devices and scan and all are found and work without problem.

**Comment by unmesh59** [comment]
I just tried it again and it worked! I'm pretty sure I made no network changes in the interim.

Somewhat off topic but would upgrading to a more recent version of xampp work?

**Comment by alphayyz** [comment]
I'm also having this same issue.  TasmoAdmin only sees my Tasmotized devices when on the same VLAN.  WebUI access to the devices works just fine despite being on different VLANs.  I'm using  TasmoAdmin v. 0.13.1.  I really like the add-on and would love to get it working across VLANs for maximum security.   Thanks!

**Comment by PavelGorbanj** [comment]
Cross-VLAN works for me for ages (tasmoadmin communicates with devices from 3 VLANS).
Pls ensure routing/firewall is configured properly.
