### ISSUE TITLE
AM2301 Temperature not shown

### ISSUE THREAD

**Issue by drahdiwaberl** [TasmoAdmin/TasmoAdmin#405]
having a Wemos D1 Mini with latest Tasmota and 3x AM2301 on 3 GPIOs. working fine in Tasmota, and also did work in Tasmoadmin when i first installed it about a year ago. But some time over the last months Tasmoadmin stopped showing data of this device.

After updating everything to latest versions and debugging a little (the first sensor did have a loose contact) it still doesn't work. Tried the obvious like deleting and re-adding the device as well.

Issue #340 sounds similar, but the command suggested there doesn't help.

**Comment by reloxx13** [comment]
Heya,

i still need a status 0 response to check

**Comment by drahdiwaberl** [comment]
{"Status":{"Module":18,"DeviceName":"decke","FriendlyName":["decke"],"Topic":"temphum","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Exception","Uptime":"0T00:25:11","StartupUTC":"2020-10-06T08:55:27","Sleep":50,"CfgHolder":4617,"BootCount":190,"BCResetTime":"2020-10-05T17:05:26","SaveCount":263,"SaveAddress":"F7000"},"StatusFWR":{"Version":"8.5.1(tasmota)","BuildDateTime":"2020-10-02T10:09:47","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"348/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["UKLF","home"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000A8009","2805C8000100060000005AFF000000000000","00000200","00006000","00000000"]},"StatusMEM":{"ProgramSize":596,"Free":404,"Heap":24,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"temphum-4405","IPAddress":"192.168.0.118","Gateway":"192.168.0.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.254","Mac":"B4:E6:2D:37:71:35","Webserver":2,"WifiConfig":5,"WifiPower":17.0},"StatusMQT":{"MqttHost":"m21.cloudmqtt.com","MqttPort":12743,"MqttClientMask":"W1_%06X","MqttClient":"W1_377135","MqttUser":"uotnzfbf","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2020-10-06T09:20:38","Local":"2020-10-06T10:20:38","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:01","Sunset":"17:22"},"StatusSNS":{"Time":"2020-10-06T10:20:38","AM2301-00":{"Temperature":19.2,"Humidity":62.2,"DewPoint":11.8},"AM2301-02":{"Temperature":20.4,"Humidity":55.8,"DewPoint":11.3},"AM2301-04":{"Temperature":21.8,"Humidity":58.7,"DewPoint":13.3},"TempUnit":"C"},"StatusSTS":{"Time":"2020-10-06T10:20:38","Uptime":"0T00:25:11","UptimeSec":1511,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":51,"MqttCount":0,"Wifi":{"AP":1,"SSId":"UKLF","BSSId":"20:AA:4B:21:0E:26","Channel":6,"RSSI":100,"Signal":-40,"LinkCount":1,"Downtime":"0T00:00:05"}},"StatusSTK":{"Exception":29,"Reason":"Exception","EPC":["4000df64","00000000","00000000"],"EXCVADDR":"00000000","DEPC":"00000000","CallChain":["401014c0","4026382b","4010593b","402637c0","40263767","402628c4","402628ed","40260358","40258b63","401038c2","4025c6c1","40255102","4026104f","40000f3d","40260ac2","4026a213","40269ad3","40247cd8","40000f49","40000f49","40000e19","40105a41","40105a47","4010000d","402689bc","4026896d","40100b04","40102688","4010593b","40100b04","4010321f"]}}

**Comment by drahdiwaberl** [comment]
fwiw - Tasmoadmin recognizes it as a non-switch device, showing the concentric circles icon on the start page
