### ISSUE TITLE
Remove xampp from src tree

### ISSUE THREAD

**Issue by inverse** [TasmoAdmin/TasmoAdmin#406]
Is there a reason why this repo bundles xampp in the source tree?

```
malachi@pulsar portable $ du -h
16K	./root_xampp/apache/conf/extra
44K	./root_xampp/apache/conf
48K	./root_xampp/apache
76K	./root_xampp/php
132K	./root_xampp
153M	.
```

I noticed this is incurring a big hit on storage when I'm doing a backup of my setup with Home Assistant.

**Comment by inverse** [comment]
Created a PR to purge it from the addon: https://github.com/hassio-addons/addon-tasmoadmin/pull/99

**Comment by reloxx13** [comment]
thank you very much, ill test it out

**Comment by inverse** [comment]
Happy to do the same on this repo but would require changing the installation guide. Let me know if you want me to do it :+1:

**Comment by corbolais** [comment]
Thank you for your work resulting in tasmotaAdmin.

But thank you. I am somewhat surprised having >150MB of windos-only binary files in a repo not expressly intended for windos users.

I refuse to clone this repo as long it clutters my disk space. Please use a separate repo if you really must support this ui.

It is a no-go to include this much binary junk. I could'nt believe the duration of the git clone operation and aborted to investigate where this stems from. And it's another surprise this issue just came up 6 days ago.

+1 though, as it made me aware of the github repo size extension to google chrome. Very handy.

cheers

**Comment by inverse** [comment]
@reloxx13 how do you prepare the release to include XAMPP? I guess that part needs to be catered for.

**Comment by reloxx13** [comment]
Its the sourcecode and the sourcecode provides a ready to use xampp installation cause many are unable to set a webserver up.

@corbolais you down need the sourcecode. download the release files where it i excluded. updates are done by the selfupdater not due git pull.

I need it inside the repo to set the configs for the users.

![grafik](https://user-images.githubusercontent.com/14855001/96377645-386f2f80-1187-11eb-8c2d-85490cc0ef3e.png)

**Comment by corbolais** [comment]
Hello @reloxx13 

> I need it inside the repo to set the configs for the users.

What do you mean by that. Why should any blob be required to set configs for users?

If I understand correctly, you intend to do updates via release files only.

I am using the git repository for the source code to track (local) changes. I do not intend to update via release files but via git only.

Please get the git repository structure cleaned up. I.e. use one for that XAMPP stuff and another one without. Just extract the blobs into another repo.

In case anyone else stumbles across this, here's a workaround:

* how to avoid big blobs:
```
git clone --depth 1 --filter=blob:none --no-checkout https://github.com/reloxx13/TasmoAdmin.git TasmoAdmin
cd TasmoAdmin
git checkout master -- tasmoadmin/

```
@reloxx13 You might want to include this hint in the README file for the time being. Until you got the binary files issue sorted.

**Comment by inverse** [comment]
Removed from source tree
