### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by daniel-lo** [TasmoAdmin/TasmoAdmin#407]
Tried to update devices from 8.5.0 to 8.51 by selecting min/full locally .. it sais update has finished but nothing happend. Tried the files individually on one device and uptate works. What may be going wrong?

**Comment by zuhair68** [comment]
I have the same problem

**Comment by benjamin-salchow** [comment]
Could it be that the firmware is not gzipped?
By using the gzipped version it worked like a charm, but it's currently not supported by TasmoAdmin.

https://github.com/reloxx13/TasmoAdmin/issues/403

**Comment by daniel-lo** [comment]
I'd not expect the log to mention a successful update in such a case.

**Comment by eloo** [comment]
@daniel-lo 
same for me.
update is reported as successful but actually nothing is updated.

**Comment by eloo** [comment]
@daniel-lo 
i found the problem on my setup.
when you go to the update page there is a update server input field on the top. there was the internal docker ip.
i've changed this to the real ip of my homeassistant device then it worked.
(i also activated ssl but that should not matter i guess)

maybe this helps and should be added to the documentation?

**Comment by daniel-lo** [comment]
@eloo 
The update server should not be relevant if you select the local link to minmal and full.

**Comment by eloo** [comment]
@daniel-lo 
i guess that not true.. if you check the logs you see that you are uploading your desired files to tasmoadmin and then let the devices fetch this file from tasmoadmin. and when you have the from ip there the devices can't reach "your" update server.

**Comment by daniel-lo** [comment]
@eloo .. so you mean edit the line: OTA Server IP with the local IP of the machine Tasmoadmin is running on?

**Comment by eloo** [comment]
@daniel-lo yes ;)

**Comment by daniel-lo** [comment]
@eloo 
tried it .. but no change for me :-(

**Comment by eloo** [comment]
@daniel-lo can you access the tasmoadmin webinterface with the entered IP and the port?
i guess this should work.. maybe you need also to check the SSL option?

**Comment by daniel-lo** [comment]
@eloo 
yes .. I can access it. And checking SSL doesn't make a difference.

**Comment by eloo** [comment]
@daniel-lo okay.. thats odd.. sounds you have a different issue.
sorry that i couldn't help

**Comment by daniel-lo** [comment]
@eloo .. thanks for trying :-)
@reloxx13 .. do you have an idea?

**Comment by gpalsingh30** [comment]
Any update on this issue... the issue is still persisting for me.. 👎

**Comment by garymcleanuk** [comment]
Root cause...

The plain HTTP request was sent to HTTPS port. The webserver update port for tasmoadmin is configured for SSL but tasmota doesnt support SSL even with the tick box unticked in the update GUI.. Bug.

**Comment by inverse** [comment]
Is this still a problem on v2.0.0?
