### ISSUE TITLE
chmod 777

### ISSUE THREAD

**Issue by corbolais** [TasmoAdmin/TasmoAdmin#408]
Thank you for TasmoAdmin.

Why would it be required `chmod 777` not only one directory but even two directories on a webserver?

Please avoid such overly permissive settings.

Just found out about tasmotaAdmin and haven't had a look at the source. I'd PR otherwise. Maybe you want to express the reasoning behind this configuration.

cheers

**Comment by corbolais** [comment]
The README refers to https://github.com/reloxx13/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04 for a Linux install.

The guide wants to `chmod 777` not even one but two directories.

To be clear: anyone having the "need" for world read/write really needs to get educated on the Unix permissions scheme. No webserver software whatsoever should ever enforce a `chmod 777`. It's just a sign for broken software and/or incompetent developers.

cheers

**Comment by mprins** [comment]
it's a wiki; you can fix it instead of accusing people of incompetence

**Comment by corbolais** [comment]
> it's a wiki; you can fix it instead of accusing people of incompetence

Stop whining. It's a statement or a fact if you will. No "accusation" in your wording.

Maybe you want to shed some light on the issue at hand?

ACK, it's a wiki. I asked for some reasoning. No news there.

**Comment by inverse** [comment]
There shouldn't be a need for `777` access - configuration should be writable by the web user only.
