### ISSUE TITLE
Device not found - JSON ERROR 4

### ISSUE THREAD

**Issue by xamones** [TasmoAdmin/TasmoAdmin#415]
Hi!
As instructed by TasmoAdmin, this the error reported when I tried to add a Wemos D1 with tasmota 9.1.0 to it.

<br>JSON Answer =&gt; {return document.getElementById(s);}function qs(s){return document.querySelector(s);}function sp(i){eb(i).type=(eb(i).type==='text'?'password':'text');}function wl(f){window.addEventListener('load',f);}function la(p){var a='';if(la.arguments.length==1){a=p;clearTimeout(lt);}if(x!=null){x.abort();}x=new XMLHttpRequest();x.onreadystatechange=function(){if(x.readyState==4&amp;&amp;x.status==200){var s=x.responseText.replace(/{t}/g,"</p>").replace(/{s}/g,"").replace(/{c}/g,"%'&gt;<div style="text-align:center;font-weight:&quot;);eb(" l1').innerhtml="s;}};x.open('GET','.?m=1'+a,true);x.send();lt=setTimeout(la,2345);}function" lc(v,i,p){if(eb('s')){if(v="='h'||v=='d'){var" sl="eb('sl4').value;eb('s').style.background='linear-gradient(to" right,rgb('+sl+'%,'+sl+'%,'+sl+'%),hsl('+eb('sl2').value+',100%,50%))';}}la('&'+v+i+'="+p);}wl(la);function jd(){var t=0,i=document.querySelectorAll(" input,button,textarea,select');while(i.length="">=t){if(i[t]){i[t]['name']=(i[t].hasAttribute('id')&amp;&amp;(!i[t].hasAttribute('name')))?i[t]['id']:i[t]['name'];}t++;}}wl(jd);<style>div,fieldset,input,select{padding:5px;font-size:1em;}fieldset{background:#4f4f4f;}p{margin:0.5em 0;}input{width:100%;box-sizing:border-box;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;background:#dddddd;color:#000000;}input[type=checkbox],input[type=radio]{width:1em;margin-right:6px;vertical-align:-1px;}input[type=range]{width:99%;}select{width:100%;background:#dddddd;color:#000000;}textarea{resize:vertical;width:98%;height:318px;padding:5px;overflow:auto;background:#1f1f1f;color:#65c115;}body{text-align:center;font-family:verdana,sans-serif;background:#252525;}td{padding:0px;}button{border:0;border-radius:0.3rem;background:#1fa3ec;color:#faffff;line-height:2.4rem;font-size:1.2rem;width:100%;-webkit-transition-duration:0.4s;transition-duration:0.4s;cursor:pointer;}button:hover{background:#0e70a4;}.bred{background:#d43535;}.bred:hover{background:#931f1f;}.bgrn{background:#47c266;}.bgrn:hover{background:#5aaf6f;}a{color:#1fa3ec;text-decoration:none;}.p{float:left;text-align:left;}.q{float:right;text-align:right;}.r{border-radius:0.3em;padding:2px;margin:6px 2px;}</style><div style="text-align:left;display:inline-block;color:#eaeaea;min-width:340px;"><div style="text-align:center;color:#eaeaea;"><noscript>To use Tasmota, please enable JavaScript<br></noscript><h3>HR MULTI2 Module</h3><h2>Tasmota_FCDA40</h2><h4>tasmota_FCDA40-6720 (192.168.1.47)</h4></div><div id="l1" name="l1"></div></div></div><table style="width:100%"><tbody><tr><th>").replace(/{m}/g,"</th><td>").replace(/{e}/g,"</td></tr></tbody></table><table style="width:100%"><tbody><tr><td style="width:25%"><button onclick="la(&quot;&amp;o=1&quot;);">Toggle 1</button></td><td style="width:25%"><button onclick="la(&quot;&amp;o=2&quot;);">Toggle 2</button></td><td style="width:25%"><button onclick="la(&quot;&amp;o=3&quot;);">Toggle 3</button></td><td style="width:25%"><button onclick="la(&quot;&amp;o=4&quot;);">Toggle 4</button></td></tr></tbody></table><div style="text-align:right;font-size:11px;"><hr><a href="https://bit.ly/tasmota" target="_blank" style="color:#aaa;">Tasmota 9.1.0 by Theo Arends</a></div>

**Comment by inverse** [comment]
Is this still an issue for you?
