### ISSUE TITLE
Update not working, because tasmota-minimal.bin is not flashed before

### ISSUE THREAD

**Issue by osxdoc** [TasmoAdmin/TasmoAdmin#417]
Hello I want to update my Gosund-tasmota socket. If I do it my own, I update the tasmota-minimal.bin and than the tasmota-DE.bin.
If I try the manual update with TasmoAdmin and selected the minimal and the full bin from my disk, when I start the update 0.8.4->0.9.1

> [28-11-2020 16:44:39][GLOBAL] Starte Update Prozess
> [28-11-2020 16:44:39][ID-4][SCHRITT-2][GLOBAL] Starte Schritt 2
> [28-11-2020 16:44:39][ID-4][SCHRITT-2][PRÜFEN] Prüfe Verbindung | VERSUCH => 1
> [28-11-2020 16:44:39][ID-4][SCHRITT-2][PRÜFEN] Verbindung erfolgreich! | Momentane Version => 8.4.0(tasmota)
> [28-11-2020 16:44:39][ID-4][SCHRITT-2][OTAURL] Setze OTA URL für Firmware => NEW FW
> [28-11-2020 16:44:39][ID-4][SCHRITT-2][OTAURL] OTA Url => http://192.168.200.90:9541/data/firmwares/tasmota.bin
> [28-11-2020 16:44:39][ID-4][SCHRITT-1][OTAURL] OTA URL erfolgreich gesetzt für Firmware => NEW FW
> [28-11-2020 16:44:39][ID-4][SCHRITT-2][UPDATE] Starte Module update...
> [28-11-2020 16:44:39][ID-4][SCHRITT-2][UPDATE] Update gestartet
> [28-11-2020 16:44:39][ID-4][SCHRITT-2][PRÜFE UPDATE] Warte auf update | Sekunden => 60
> [28-11-2020 16:45:39][ID-4][SCHRITT-2][FERTIG] ============= Update fertig! =============

it never tries to upload the minimal.bin and the update fails, because there is not enough space available.

**Comment by CodeFinder2** [comment]
Can confirm this, I am having the same issue.

**Comment by gpalsingh30** [comment]
Any update on this... I am having the same issue.

**Comment by benjamin-salchow** [comment]
Same on my side - using the latest docker container. It doesn't matter if I use the browser upload self build images or the original images from the tasmota release page.

**Comment by GameWatchProjects** [comment]
Problem with new tasmoat releases is, you must use the minimal.bin from the version, which is installed of the device und must use the tasmota.bin.gz for update to the next version. But the webinterface renames the gz file to bin, but why?

**Comment by saschaludwig** [comment]
I can confirm that. The Update function is broken.

**Comment by user45876** [comment]
Same here for some time now, using 1.8.0 - any updates or workarounds?
It is the same as OP describes, minimal is not used, thus no update is made. Seems to be specific to the SP111 plugs in my case?

**Comment by user45876** [comment]
Thanks for your reply. I am using 1.8.0, which is supposed to be the most current version and I am also using the gzip-option. It would always only iset the update URL to the full tasmota.bin and never use the minimal. Tried Automatic and manual option.

**Comment by inverse** [comment]
It should work with the gzip option checked.

![image](https://user-images.githubusercontent.com/713525/164303385-16b803d2-7460-48a7-88fb-d87726d132e6.png)

**Comment by user45876** [comment]
Wait - just to be on the same page - the issue for me is., that it never sets the update path to the minimal. Downloading new version works just fine, this was indeed an older and different issue.
This issue should be about tasmoadmin not setting the update url to minimal first and then full tasmota second (as described in OP).

**Comment by inverse** [comment]
Okays that seems like a different issue

**Comment by inverse** [comment]
I've spent some time looking into how the upgrade process works and I think I understand it a bit better.

So when you pass an OTA URL to a Tasmota device it first tries flashing a minimal firmware at the same location as the non-minimal firmware.

For example

Passing `http://ota.tasmota.com/tasmota/tasmota.bin.gz` and it'll look and first flash `http://ota.tasmota.com/tasmota/tasmota-minimal.bin.gz` first. You won't see that in the update output since that's happening on the device and there it no real way for us to get that unless we can parse the web-server logs showing the device accessing the file?
