### ISSUE TITLE
After Update Not All Devices Found Reliably

### ISSUE THREAD

**Issue by ryancasler** [TasmoAdmin/TasmoAdmin#418]
I updated today to the latest Docker image of TasmoAdmin and I am having a little trouble finding all my Tasmota devices reliably.  I have devices that connect to a couple of different wifi access points but all devices are served by one DHCP server and all devices are on the same subnet (192.168.1.X with a subnet mask of 255.255.255.0).  Sometimes when opening TasmoAdmin, not all of the devices that connect to other wifi access points are found immediately.  Eventually I can refresh the page and force them to be found but it usually takes 4 or 5 attempts for them to be found.  I did not see this with previous version.  Has something changed in  TasmoAdmin with the latest release that would affect finding previously defined devices?  Or is there some setting in TasmoAdmin that I should change to allow them to be found more reliably?  I don't think there is anything wrong with my network since I can access the devices directly when they are not found by TasmoAdmin.  Thanks!

**Comment by inverse** [comment]
What version of TasmoAdmin was this in? Are you still seeing the issue?

**Comment by inverse** [comment]
Closing as stale
