### ISSUE TITLE
Mounting just MyConfig.json with docker-compose

### ISSUE THREAD

**Issue by milkpirate** [TasmoAdmin/TasmoAdmin#419]
Hey,

I am having an Ansible playbook to provision my RaspberryPi with all its stuff. This also includes my IoT docker compose stack (including tasmotaadmin). I had a look what gets generated in the suggested data folder and to me only the MyConfig.json file seemed important and I would prefer just deploying that while setting everything up.

So I modifies the docker-composer service definition like so:
```
  tasmota:
    container_name: tasmota
    image: raymondmm/tasmoadmin:v1.7.0
    restart: unless-stopped
    ports:
      # HOST:CONTAINER
      - 9999:80
    volumes:
    - ./volumes/tasmota/MyConfig.json:/data/tasmoadmin/MyConfig.json
```

Pre running the container the file looks like:
```
pi@raspberrypi3:[~/iot-stack/volumes/tasmota]$ cat MyConfig.json
{
    "ota_server_ssl": "0",
    "ota_server_ip": "XXX",
    "ota_server_port": "9999",
    "username": "admin",
    "password": "XXX",
    "refreshtime": "8",
    "current_git_tag": "v1.7.0",
    "update_automatic_lang": "tasmota-sensors.bin",
    "nightmode": "always",
    "login": "1",
    "scan_from_ip": "XXX",
    "scan_to_ip": "XXX",
    "homepage": "devices",
    "check_for_updates": "0",
    "minimize_resources": "1",
    "update_channel": "docker",
    "hide_copyright": "1",
    "show_search": "1"
}
```

And has the following permissions/ownership:
```
pi@raspberrypi3:[~/iot-stack/volumes/tasmota]$ ls
total 4.0K
644 -rw-r--r-- 1 pi pi 602 Dec  2 17:37 MyConfig.json
pi@raspberrypi3:[~/iot-stack/volumes/tasmota]$ ls -n
total 4.0K
644 -rw-r--r-- 1 1000 1000 602 Dec  2 17:37 MyConfig.json
```

After/while running the container the ownership changes to:
```
pi@raspberrypi3:[~/iot-stack/volumes/tasmota]$ ls
total 4.0K
644 -rw-r--r-- 1 systemd-timesync systemd-journal 602 Dec  2 17:37 MyConfig.json
pi@raspberrypi3:[~/iot-stack/volumes/tasmota]$ ls -n
total 4.0K
644 -rw-r--r-- 1 100 101 602 Dec  2 17:37 MyConfig.json
```

And the frontend repots:
![image](https://user-images.githubusercontent.com/9251021/101092305-bfeaf380-35b9-11eb-83f7-59f0b8560bbb.png)

`chmod a+rw MyConfig.json` did not help either :( 

So:
1. Why?
1. What am I doing wrong?
1. What causes the change of ownership and why is it necessary?
1. Wouldnt it suffice to make a `chmod a+rw MyConfig.json`?
1. ...and is it possible to run the container without root and as a normal user? Meaning to add something like `user: '{{ user_id.stdout }}:{{ user_group_id.stdout }}'` to the service definition.

PS: I had a look at your Dockerfile(s) you do not seem to use docker's `buildx` feature. Its pretty neat for cross building containers for different architectures. You can have a look here: https://www.docker.com/blog/multi-arch-build-what-about-gitlab-ci/ or a little more detailed here: https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408

**Comment by milkpirate** [comment]
Guys?

**Comment by milkpirate** [comment]
Bump!

**Comment by tablatronix** [comment]
I am going to guess these uids were not supposed to be this..

-rw-r--r-- 1 _apt systemd-timesync  355 Feb 24 21:10 devices.csv
drwxr-xr-x 2 _apt systemd-timesync 4096 Jan 29  2021 firmwares

**Comment by inverse** [comment]
Sounds like it's related to this: https://github.com/TasmoAdmin/TasmoAdmin/blob/master/.docker/rootfs/etc/fix-attrs.d/01-tasmoadmin which is called on container boot.

**Comment by milkpirate** [comment]
@inverse Hmh... I see. Ok, will see what will happen if I drop the permission change. Further the message from the frontend is rooting in `/var/www/tasmoadmin/includes/Config.php:325`, which is
```
                rename($tempfile, $this->cfgFile);
```
-  This call fails since the *source* is still busy:
  ```
bash-5.0# ls -la
...
1647942142.6739623999fea486d  1647943452.847862399f1ccefc3  1647944861.02446239a49d05f71
1647942142.6746623999fea4b09  1647943452.850962399f1ccfbf0  1647944861.03076239a49d077e1
1647942142.6752623999fea4d78  1647943452.854662399f1cd0a53  1647944861.03546239a49d08a4c
1647942142.6758623999fea5003  1647943452.858862399f1cd1a82  MyConfig.json
1647942142.6765623999fea526b  1647943452.981962399f1cefb61  devices.csv
1647942142.6771623999fea54d3  1647943452.985462399f1cf0958  firmwares
1647942142.6777623999fea5735  1647943453.00762399f1d01b55   updates
1647942142.6783623999fea599f  1647943453.096162399f1d17797
bash-5.0# mv 1647942142.6739623999fea486d MyConfig.json    # pretty much the call generated by line 325
mv: can't rename '1647942142.6739623999fea486d': Resource busy
bash-5.0#
  ```
  Maybe some process is still using it?
- By replacing `rename` with `copy` did the trick for me, but I am well aquainted with TasmoAdmin to know if thats a feasable sollution.

**Comment by inverse** [comment]
Perhaps this PR might fix it? Would you be able to test?

https://github.com/TasmoAdmin/TasmoAdmin/pull/475

**Comment by milkpirate** [comment]
@inverse sorry to say but https://github.com/TasmoAdmin/TasmoAdmin/pull/475 fixes neither the permission issues nor the php `rename` one, or at least not for me :(

**Comment by inverse** [comment]
Yeah there is def something funky going on with the container init with regards to this data dir. I noticed it when adding the docker-compose stack.

**Comment by tablatronix** [comment]
Fixed for me, I removed the container and pulled

**Comment by inverse** [comment]
@milkpirate I suspect it's because of the fact it's being mounted to the container (but my docker knowledge isn't that great)

Feels like something that could certainly be refactored. e.g the current flow is

-load config
- update key
- write to tmp file
- rename

**Comment by inverse** [comment]
@milkpirate #482 should fix your issue

**Comment by milkpirate** [comment]
@inverse the `rename` or `mv` is a common pattern. It is usaully used to make the config change atomic and/or to trigger inotifications (when prcesses are listening on file changes). 

Background: Renames/moves in the Linux Kernel are realized as just inode changes which are atomic. So the following can not happen: If you open and manipulate the file in place and that another program reads in the meantime, it can result in reading partial or corrupted settings. Classical race condition. BTW: there are much better options to do IPC.

Anyway, I'm just speculating, and you would have to ask the original author why (s)he choose this option. :man_shrugging:

**Comment by inverse** [comment]
Thank for the context, not had such issues in the past with PHP applications but it makes total sense.

Yeah it looks like the change was made to fix some race conditions with multiple writes.

**Comment by inverse** [comment]
@milkpirate Is this a limitation of mounting a file and being unable to rename a file to it?

## Dockerfile
```
FROM alpine

WORKDIR /app

COPY other /app

ENTRYPOINT ["tail", "-f", "/dev/null"]
```


## docker-compose.yml
```
version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./other/mine.txt:/app/mine.txt
```

## ls
```
malachi@puslar tmp $ tree
.
├── docker-compose.yml
├── Dockerfile
├── mount
│   └── mine.txt
└── other
    └── mine.txt
```

## run

```
docker exec -it tmp-web-1 sh -c 'touch tmp.txt && mv tmp.txt mine.txt'
```

**Comment by milkpirate** [comment]
First, I guess you could do a `docker run -it -v $PWD/other/mine.txt:/app/mine.txt alpine /bin/sh`. Then you have an interactive shell to tinker. From the mount point of view that should be equivalent to what docker-compose does (docker-compose is just like a frontend for docker... any other compatible container engine).

```sh
/app # mount | grep txt
/dev/sda2 on /app/mine.txt type ext4 (rw,relatime,errors=remount-ro)
/app # ls -la
total 12
drwxr-xr-x    1 root     root          4096 Mar 30 17:49 .
drwxr-xr-x    1 root     root          4096 Mar 30 17:48 ..
-rw-rw-r--    1 1000     1000            11 Mar 30 17:45 mine.txt
-rw-r--r--    1 root     root             0 Mar 30 17:49 tmp.txt
/app # mv tmp.txt mine.txt
mv: can't rename 'tmp.txt': Resource busy
/app # lsof mine.txt
/app # cat tmp.txt > mine.txt
/app #
```
Googled a little but didnt find something conclusive. I am pretty sure the `mv` syscall is not working well with the file being mounted. I am pretty sure you cant do `mv foo.txt /dev/sda[1]` either. I would also moutn the whole directory where `MyConfig.json` resides in, bu theres so much junk around it :/

**Comment by inverse** [comment]
Yup - which means you could it in a oneliner `touch mine.txt && docker run -it -v $PWD/mine.txt:/app/mine.txt alpine sh -c 'cd /app && touch tmp.txt && mv tmp.txt mine.txt'`

> . I would also moutn the whole directory where MyConfig.json resides in, bu theres so much junk around it :/

You mean junk from TasmoAdmin or on your own volume?

**Comment by milkpirate** [comment]
@inverse all those files:

```
...
1647943135.615262399ddf96354  1647944860.78916239a49cc0a40  1647950652.81226239bb3cc648d  1647952480.80166239c260c3b55  1647975077.42623a1aa566881
1647943135.618962399ddf971c1  1647944860.79446239a49cc1f0f  1647950652.8166239bb3cc7354   1647952480.8066239c260c4c73   MyConfig.json
1647943135.761562399ddfb9e9e  1647944861.01416239a49d036f9  1647950653.02826239bb3d06e28  1647952480.93046239c260e3258  devices.csv
1647943135.783462399ddfbf43e  1647944861.02446239a49d05f71  1647950653.04066239bb3d09e7d  1647952480.95816239c260e9e99  firmwares
1647943135.861962399ddfd26fc  1647944861.03076239a49d077e1  1647950653.05426239bb3d0d3a2  1647952480.96636239c260ebebb  updates
1647943135.930662399ddfe3338  1647944861.03546239a49d08a4c  1647950653.06096239bb3d0eddc  1647952480.98556239c260f09bf
1647943135.947462399ddfe74da  1647944920.78226239a4d8bef7e  1647950660.73786239bb44b4205  1647952540.78616239c29cbfedd
1647943143.525762399de780566  1647944920.78576239a4d8bfd46  1647950660.74166239bb44b50cf  1647952540.78986239c29cc0d44
/data/tasmoadmin $
```
But I guess with your fix it might boil down to this:
```
-rw-r--r--    1 nginx    nginx          570 Mar 22 20:22 MyConfig.json
-rw-r--r--    1 nginx    nginx          521 Mar 22 10:12 devices.csv
drwxr-xr-x    2 nginx    nginx         4096 Mar 21 17:09 firmwares
drwxr-xr-x    2 nginx    nginx         4096 Mar 21 17:09 updates
```
Which would be resonable. BTW did you find a way to publish (current / latest) iamges to docker hub again?

**Comment by inverse** [comment]
Yeah those files are from all the tmp file generation before the rename :/ I noticed it too trying to reproduce your issue.

The problem with my fix is as you describe earlier. Was planning on tidying things up and adopting this Symfony component to make things a little simpler https://symfony.com/doc/current/components/filesystem.html#dumpfile

**Comment by milkpirate** [comment]
Well I am pretty sure if we mount the whole directory and not just the file (which is as I believe something like `mount -o bind old_file new_file`) the rename method should work.

**Comment by inverse** [comment]
And you explained it well and why it's common practice to use tmp + mv to make such changes too 😄 

👋🏼 greetings also from Berlin
