### ISSUE TITLE
Issue with .htaccess file and Apache 2.x

### ISSUE THREAD

**Issue by clmcavaney** [TasmoAdmin/TasmoAdmin#426]
This file https://github.com/reloxx13/TasmoAdmin/blob/4b025471711d2e774c860511d5404e59546a18a6/tasmoadmin/data/firmwares/.htaccess#L1 has the instruction "`Satisfy Any`" which doesn't work with modern versions of Apache 2.x

It should be something like:
`Require all granted`

**Comment by inverse** [comment]
Happy to accept PRs to fix this

**Comment by clmcavaney** [comment]
Fair point - will get that organised.
