### ISSUE TITLE
Wifi signal status (RSSI) seems to be incorrect

### ISSUE THREAD

**Issue by joka222** [TasmoAdmin/TasmoAdmin#429]
I'm on tasmota 9.2.

If I compare the RSSI value of a device in tasmoadmin with the possible wifi options in the device webui itself, tasmoadmin shows a wrong RSSI % value.

example:

it shows 20% here
![image](https://user-images.githubusercontent.com/45273450/107115543-9f674000-686d-11eb-89f5-715955648bef.png)

in comparison to the options in the device webui at the same time, the first value is the right value 50% but 20% is shown as RSSI in tasmoadmin which is the last value in list.
![image](https://user-images.githubusercontent.com/45273450/107115569-d4739280-686d-11eb-9080-a87e60db348f.png)

Tasmoadmin seems to choose a value out of the list randomly.

**Comment by inverse** [comment]
We take the RSSI exposed from the device from the API. 

e.g. `http://<ip>/cm?user=<user>&password=<password>&cmnd=status+0`

from the `StatusSTS.Wifi.RSSI` element from looking at the code.

**Comment by inverse** [comment]
Closing as stale
