### ISSUE TITLE
ISSUE WITH SONOFF 4CH TASMOTA 9.3.1 AND PREVIOUS AFTER 8.3

### ISSUE THREAD

**Issue by mircozappon** [TasmoAdmin/TasmoAdmin#433]
I found an issue related to sonoff 4ch (4 devices with the same problem) only when setoption80 is active (for blinds and rollers manteinance).
The issue appear only when 2 shutterrelay are defined shutterrelay1=1 shutterrelay2=3, if setoption80 = 0 no errors in tasmoadmin. I use 7 sonoff 4ch for my covers with shuttermode 1, Interlock 1,2, interlock on, 3 are right because i define only shutterarray1 the 4 having shutterrelay2=3 have the issue.

I want to clarify that in homeassistanst and mqtt all is perfect and right, no issues. I can connect to device from TasmoAdmin, but it always show offline status with red icon.

Some ideas? 

Device screenshot:
![image](https://user-images.githubusercontent.com/28898156/111834895-88981c80-88f4-11eb-9635-2732557354ff.png)

Error screenshots sonoff 4ch sith with shutterrelay1=1 and with shutterrelay2=3:
![image](https://user-images.githubusercontent.com/28898156/111835033-b7ae8e00-88f4-11eb-964b-30568ff81196.png)
![image](https://user-images.githubusercontent.com/28898156/111835179-ec224a00-88f4-11eb-84b1-bdc5a5376f5f.png)

Scrrenshot sonoff 4ch with shutterrelay1=1
![image](https://user-images.githubusercontent.com/28898156/111835375-2f7cb880-88f5-11eb-95b8-aaec4882edd4.png)

This is the error in TasmoAdmin:

Could not reach device. Please try again. This happens if the device is restarting or there were too many requests.
JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":7,"DeviceName":"dbs","FriendlyName":["dbs_door_shutter_up","dbs_door_shutter_down","dbs_window_shutter_up","dbs_window_shutter_down"],"Topic":"dbs","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":300,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1,"InfoRetain":0,"StateRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T06:56:20","StartupUTC":"2021-03-19T12:31:21","Sleep":50,"CfgHolder":4617,"BootCount":13,"BCResetTime":"2021-03-03T16:53:38","SaveCount":8228,"SaveAddress":"FB000"},"StatusFWR":{"Version":"9.3.1(tasmota)","BuildDateTime":"2021-02-26T13:42:23","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"453/699"},"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["CHAOS",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0000C029","2805C8000100060000005A0A000000000000","40000080","00006000","00000000"]},"StatusMEM":{"ProgramSize":605,"Free":396,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"dbs-2876","IPAddress":"192.168.100.200","Gateway":"192.168.100.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.100.1","Mac":"DC:4F:22:C7:0B:3C","Webserver":2,"WifiConfig":2,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.100.150","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C70B3C","MqttUser":"root","MqttCount":18,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2021-03-19T19:27:41","Local":"2021-03-19T20:27:41","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"06:54","Sunset":"19:00"},"StatusSNS":{"Time":"2021-03-19T20:27:41","Shutter1":{"Position":0,"Direction":0,"Target":0},"Shutter2":{"Position":0,"Direction":0,"Target":0}},"StatusSTS":{"Time":"2021-03-19T20:27:41","Uptime":"0T06:56:20","UptimeSec":24980,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":18,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"CHAOS","BSSId":"8C:DE:F9:21:D4:4A","Channel":1,"RSSI":90,"Signal":-55,"LinkCount":1,"Downtime":"0T00:00:03"}},"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":324,"Close":314,"50perc":68,"Delay":0,"Opt":"0000","Calib":[2340,414,5094,900,1000],"Mode":"0"}},{"SHT1":{"Relay1":3,"Relay2":4,"Open":222,"Close":220,"50perc":66,"Delay":0,"Opt":"0000","Calib":[1430,301,3161,900,1000],"Mode":"0"}}}}

**Comment by reloxx13** [comment]
heya,
ur json is broken, either by a defect fw or a bug in the fw.
![grafik](https://user-images.githubusercontent.com/14855001/111846688-9f943a00-8907-11eb-89e8-686bd5d23fc4.png)

i would try reflashing and reset and/or opening an issue in tasmota repo if the problem stays. mqtt does not use json thats why it works fine in HA,

if all of ur devices have the same invalid json, it will be a fw bug.

**Comment by mircozappon** [comment]
Thansk reloxx13 for the answer, I'll try to compile and build the firmware again and I'll hope to solve the problem. Otherwise I'll open a ticket in tasmota fw, because it's involve all devices with more than one blind defined as you show me above.

**Comment by inverse** [comment]
@mircozappon is this still an issue?
