### ISSUE TITLE
Error dispositivo no encontrado

### ISSUE THREAD

**Issue by pajenny** [TasmoAdmin/TasmoAdmin#444]
Dispositivo no encontrado

ERROR de JSON => 4: Syntax error
Por favor, copie el mensaje completo del error y péguelo en un nuevo issue en GitHub de TasmoAdmin.
Respuesta JSON => {"Status":{"Module":23,"DeviceName":"rele_calefaccion_sotano_51","FriendlyName":["rele_comedor_01_wf51_04_bajos_calefaccion_sotano","rele_habitaciones_02_wf51_04_bajos_calefaccion_sotano","rele_habitaciones_03_wf51_04_piso_calefaccion_sotano","rele_bhuardilla_04_wf51_04_piso_cale],"Topic":"4chpror3.01_sotano","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:00:56","StartupUTC":"2021-08-25T10:40:43","Sleep":50,"CfgHolder":4617,"BootCount":46,"BCResetTime":"2021-05-14T06:16:41","SaveCount":115,"SaveAddress":"FB000"},"StatusFWR":{"Version":"9.5.0(minimal)","BuildDateTime":"2021-06-17T08:26:39","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"571/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Co******tp",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000A8009","2805C8000C00060000005A0A000000000000","00000280","00006000","00000000"]},"StatusMEM":{"ProgramSize":389,"Free":612,"Heap":31,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","00000580","04000003","00000002","00000000","00000000","00000000","00000000","00000000"],"Drivers":"1,2","Sensors":""},"StatusNET":{"Hostname":"4chpror3.01_sotano-3349","IPAddress":"172.26.55.51","Gateway":"172.26.55.1","Subnetmask":"255.255.255.0","DNSServer":"8.8.8.8","Mac":"24:A1:60:19:ED:15","Webserver":2,"WifiConfig":0,"WifiPower":17.0},"StatusMQT":{"MqttHost":"172.26.55.40","MqttPort":1883,"MqttClientMask":"rele_calefaccion_sotano_51","MqttClient":"rele_calefaccion_sotano_51","MqttUser":"jmqt","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4},"StatusTIM":{"UTC":"2021-08-25T10:41:39","Local":"2021-08-25T11:41:39","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00"},"StatusSNS":{"Time":"2021-08-25T11:41:39"},"StatusSTS":{"Time":"2021-08-25T11:41:39","Uptime":"0T00:00:56","UptimeSec":56,"Vcc":3.466,"Heap":30,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"ON","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"Colegas_tp","BSSId":"D2:32:E5:D3:89:EC","Channel":1,"Mode":"11n","RSSI":90,"Signal":-55,"LinkCount":1,"Downtime":"0T00:00:03"}}}}

×

**Comment by ascillato** [comment]
Please, explain a little what is your issue?

Por favor, explicamos cual es el problema?

**Comment by inverse** [comment]
Closing as stale
