### ISSUE TITLE
Update für gepackte Dateien

### ISSUE THREAD

**Issue by mafrei2019** [TasmoAdmin/TasmoAdmin#446]
Seit Tasmota 10.x muss zum Upload die gepackte Version (gz) verwenden werden. TasmaAdmin kann aber aktuell nur bin Dateien verarbeiten. Kann mann da auf eine Änderung hoffen ?

**Comment by joka222** [comment]
Hard links can be used as a workaround until an update is available.

**Comment by XtraLarge** [comment]
How to do this?

**Comment by ngalfas** [comment]
Solution

https://github.com/reloxx13/TasmoAdmin/pull/447

**Comment by joka222** [comment]
> How to do this?

for Windows user:

https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/mklink

mklink /h <link> <target>

mklink /h tasmota-DE_10-0.bin tasmota-DE_10-0.bin.gz
mklink /h tasmota-minimal_10-0.bin tasmota-minimal_10-0.bin.gz

**Comment by inverse** [comment]
Closing as resolved
