### ISSUE TITLE
Migrate from Travis to GitHub Actions

### ISSUE THREAD

**Issue by inverse** [TasmoAdmin/TasmoAdmin#450]
See: https://github.com/reloxx13/TasmoAdmin/pull/447#issuecomment-980612527

@reloxx13 what's the current workflow with releasing with Travis?

Typically I've seen GitHub Action style things have CI running against each branch to check if things work and then when a GitHub release is created run the whole release pipeline. 

I'm guessing it's going to be simplified on GitHub Actions

-  CI running the scripts to build + test on each PR
- Release running on GitHub Release pushing the docker artifacts

**Comment by reloxx13** [comment]
Hey @inverse,
I am very grateful for your efforts!

Thr travis ci was made to create and publish the docker images and the xampp ready to use package which gto added to the release.

It was triggered everytime on tag creation. tags which end of -beta were also release as beta versions on dockerhub.

**Comment by inverse** [comment]
Almost there we just need to fix the Dockerhub side

**Comment by inverse** [comment]
Migrated to GitHub Pages
