### ISSUE TITLE
jquery security concerns

### ISSUE THREAD

**Issue by grassroot** [TasmoAdmin/TasmoAdmin#455]
Hello,
TasmoAdmin seems to be using an aged version 1.12 of the JQuery and JQuery-UI libraries which according to [snyk.io](https://snyk.io/test/npm/jquery/1.12.1) and [CVE](https://www.cvedetails.com/vulnerability-list/vendor_id-6538/product_id-11031/opxss-1/Jquery-Jquery.html) contain multiple vulnerabilities.
Any changes on upgrading them to more secure version, hopefully up to [currently latest 3.6.0](https://jquery.com/download/).

**Comment by inverse** [comment]
Thanks! 

Using npm to manage front-end dependencies would help with creating viability with this.

**Comment by inverse** [comment]
jquery issue not fixed - still need to bump that

**Comment by inverse** [comment]
Fixed on master - will be in the next release :+1:
