### ISSUE TITLE
Please Update Docker Hub to v 1.8

### ISSUE THREAD

**Issue by mpuff** [TasmoAdmin/TasmoAdmin#473]
Hello, 

please also update the docker hub.

thank you

**Comment by inverse** [comment]
We're currently blocked: https://github.com/reloxx13/TasmoAdmin/issues/465#issuecomment-1055804161

**Comment by inverse** [comment]
Hi @jenniferlee1818 we're blocked as the person who owns the Docker hub account needs to set the credentials for GitHub Actions for us to push the images. 

Otherwise we will need to migrate to a new account.

**Comment by pbanj** [comment]
probably best to just make a new account at this point

**Comment by inverse** [comment]
We could do but I think it would be best to set things up a bit differently this time to improve the longevity of this project. 

- Migrate this repo to an organisation. e.g. TasmoAdmin
- Push the images to Github's own CR (Container Registry)

This way to enables a more fluid setup and allows the project to continue easily without being dependant on one individual. 


@reloxx13 what do you think?

**Comment by pbanj** [comment]
That does sound like a better idea

**Comment by inverse** [comment]
We migrated from Docker Hub to GitHub packages to provide a better way to manage things.

The images are available at: https://github.com/orgs/TasmoAdmin/packages/container/package/tasmoadmin
