### ISSUE TITLE
Guide for Ubuntu Server 16.04 install on Rasbian

### ISSUE THREAD

**Issue by edegraaff** [TasmoAdmin/TasmoAdmin#514]
I get an error during booting tasmoadmin, and it seems files are missing in the latest build

Warning: require_once(/var/www/tasmoadmin/tasmoadmin/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/tasmoadmin/tasmoadmin/includes/bootstrap.php on line 103

Fatal error: require_once(): Failed opening required '/var/www/tasmoadmin/tasmoadmin/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/tasmoadmin/tasmoadmin/includes/bootstrap.php on line 103

## Expected Behavior
I expected the starting page should start 
## Current Behavior

I get the error mentioned above

## Possible Solution
Seems the vendor autoload.php is gone, i can't find it in the 
https://github.com/reloxx13/TasmoAdmin.git

## Steps to Reproduce
1. install acording the guide
2. start the page at in my case http://192.168.1.40:9999/
3. error shown
4.

## Context (Environment)
PHP Version 7.4.28
System	Linux tasmoadmin 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l
Build Date	Feb 17 2022 16:17:19
Server API	Apache 2.0 Handler
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/etc/php/7.4/apache2
Loaded Configuration File	/etc/php/7.4/apache2/php.ini
Scan this dir for additional .ini files	/etc/php/7.4/apache2/conf.d
Additional .ini files parsed	/etc/php/7.4/apache2/conf.d/10-opcache.ini, /etc/php/7.4/apache2/conf.d/10-pdo.ini, /etc/php/7.4/apache2/conf.d/20-calendar.ini, /etc/php/7.4/apache2/conf.d/20-ctype.ini, /etc/php/7.4/apache2/conf.d/20-curl.ini, /etc/php/7.4/apache2/conf.d/20-exif.ini, /etc/php/7.4/apache2/conf.d/20-ffi.ini, /etc/php/7.4/apache2/conf.d/20-fileinfo.ini, /etc/php/7.4/apache2/conf.d/20-ftp.ini, /etc/php/7.4/apache2/conf.d/20-gettext.ini, /etc/php/7.4/apache2/conf.d/20-iconv.ini, /etc/php/7.4/apache2/conf.d/20-json.ini, /etc/php/7.4/apache2/conf.d/20-mbstring.ini, /etc/php/7.4/apache2/conf.d/20-phar.ini, /etc/php/7.4/apache2/conf.d/20-posix.ini, /etc/php/7.4/apache2/conf.d/20-readline.ini, /etc/php/7.4/apache2/conf.d/20-shmop.ini, /etc/php/7.4/apache2/conf.d/20-sockets.ini, /etc/php/7.4/apache2/conf.d/20-sysvmsg.ini, /etc/php/7.4/apache2/conf.d/20-sysvsem.ini, /etc/php/7.4/apache2/conf.d/20-sysvshm.ini, /etc/php/7.4/apache2/conf.d/20-tokenizer.ini, /etc/php/7.4/apache2/conf.d/20-zip.ini
PHP API	20190902
PHP Extension	20190902
Zend Extension	320190902
Zend Extension Build	API320190902,NTS
PHP Extension Build	API20190902,NTS
Debug Build	no
Thread Safety	disabled
Zend Signal Handling	enabled
Zend Memory Manager	enabled
Zend Multibyte Support	provided by mbstring
IPv6 Support	enabled
DTrace Support	available, disabled
Registered PHP Streams	https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters	zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, convert.iconv.*

## Detailed Description
Seems files are missing

## Possible Implementation
When there is  a new build i will retry

**Comment by inverse** [comment]
hanks for reporting this The guide is actually referencing installing from the master branch which was migrated to use composer for the PHP dependencies. 

I've updated it to cover installing these dependencies - https://github.com/TasmoAdmin/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04#setup-composer

you may need to install the `unzip` package. e.g. `sudo apt-get install unzip`.

Ideally we should rewrite this to install from the release packages https://github.com/TasmoAdmin/TasmoAdmin/releases/

The latest non-beta one should suffice.

**Comment by edegraaff** [comment]
I got it working within Debian (Raspbian) but it demands some actions to get the whole working: 
Clean install raspbian
> sudo apt-get install apache2 php libapache2-mod-php php7.0-curl php7.0-zip php7.0-mbstring git vim
replaced by apt-get install apache2 php php7.4-curl php7.4-zip php7.4-mbstring git joe_

>>  sudo rm /etc/php/7.4/apache2/conf.d/opcache.ini   >> does not exist

new: sudo apt-get install php-xml 
new: apt-get install composer
and from there i used the guide

**Comment by edegraaff** [comment]
Autodiscover works ! great
And update also 
![image](https://user-images.githubusercontent.com/12442749/165165541-64ae9147-0f07-4cf7-8f86-bab80b0712f0.png)

**Comment by edegraaff** [comment]
The selfupdate fails at my site 

Fatal error: Uncaught Error: Class 'TasmoAdmin\ZipArchive' not found in /var/www/tasmoadmin/tasmoadmin/src/SelfUpdate.php:175 Stack trace: #0 /var/www/tasmoadmin/tasmoadmin/src/SelfUpdate.php(31): TasmoAdmin\SelfUpdate->install() #1 /var/www/tasmoadmin/tasmoadmin/pages/selfupdate.php(13): TasmoAdmin\SelfUpdate->update() #2 /var/www/tasmoadmin/tasmoadmin/index.php(55): include_once('/var/www/tasmoa...') #3 {main} thrown in /var/www/tasmoadmin/tasmoadmin/src/SelfUpdate.php on line 175

**Comment by inverse** [comment]
Just merged a change that should fix that - could you run `git pull` from where you cloned the repo too?

**Comment by edegraaff** [comment]
> Just merged a change that should fix that - could you run `git pull` from where you cloned the repo too?

ok one sec

**Comment by edegraaff** [comment]
Next usecase:
scan all devices : 
list is all devices are updated exept one 
do update all devices 
select all 
run update 
seems all updates are runned but the first one that was already updated caused the update proces to fail.
end result: 
all devices are updated > ready 
list view > none are updated 

action:
select individual devices 3 > do update
result all are updated  > great !

**Comment by inverse** [comment]
So because one is already updated to latest the remaining are not updated when updating multiple?

**Comment by edegraaff** [comment]
> So because one is already updated to latest the remaining are not updated when updating multiple?

Seems that way, i am checking the reason, it could also be one device that is reluctand to update and is causing the full update of all devices. I updated the nr 1 as test > pass, then updated all > fail, then updated 2 and 3 > pass then updated 4, 5, 6 >fail

**Comment by edegraaff** [comment]
Seems most of the issues have been solved: 
Auto update, the last ones have been updated, did take a while but it worked 
Selfupdate worked up to 1.8.0
Pulling your latest work did fix the problem i reported so 
all systems ready and go 
thanks!

regards
Eelco

**Comment by inverse** [comment]
Still need to fix that issue you previously reported about not all devices updating - Slowly refactoring the code and adding tests as I go!

**Comment by edegraaff** [comment]
> Still need to fix that issue you previously reported about not all devices updating - Slowly refactoring the code and adding tests as I go!

ok, what we could do is putting the devices or som of them in one revision back, and re-update all of them. Feel free to reach out to me for testing.

**Comment by edegraaff** [comment]
All devices are now updated, what seems an issue is sometimes the update procedure fails, and then after some retry's all are updated. Is there somewhere a log that is written? during the update proces? Suggestion to log the progress somewhere and use a logrotate to remove or update older log files.
all my devices are now tasmota 11.1

**Comment by inverse** [comment]
Gonna close this issue as I think the original case is solved. 

Did lots of rework the device update layer and it should be a lot more flexible and stable.
