### ISSUE TITLE
Check if OTA URL is accessible before updating devices

### ISSUE THREAD

**Issue by hobojoe** [TasmoAdmin/TasmoAdmin#524]
## Expected Behavior
Device updated to desired firmware.

## Current Behavior
The update process completes successfully, but the device remains on the old firmware version:

## Steps to Reproduce

1. I have added the min and regular firmware file to update (7.2)
![image](https://user-images.githubusercontent.com/1886514/165749453-2165ecd2-4cdd-41e6-b584-457dd449dd9b.png)

2. Click the Next button
3. Process completes, but device remain on the old firmware.

## Context (Environment)
TasmoAdmin v1.8.0
Running as a Home Assistant Addon (RBPI 4)
The Tasmota device is in a network without internet access, but with access to Home Assistant IP (192.168.1.100).

## Detailed Description
[28-04-2022 09:05:38][GLOBAL] Start update process
[28-04-2022 09:05:38][ID-5][STEP-2][GLOBAL] Start Step 2
[28-04-2022 09:05:38][ID-5][STEP-2][CHECK] Check Connection | TRY => 1
[28-04-2022 09:05:38][ID-5][STEP-2][CHECK] Connection Successfully! | Current Version => 6.7.1(sonoff)
[28-04-2022 09:05:38][ID-5][STEP-2][OTAURL] Set OTA URL for Firmware => NEW FW
[28-04-2022 09:05:38][ID-5][STEP-2][OTAURL] OTA Url => http://192.168.1.100:9541/data/firmwares/tasmota.bin
[28-04-2022 09:05:38][ID-5][STEP-1][OTAURL] OTA URL set for Firmware => NEW FW
[28-04-2022 09:05:38][ID-5][STEP-2][UPDATE] Trigger device update...
[28-04-2022 09:05:38][ID-5][STEP-2][UPDATE] Device update triggered
[28-04-2022 09:05:38][ID-5][STEP-2][CHECK UPDATE] Wait for update | Seconds => 60
[28-04-2022 09:06:38][ID-5][STEP-2][DONE] ============= Update done! =============

**Comment by inverse** [comment]
Are you able to access the firmware hosted on http://192.168.1.100:9541/data/firmwares/tasmota.bin ?

**Comment by hobojoe** [comment]
> Are you able to access the firmware hosted on http://192.168.1.100:9541/data/firmwares/tasmota.bin ?

Just tried it ... it works fine.

**Comment by hobojoe** [comment]
Rechecked here... the Network my tasmota device was on didn't have access to that 9541 port :(

Sorry. After I fixed that, it worked!

Not sure if there is a way for the addon to show a warning when the update wasn't completed.

Thanks!

**Comment by inverse** [comment]
@hobojoe we def need to improve that update logic code to check these things. Somethings that come to mind are

- Checking the firmware file is accessible on the OTA link sent
- Checking Tasmo version post install to see if it matches and warning if not

**Comment by hapklaar** [comment]
Yes please. Also took me some time to find out the firmware url wasn't reachable from my tasmota devices, as I was lead to believe by the TasmoAdmin logs saying the update was done when it wasn't.

**Comment by tkupka** [comment]
http://ota.tasmota.com:80/data/firmwares/tasmota.bin --> wrong url used by TasmoAdmin (lead to 302)
http://ota.tasmota.com:80/tasmota/release/tasmota.bin --> correct URL where the bin file can be downloaded

**Comment by reloxx13** [comment]
> Yes please. Also took me some time to find out the firmware url wasn't reachable from my tasmota devices, as I was lead to believe by the TasmoAdmin logs saying the update was done when it wasn't.

tasmota does not response with an update status, we can just tell tasmota the update file and tell the device to update now. but yes, checking the file url is a good idea.

**Comment by inverse** [comment]
The backend validate that is can access the file - still additional work to do elsewhere though

**Comment by inverse** [comment]
The beta builds have this change in now.

- check accessible from backend
- check from js frontend
- version check during install
