### ISSUE TITLE
Error while trying to add device.

### ISSUE THREAD

**Issue by mkrawcz1** [TasmoAdmin/TasmoAdmin#525]
## Expected Behavior

Device added.

## Current Behavior

Device not added.
If autoscanned - device not found.
If added manualy - error as bellow:
Device not found

JSON ERROR => 4: Syntax error
JSON Answer => {"Status":{"Module":0,"DeviceName":"Wlacznik podlewanie","FriendlyName":["Włącznik podlewanie 1","Włącznik podlewanie 2","Włącznik podlewanie 3","Włącznik podlewanie 4","Włącznik podlewanie 5","Włącznik podlewanie 6","Włącznik podlewanie 7","Włącznik podle],"Topic":"tasmota_63C2D6","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/tasmota-minimal.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:00:25","StartupUTC":"2022-04-30T19:26:49","Sleep":50,"CfgHolder":4617,"BootCount":12,"BCResetTime":"2022-04-27T18:24:55","SaveCount":41,"SaveAddress":"F8000"},"StatusFWR":{"Version":"11.1.0.1(tasmota)","BuildDateTime":"2022-04-30T17:04:40","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"569/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["XXXXXX",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A190000000000","00000080","00006000","00004000"]},"StatusMEM":{"ProgramSize":627,"Free":376,"Heap":25,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164068","FlashFrequency":40,"FlashMode":3,"Features":["00000415","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","04000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"tasmota-63C2D6-0726","IPAddress":"192.168.0.171","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer1":"8.8.8.8","DNSServer2":"8.8.4.4","Mac":"C8:C9:A3:63:C2:D6","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.0.30","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_63C2D6","MqttUser":"user","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4},"StatusTIM":{"UTC":"2022-04-30T19:27:14","Local":"2022-04-30T20:27:14","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"05:31","Sunset":"20:03"},"StatusSNS":{"Time":"2022-04-30T20:27:14"},"StatusSTS":{"Time":"2022-04-30T20:27:14","Uptime":"0T00:00:25","UptimeSec":25,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","POWER8":"OFF","Wifi":{"AP":1,"SSId":"kramar","BSSId":"6C:3B:6B:EE:37:DD","Channel":6,"Mode":"11n","RSSI":100,"Signal":-50,"LinkCount":1,"Downtime":"0T00:00:05"}}}}

## Possible Solution

Is:
"DeviceName":"Wlacznik podlewanie","FriendlyName":["Włącznik podlewanie 1","Włącznik podlewanie 2","Włącznik podlewanie 3","Włącznik podlewanie 4","Włącznik podlewanie 5","Włącznik podlewanie 6","Włącznik podlewanie 7","Włącznik podle],

Should be:
"DeviceName":"Wlacznik podlewanie","FriendlyName":["Włącznik podlewanie 1","Włącznik podlewanie 2","Włącznik podlewanie 3","Włącznik podlewanie 4","Włącznik podlewanie 5","Włącznik podlewanie 6","Włącznik podlewanie 7","Włącznik podlewanie 8"],

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

v1.8.0 on Home Assistant 2022.4.7/Home Assistant OS 7.6

**Comment by inverse** [comment]
Hi @mkrawcz1 - I'm new to taking over this project so not to familiar with the inner workings of the Tasmo side of things.

Looks like there is something wrong with the JSON response from the device which seems odd. I can see there is some additional logic to correct this in some older versions of Tasmo but I can see you are running `11.1.0.1`. which I have some devices on `11.1.0` with no issues.

**Comment by reloxx13** [comment]
Tasmota sometime has issue with saving config and generating a valid json response.
u can try to re-set the friendly names as friendlyname 8 is not saved correctly

![grafik](https://user-images.githubusercontent.com/14855001/174406522-8799b167-77c8-4a51-bc5a-151a276605e7.png)


i use this parser to validate the jsons:    
http://json.parser.online.fr/

**Comment by inverse** [comment]
@reloxx13 should we handle this case though? e.g. try and correct it? 

Or should we just document what you just described? .e.g provide better context for the end user?
