### ISSUE TITLE
Invalid Docker-Repository-URL: https://ghcr.io/tasmoadmin/tasmoadmin:latest

### ISSUE THREAD

**Issue by joka222** [TasmoAdmin/TasmoAdmin#543]
Install TasmoAdmin on a Synology NAS running Docker
Login to DSM
Go To Docker -> Image
Click Add -> Add from Url
Copy / Paste this url : https://ghcr.io/tasmoadmin/tasmoadmin:latest
Leave all other fields blank
Click Add
Choose Tag: latest and Click Select

ends in an error:
Invalid Docker-Repository-URL: https://ghcr.io/tasmoadmin/tasmoadmin:latest

**Comment by inverse** [comment]
I'm unable to test this as my device doesn't support docker (DS218) but what happens if you strip the `https` from the URL? so it's just `ghcr.io/tasmoadmin/tasmoadmin:latest`?

**Comment by joka222** [comment]
the same error occurs:

Invalid Docker-Repository-URL: ghcr.io/tasmoadmin/tasmoadmin:latest

**Comment by joka222** [comment]
with SSH I  was able to pull the image without any problems. I think it is a Synology/Github problem that it doesn't work via the docker UI.

sudo -i
docker pull ghcr.io/tasmoadmin/tasmoadmin:latest

After download completes, the image appears in the Synology Docker app and it even recognizes the registry (https://ghcr.io) I've added for it.

**Comment by inverse** [comment]
Really strange - wonder why they were limiting the container registry that you can pull from.

Is there an easy way to report this behaviour to Synology?

**Comment by joka222** [comment]
No luck, same problem: Invalid Docker-Repository-URL

Maybe this is the reason of the problem: [https://github.community/t/correct-link-to-add-to-docker-registry/160636](url)

I am not really an expert in this topic.

THX for you help and that you continue the support for tasmoadmin!

**Comment by inverse** [comment]
Ouch - yeah sounds like a limitation of GitHub's container registry.

Could you document the steps you followed to get this working on your Synology so I can update the Wiki?

**Comment by joka222** [comment]
Install TasmoAdmin on a Synology NAS running Docker

1. Docker UI (Synology):
Login to DSM
Go To Docker -> Registry
Add  https://ghcr.io (will end in an error but the image will appear in the Synology Docker app later and it even recognizes the registry (https://ghcr.io))

2. Terminal:
SSH login via putty to DSM
sudo -i
docker pull ghcr.io/tasmoadmin/tasmoadmin:latest

3. Docker UI (Synology):
Login to DSM
Go to Docker -> image/launch
Advanced Settings
Enable auto-restart
set Local Ports (not automatic)
Volume -> persistent path

**Comment by inverse** [comment]
Thanks - I updated the Wiki based on this!
