### ISSUE TITLE
Selfupdate on 2.0.0beta6

### ISSUE THREAD

**Issue by SOliver78** [TasmoAdmin/TasmoAdmin#552]
Hello,

how can i fixed the following "error" in 2.0.0beta6?
![Screenshot_20220610_190538](https://user-images.githubusercontent.com/107271539/173117945-3556847c-8ba9-4094-8c5a-1873743ffeb4.png)
Under selfupdate the current version is unkown and the new version is the stable 1.8.0. When i make the update, it downgrades to 1.8.0.
Sorry for my bad english ;)

**Comment by inverse** [comment]
This sounds like an issue with v2.0.0-beta6 being a pre-release build and we're not accounting for those builds.

def something we should fix - thanks for raising!

**Comment by reloxx13** [comment]
beta only were available by docker, and docker does not have the self-update page (in the past). if you are on docker with a beta version, the docker detection does not work anymore and is a bug.

are you on docker?

**Comment by SOliver78** [comment]
> ~beta only were available by docker, and docker does not have the self-update page (in the past). if you are on docker with a beta version, the docker detection does not work anymore and is a bug.~ im not sure anymore
> 
> are you on docker?

Hello,

no, my VM are running with debian 10 an PHP 7.4. I checked out the developer branch.

**Comment by inverse** [comment]
@reloxx13 I guess we really need to improve the version checker - right now it's just comparing current vs latest and if that's different it always suggests upgrading.

Since I've introduced composer we could adopt https://packagist.org/packages/composer/semver

**Comment by inverse** [comment]
Improved the version check in https://github.com/TasmoAdmin/TasmoAdmin/pull/561 However it'll still suggest an update due to the current tag being set to an empty string :/

**Comment by inverse** [comment]
@SOliver78 is this still an issue?

**Comment by SOliver78** [comment]
@inverse I have been downgrade to 2.0.0, as there was other bugs for me.
Gosund P1 Power Stripe was recognized as 4 single-line devices.
Many devices displayed information from other devices.
I can possibly do an upgrade right away and create screenshots.

**Comment by SOliver78** [comment]
I Have downloaded tasmoadmin_v2.1.0-beta14.tar.gz, but in Selfupdate a new Version 2.0.0 was found:
![Screenshot_20220905_195850](https://user-images.githubusercontent.com/107271539/188498909-2b44ef60-6799-470f-8f51-5a0f83bc94b6.png)

**Comment by inverse** [comment]
@SOliver78 what version is displayed in the footer?

![image](https://user-images.githubusercontent.com/713525/188506305-64745837-47ba-4cdb-974a-696d44b2b53a.png)

**Comment by SOliver78** [comment]
@inverse no version is displayed for the 2.1.0-beta14 version:
![Screenshot_20220905_215353](https://user-images.githubusercontent.com/107271539/188507519-2988cb08-bbdb-4248-a353-6a3819a925b5.png)

**Comment by SOliver78** [comment]
I have tested 2.1.0-beta15 and now it looks like these:
![Screenshot_20220906_085409](https://user-images.githubusercontent.com/107271539/188567031-d5fa35fc-b968-4a4d-8dd0-a57534cba16e.png)

**Comment by inverse** [comment]
@SOliver78  Just published a change which should fix this case. The zips on the releases page now include the version and it should no longer be empty.

**Comment by inverse** [comment]
https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0-beta.16
