### ISSUE TITLE
RSSI, Version, and Runtime never load on device list page

### ISSUE THREAD

**Issue by deprecatedcoder** [TasmoAdmin/TasmoAdmin#554]
On the `<host>/devices` page the values for these columns perpetually have the loading icon and clicking `Detail View` is unavailable.

They work successfully on the `<host>/upload` page.

This had worked for my environment in the past and I've only noticed it not working now because I've just added two new devices.

![TasmoAdminError](https://user-images.githubusercontent.com/13654313/173244964-79e80e50-2ce4-4bb1-ac87-3baf1c387d20.png)

## Expected Behavior
These values should populate.

## Current Behavior
They do not.

## Possible Solution
I've not dug into it exhaustively, but the console in Firefox throws:

`Uncaught ReferenceError: nightmodeconfig is not defined [app.min.js:1:678]`

(see screenshot above)

I looked into that and found it is set in the `footer`, which is not loading on that page, but I've not determined why the footer does not load.

## Context (Environment)

`TasmoAdmin v1.8.0` installed via HomeAssistant addon `addon-tasmoadmin v.0.18.0`

## Context (Device)
All devices (5 Sonoff S31s) running either `Tasmota 11.0.0` or `11.1.0`

**Comment by inverse** [comment]
There was a new build published for the Home Assistant  addon which may fix this.

See: https://github.com/hassio-addons/addon-tasmoadmin/releases/tag/v0.19.0

Interesting about the undefined ref - will try to see what that is about.

**Comment by deprecatedcoder** [comment]
New build fixed it.

Go out to clean the garage for a couple hours and the community solves my problems.  I know it wasn't you directly that solved it, but you're still awesome 👍

Thanks for taking a look.
