### ISSUE TITLE
Composer lock file is missing

### ISSUE THREAD

**Issue by frenck** [TasmoAdmin/TasmoAdmin#555]
The `composer.lock` file is missing; therefore a reproducible build is not possible.

## Expected Behavior

Projects to ship with a `composer.lock` to which the project was tested and build against.

## Current Behavior

Lock file is missing, the dependencies installed may not be compatible or tested.

## Possible Solution

Add the composer.lock file to the project.

## Steps to Reproduce

1. Not
2. Relevant
3. For
4. This issue

## Context (Environment)

Any context.

## Context (Device)

Any context.

## Detailed Description

Not much more detail to provide

## Possible Implementation

```bash
git add composer.lock
```

**Comment by inverse** [comment]
Thanks for the bug report - will add this in :space_invader:

**Comment by inverse** [comment]
Published https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta7 if you wanna use this.

There was some additional work I wanted to do before a proper 2.0.0 such as improving the frontend to improve the update process/validation.
