### ISSUE TITLE
v2.0.0-beta8; Re-tagged, re-released

### ISSUE THREAD

**Issue by frenck** [TasmoAdmin/TasmoAdmin#569]
It seems like, just a couple of minutes ago, the [v2.0.0-beta8](https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta8) release and tag have been removed and re-tagged/re-released on another commit (fixing an OTA issue).

The problem with this approach is that external sources might already picked up the first [v2.0.0-beta8](https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta8)... For example, the Home Assistant add-on has already been built and shipped the previous. A change will not trigger a change from Docker's perspective.

## Expected Behavior

To have reproducable/stable version tagging policies.

## Current Behavior

Two downloads of the same version can actually be different versions (depending on the moment one has download it).

## Possible Solution

Tag a new version when something changes (nothing wrong with that). If a previous version should not be used, pull it (deleted it); and release a newer version bump.

## Steps to Reproduce

See above story.

## Context (Environment)

Not relevant

## Context (Device)

Not relevant

## Detailed Description

See above

## Possible Implementation

🤷

**Comment by inverse** [comment]
Yeah I forgot to include this other fix into that release and re-released with it included. And I saw you built the addon at the same time... Has it caused an issue for your new release?

Okays - I will avoid this retagging and just push a new version going forward or is there anything more? 

what exactly changed when you released https://github.com/hassio-addons/addon-tasmoadmin/releases/tag/v0.18.0 that required pulling in the beta builds?

**Comment by frenck** [comment]
> Yeah I forgot to include this other fix into that release and re-released with it included. 

You should **never** re-use version numbers. As one can have already downloaded it. You now have 2 different v2.0.0-beta8 versions in the wild.

> What exactly changed when you released

You release the same version number with a different source. The v2.0.0-beta8 in the add-on isn't the v2.0.0-beta8 now shown here on GitHub.

**Comment by inverse** [comment]
Thanks for the feedback - Will take note for future changes.

Hopefully can get a stable 2.0.0 release out so it can conform to the addon community guidelines.
