### ISSUE TITLE
Devices with more than 1 button/function no longer detecting on add or edit

### ISSUE THREAD

**Issue by charettepa** [TasmoAdmin/TasmoAdmin#570]
devices with more than 1 button/function (multi_button) no longer detecting on add or edit
only the 1st button/function is detected followed by (

![image](https://user-images.githubusercontent.com/22502305/174676232-1ecde355-c609-46ed-9b52-688f6506ba1c.png)

## Expected Behavior
For all buttons/functions of (multi_button) to detect and not error out

## Current Behavior
Only the first button/function is detected folowed by (
you can not save to add or edit existing device

## Possible Solution
???

## Steps to Reproduce
1. Add or edit device that has multi button/function
2. specify the IP
3. search/proceed
4. error appears

## Context (Environment)
Tasmoadmin 1.8 (0.19.0 on HA addons)

## Context (Device)
TasmoAdmin 1.8 , Devices that are multi button/function

## Detailed Description
allow the devices to detect or update for all buttons/functions as previously

## Possible Implementation
??

**Comment by inverse** [comment]
Hi @charettepa I hope that this is fixed in the next release of the HA Addon. 

A new build was pushed around 5 minutes ago which should get adopted by them and released. When you next get an update can you please report back and let me know if its fixed or is still an issue.

**Comment by charettepa** [comment]
Hi @inverse 

Yes I can confirm this seems to now be fixed in the 2nd release of beta8 
Which unfortunately currently is only an edge relese in HA addons
Hopefully it gets pushed as a non-edge release
Unfortunately there is no easy way to restore all the setting from a non-edge to an edge version

Its unfortunate they do not expose/make available the data paths for the addons, like a normal docker container

That being said release2 of beta8 does fix this issue
Thank You

**Comment by inverse** [comment]
Hopefully it gets promoted soon and you don't need to deal with that for long. Not sure of the process of addons getting promoted from edge to GA.

**Comment by charettepa** [comment]
As per previously
this issue seems to now be resolved

in addition
This has now been pushed to GA in HA Add-Ons as V 19.1
