### ISSUE TITLE
Autoupdate setting to choose Release Binaries vs Development Binaries

### ISSUE THREAD

**Issue by alexdelprete** [TasmoAdmin/TasmoAdmin#573]
TasmoAdmin is pulling binaries from the release branch (), it would be nice if we could also choose the dev branch in the settings.

Release branch (latest version v12.0.2.1): http://ota.tasmota.com/tasmota/release/
Dev branch (latest version v12.0.2): http://ota.tasmota.com/tasmota/

TasmoAdmin is using this to pull latest version: https://api.github.com/repos/arendst/Tasmota/releases/latest

But that only works for the Release branch, I don't know if there's another url for dev branch.

If you check the Tasmota Web Installer: https://tasmota.github.io/install/

You'll see that it is possible to choose a specific branch from the listbox.

## What should we implement

A setting to choose which branch should the autoupdate function pull binaries from (Release / Development)

**Comment by inverse** [comment]
Def need to priotise this task next! I notice that fetching releases via GitHub actually gets rate limited quite quickly as we've not authenticated against the API.

**Comment by alexdelprete** [comment]
Can't wait. Can you check the code of Tasmota Web Installer to see how they did it?

**Comment by alexdelprete** [comment]
I tried to update to latest 12.1.0 and I have a weird error:

```
Unable to access OTA URL @ http://tasmoadmin.osilife.net:80/data/firmwares/tasmota.bin.gz - TypeError: Failed to fetch
```

I didn't quite understand those 2 settings introduced in latest version (frontend/backend update check).

**Comment by inverse** [comment]
By default only the backend check should be enabled - which is that the the backend PHP application checks if it can access the firmware from itself to check if it has been downloaded correctly or the OTA firmware URL is accessible.

The frontend check does this from the client side code - it sounds like the frontend configuration was checked for you? Is it causing issues?

**Comment by inverse** [comment]
> Can't wait. Can you check the code of Tasmota Web Installer to see how they did it?

Looks like they store all the firmware in git https://github.com/tasmota/install/tree/main/firmware

Looks like the best solution would be be scrape the DOM from those pages you displayed

**Comment by alexdelprete** [comment]
> The frontend check does this from the client side code - it sounds like the frontend configuration was checked for you? Is it causing issues?

firmware was not accessible (failed to fetch), even if I disable both frontend/backend options.

**Comment by alexdelprete** [comment]
> Looks like the best solution would be be scrape the DOM from those pages you displayed

I agree, probably it's the best approach.

**Comment by inverse** [comment]
> firmware was not accessible (failed to fetch), even if I disable both frontend/backend options.

It shouldn't be like that - perhaps we should create another issue to discuss this - or even if this behaviour is needed


> I agree, probably it's the best approach.

Make some progress works quite nicely in that PR - main issues are

- requires php-dom to be installed
- if the site changes it breaks - but it should be quick to fix

**Comment by alexdelprete** [comment]
> perhaps we should create another issue to discuss this

Created issue #631

> Make some progress works quite nicely in that PR

Great. Let me know if I can help testing, etc.

> * if the site changes it breaks - but it should be quick to fix

I was thinking maybe we should ask @arendst for an advice on the best approach to programatically check release/development firmware releases, instead of scraping the OTA page.

**Comment by alexdelprete** [comment]
> * not sure if its a major bump for non-docker installs

From what I read [here](https://www.php.net/manual/en/dom.installation.php), php-dom is enabled by default, in case it's not, it's enabled by installing php-xml:

```
sudo apt-get install php-xml
```

So I don't think that's an issue for non-docker installs.

**Comment by inverse** [comment]
> From what I read [here](https://www.php.net/manual/en/dom.installation.php), php-dom is enabled by default, in case it's not, it's enabled by installing php-xml:

Thanks - that makes sense - sure we can document it too if needed

> I was thinking maybe we should ask @arendst for an advice on the best approach to programatically check release/development firmware releases, instead of scraping the OTA page.

That could work too @arendst any recommendations for this solution? right now i was just scraping the DOM on the OTA page which works fine but could be an issue if that ever changes.

**Comment by inverse** [comment]
I also noticed there is no non gz versions of the minimal firmware on here... but I posted #633 which talked about should this minimal firmware be removed completely?

**Comment by alexdelprete** [comment]
the minimal firmware is needed when there's a concern that the device doesn't have enough space to perform a direct full upgrade to another build. makes sense in that case to offer only the gz minimal. You could also gunzip the file to have the normal minimal version.

we could also opt to remove the double-step upgrade process...but some old devices with low resources might actually need that. It's not an easy decision...I also wrote about this [here](https://github.com/TasmoAdmin/TasmoAdmin/issues/633#issuecomment-1226224867).

**Comment by inverse** [comment]
Made some progress on the PR following your advice - to extract the bin.gz file on the fly. That being said the frontend code was not wired up to handle that for ~4h  but at least it's compatible behaviour.

Also added a toggle to switch to the development ones.

![image](https://user-images.githubusercontent.com/713525/187287097-f6f2fbb1-d7f6-4df3-97ca-91e215ccb144.png)

### Stable with gzip

![image](https://user-images.githubusercontent.com/713525/187287166-3d6fa46d-0cef-40fe-9a2c-377c677f0508.png)

### Dev without gzip

![image](https://user-images.githubusercontent.com/713525/187287335-32787ed6-8a8d-4a3d-9388-397d7e0ad2fd.png)

**Comment by alexdelprete** [comment]
Good job...can't wait to test the new version. :)

Are you parsing the OTA page with php-dom? we didn't have a reply from @arendst about the best way to look for upgrades unfortunately. Hope the OTA page doesn't change structure often. :)

BTW: you can really consider to drop the 2-step process so you don't need to worry about the minimal version, or you could make it optional in case someone needs it, but default is 1-step.

Today I tasmotized a really old sonoff relay, 6-7y old product, very low resources and I uploaded tasmota.bin without going through minimal, from the vendor's firmware: it worked perfectly.

I think the 2-step process is heritage of messy days...with a lot of buggy fw/devices etc.

**Comment by inverse** [comment]
You should be able to try it with the `ghcr.io/tasmoadmin/tasmoadmin:dev` image that is being built. - FYI I also configured this project to publish `dev` builds from master.


> BTW: you can really consider to drop the 2-step process so you don't need to worry about the minimal version, or you could make it optional in case someone needs it, but default is 1-step.

I think I will consider that - right now will leave it for the 2.1.0 release.

**Comment by alexdelprete** [comment]
The setting is working, and it's pointing at 12.1.1.1 that is the dev version of the fw.

One thing: the changelog on the upload_form page is the release version, the dev version of the changelog is: `https://github.com/arendst/Tasmota/blob/development/CHANGELOG.md`

Would be nice to show the appropriate changelog based on the chosen fw channel. :)

I'll try an upgrade of a switch now...will it do the 2-step process unpacking minimal on the fly?

**Comment by inverse** [comment]
> One thing: the changelog on the upload_form page is the release version, the dev version of the changelog is: https://github.com/arendst/Tasmota/blob/development/CHANGELOG.md

Thanks for the heads up - I'll change that next

> I'll try an upgrade of a switch now...will it do the 2-step process unpacking minimal on the fly?

The code never did the minimal since 4 years... but it'll respect your gzip setting :)

**Comment by alexdelprete** [comment]
> The code never did the minimal since 4 years... but it'll respect your gzip setting :)

ROTFL. :)

I remember 1y ago, first time I used tasmoadmin, I tried the update on a switch, it didn't work, and when I logged in the device, and the minimal version fw was installed, I completed the update manually with the full fw. Don't know what happened...since then, I didn't really trusted the process, now I do. :)

I tried the upgrade, it worked fine. Great job.

![image](https://user-images.githubusercontent.com/7027842/187544543-7a4cf61a-58e8-403b-90c2-c2fb64e28270.png)

**Comment by alexdelprete** [comment]
> The changelog issue should be fixed on the dev build :)

You want me to switch to dev build? mmmm...I don't trust devs so much. ;) (joking...)

> Need to figure out the issue with those first two upgrade output and it feels like we should release.

No big deal...you'll find the tiny bug...:)

> Thanks so much for the feedback + testing - glad I could add your feature request!

It's my way to contribute to the open source community, you are the ones who put in the real work, so the only thing I can do is bring my career experience as an ex (old) developer/project manager/etc. :)

You want me to add FR so you can track them? Sorry about that...sometimes during the conversation I come up with ideas but I forget to open FRs. Let me know...

**Comment by alexdelprete** [comment]
@inverse  Malachi, I tried the upgrade (beta12) on a device, and there's a thing I noticed I wanted to show you:

1. My config is normal bin (no gzip) and dev firmware.
2. I selected automatic upgrade and chose the device, while watching the device console in another tab
3. Here's the first part of the commands from the device console:

```log
05:07:57.497 MQT: stat/tasmota_765137/RESULT = {"OtaUrl":"http://tasmoadmin.axel.dom:5556/data/firmwares/tasmota.bin"}
05:07:57.545 MQT: stat/tasmota_765137/RESULT = {"Upgrade":"Version 12.1.1 from http://tasmoadmin.axel.dom:5556/data/firmwares/tasmota.bin"}
```

Please notice when it says "Upgrade: Version 12.1.1", is that supposed to be 12.1.1.1 (latest dev version) or it's reporting the current version of the device?

4. After that the device rebooted, and after the reboot I saw these:

```log
00:00:00.001 HDW: ESP8285
00:00:00.046 CFG: Loaded from flash at FB, Count 66
00:00:00.051 Project tasmota - Tasmota Switch Pedonale Version 12.1.1.1(minimal)-2_7_4_9(2022-08-30T17:51:52)
00:00:00.052 WARNING This version does not support persistent settings
00:00:00.645 WIF: Connecting to AP1 NetStumbling? Channel 6 BSSId 2C:91:AB:A0:0A:7F in mode 11n as tasmo-pedonale...
00:00:01.753 WIF: Connected
00:00:02.004 HTP: Web server active on tasmo-pedonale with IP address 10.1.10.124
```

Look at the 3rd line, it says version 12.1.1.1 (minimal). So it looks like it's doing the 2-step process. The device rebooted again, I guess to install the complete firmware image.

5. After reboot I saw this in the console:

```log
00:00:00.001 HDW: ESP8285
00:00:00.046 CFG: Loaded from flash at FB, Count 66
00:00:00.254 QPC: Reset
00:00:00.264 Project tasmota - Tasmota Switch Pedonale Version 12.1.1.1(tasmota)-2_7_4_9(2022-08-30T17:48:32)
00:00:00.903 WIF: Connecting to AP1 NetStumbling? Channel 6 BSSId 2C:91:AB:A0:0A:7F in mode 11n as tasmo-pedonale...
00:00:01.753 WIF: Connected
00:00:02.053 HTP: Web server active on tasmo-pedonale with IP address 10.1.10.124
05:09:26.018 MQT: Attempting connection...
05:09:26.066 MQT: Connected
05:09:26.069 MQT: tele/tasmota_765137/LWT = Online (retained)
05:09:26.071 MQT: cmnd/tasmota_765137/POWER = 
05:09:26.078 MQT: tele/tasmota_765137/INFO1 = {"Info1":{"Module":"1 Channel","Version":"12.1.1.1(tasmota)","FallbackTopic":"cmnd/DVES_765137_fb/","GroupTopic":"cmnd/tasmotas/"}}
05:09:26.087 MQT: tele/tasmota_765137/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"tasmo-pedonale","IPAddress":"10.1.10.124"}}
05:09:26.098 MQT: tele/tasmota_765137/INFO3 = {"Info3":{"RestartReason":"Software/System restart","BootCount":13}}
```

So now the device has the full firmware image, and seems to be working ok. :)

I'm curious to know your thoughts about this, if the 2-step process is not due to tasmoadmin code, then the tasmota devs must have integrated it in the firmware, but I'm just speculating here...

**Comment by inverse** [comment]
Just did the same steps as you (except with gzip enabled) and saw the exact same things.

```
05:07:57.545 MQT: stat/tasmota_765137/RESULT = {"Upgrade":"Version 12.1.1 from http://tasmoadmin.axel.dom:5556/data/firmwares/tasmota.bin"}
```

I wonder where it's getting that version from - that's not being sent from TasmoAdmin all we do is set the OTA URL + trigger the upgrade. One to report to upstream perhaps?

Very strange about the minimal flow too since we only set the non-minimal binary. Would be great to have input from the Tasmota dev's on this.

**Comment by inverse** [comment]
> It's my way to contribute to the open source community, you are the ones who put in the real work, so the only thing I can do is bring my career experience as an ex (old) developer/project manager/etc. :)

It'a my hobby outside of work + family life - I work as a engineer but on different projects and problem spaces. Sounds like you've got lots of experiences in that field too :)


> You want me to add FR so you can track them? Sorry about that...sometimes during the conversation I come up with ideas but I forget to open FRs. Let me know...

Whenever you have them feel free to put them down - Might not have the time to get through them all but Perhaps others can help too. The dev experience on this project is a bit nicer if you're familiar with some tools like docker/php etc - only thing missing is xdebug for step by step debugging.

**Comment by alexdelprete** [comment]
> I work as a engineer but on different projects and problem spaces

software engineer?

> Whenever you have them feel free to put them down - Might not have the time to get through them all but Perhaps others can help too.

I'll try my best. My problem is that my brain is strange: my creativity is triggered while brainstorming with people about a particular issue. Otherwise I start concentrating on other things and so I lose focus. :)

> The dev experience on this project is a bit nicer if you're familiar with some tools like docker/php etc

my homelab is based on proxmox: LXCs + docker. but it's only a few months, I'm not an expert...but having fun learning new things. :)

**Comment by inverse** [comment]
> software engineer?

Yup backend work mostly 

> I'll try my best. My problem is that my brain is strange: my creativity is triggered while brainstorming with people about a particular issue. Otherwise I start concentrating on other things and so I lose focus. :)

Sounds like a good person to have within a team :)

> my homelab is based on proxmox: LXCs + docker. but it's only a few months, I'm not an expert...but having fun learning new things. :)

The best way to learn :) Sounds good - I just have my laptop + pi4 for Home Assistant.

> Yes, probably it should be reported there...I bet the bug is they truncate the version to 3 digits. :)

I wouldn't be surprised! Haven't actually looked at the code for that... probably a lot lower level then I'm used too :) 

> 
I wonder where it's getting that version from - that's not being sent from TasmoAdmin all we do is set the OTA URL + trigger the upgrade. One to report to upstream perhaps?

Yes, probably it should be reported there...I bet the bug is they truncate the version to 3 digits. :)

Very strange about the minimal flow too since we only set the non-minimal binary. Would be great to have input from the Tasmota dev's on this.

I'm starting to think that the main firmware does actually contain the minimal firmware, so the devices probably do the 2-step process in any case...but it's just speculation...based on observation: the device actually did 2 reboots. ;)

Would be curious to know...  @arendst What's going on here?

**Comment by inverse** [comment]
@alexdelprete looks like perhaps it should have been a `v3.0.0` release 

https://github.com/TasmoAdmin/TasmoAdmin/issues/679

`ext-dom` :cry:

**Comment by inverse** [comment]
Although It's weird... the scraper

https://github.com/FriendsOfPHP/Goutte/blob/master/composer.json

Doesn't define it needs `ext-dom` or even the actual dependency of that which uses it directly...

https://github.com/symfony/dom-crawler/blob/6.1/composer.json

Super confused :/

**Comment by inverse** [comment]
https://github.com/symfony/symfony/issues/36150#issuecomment-601779813

okays looks like Symfony doesnt do this - I added it to TasmoAdmin
