### ISSUE TITLE
Error on the Update page

### ISSUE THREAD

**Issue by onlize** [TasmoAdmin/TasmoAdmin#574]
## Steps to Reproduce

1. Go to TasmoAdmin
2. Click on Devices
3. Click on Update
4. Click on Automatic button

## Context (Device)
I have two devices with Home Assistant latest version (2022.6.6). I have the same issue on both devices after I upgraded TasmoAdmin to the 0.19.1 version.

## Detailed Description
My TasmoAdmin was updated today to the 0.19.1 version. After that, I found that there was a new Tasmota version. When I clicked on the Updates and Automatic button, I had to wait for a long time, but after that, I received the following on the page. I tried it multiple times:

`
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Failed to connect to 192.168.86.12 port 9541 after 128778 ms: Operation timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://192.168.86.12:9541/data/firmwares/tasmota-minimal.bin in /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() #2 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish() #3 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #4 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #5 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #6 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke() #7 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #8 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke() #9 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #10 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke() #11 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer() #12 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync() #13 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/ClientTrait.php(61): GuzzleHttp\Client->request() #14 /var/www/tasmoadmin/tasmoadmin/src/Update/FirmwareChecker.php(20): GuzzleHttp\Client->head() #15 /var/www/tasmoadmin/tasmoadmin/pages/upload.php(221): TasmoAdmin\Update\FirmwareChecker->isValid() #16 /var/www/tasmoadmin/tasmoadmin/index.php(55): include_once('...') #17 {main} thrown in /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210
`

**Comment by inverse** [comment]
Thanks for raising this - A check was added in the latest build to check that the backend is able to access the firmware before trying to perform the update. It shouldn't blow up like that and I have created a fix for that in #575 

Are you able to access the firmware in your browser with http://192.168.86.12:9541/data/firmwares/tasmota-minimal.bin?

**Comment by onlize** [comment]
Thank you, I can access the firmware from the browser, and I updated my tasmota devices. I just wanted to let you know about the error.

You can close this issue if you know about this.

**Comment by inverse** [comment]
It should have printed a more helpful message which will be fixed in the next release. 

Glad you got it working in the end! Thanks fort he bug report :)

**Comment by helmar74** [comment]
Hi, updated to 2.0 (latest), same issue here:

```
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Could not resolve host: raw.githubusercontent.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://raw.githubusercontent.com/arendst/Tasmota/development/RELEASENOTES.md?r=2125173384 in /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() #2 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish() #3 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #4 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #5 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #6 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke() #7 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #8 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke() #9 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #10 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke() #11 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer() #12 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync() #13 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request() #14 /var/www/tasmoadmin/src/Helper/TasmotaHelper.php(26): GuzzleHttp\Client->get() #15 /var/www/tasmoadmin/pages/upload_form.php(7): TasmoAdmin\Helper\TasmotaHelper->getReleaseNotes() #16 /var/www/tasmoadmin/index.php(55): include_once('...') #17 {main} thrown in /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210
```

**Comment by inverse** [comment]
Closing as the next version of the HA addon has been pubished
