### ISSUE TITLE
"Update Device" page shows old Changelog

### ISSUE THREAD

**Issue by buliwyf42** [TasmoAdmin/TasmoAdmin#580]
## Expected Behavior
The latest Changelog should be shown

## Current Behavior
An old changelog is shown. (8.5.1)

## Possible Solution
Update to the latest Changelog or remove the part at all.

## Steps to Reproduce
Create Docker container with the latest Tasmoadmin Version 2.0.0 

## Context (Environment)
Docker (latest)

## Context (Device)
None

## Detailed Description
--

## Possible Implementation
--

**Comment by inverse** [comment]
Hi @buliwyf42 good catch - this check needs to be improved to pull from https://github.com/arendst/Tasmota/blob/development/CHANGELOG.md and not just https://github.com/tasmota/docs/blob/master/docs/changelog.md
