### ISSUE TITLE
CURL ERROR when adding devices on a dockerised TasmoAdmin

### ISSUE THREAD

**Issue by Th0maz** [TasmoAdmin/TasmoAdmin#585]
## Expected Behavior

Devices can be found and added.

## Current Behavior

Error is shown:
Device not found
CURL ERROR => cURL error 28: Failed to connect to 192.168.1.11 port 80 after -392000 ms: Operation timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://192.168.1.11/cm?user=admin&password=MyP4ssw0rd&cmnd=status+0

## Possible Solution

When I run TasmoAdmin in xampp on my Windows computer, the devices can be found successfully.

## Steps to Reproduce

1. Start TasmoAdmin 2.0.0 in docker
2. Connect container to bridge network
3. login
4. search for a device with device ip

## Context (Environment)

Dockerised TasmoAdmin 2.0.0 on a bridge network

**Comment by Th0maz** [comment]
I'm running TasmoAdmin 1.6.3 on the same docker host with the same network configuration and devices can be found there.

**Comment by Th0maz** [comment]
The error message appears within 1 second, so I don't think it's a timeout.
When I enter the url into the browser of my windows computer in the same local network, I get the expected response.

I believe it could be a network issue. My windows computer (same subnet, 192.168.1...) can access the tasmota devices. The docker container (different subnet) cannot.
If I remember correctly, when I first opened the auto discovery menu, the ip address range was preset with the docker containers subnet addresses (172.28.0...)

Same code 2.0.0 works fine in xampp, BUT on my windows machine, same subnet.

I'm not sure how to troubleshoot the docker scenario, since the older TasmoAdmin is working fine with similar network settings as the 2.0.0 container.

**Comment by inverse** [comment]
> If I remember correctly, when I first opened the auto discovery menu, the ip address range was preset with the docker containers subnet addresses (172.28.0...)

I think that's the standard on how the extension works as we resolve this from [SERVER_ADDR](https://www.php.net/manual/en/reserved.variables.server.php).

 How are you running the container? Could you provide the full command?

**Comment by Th0maz** [comment]
I'm running both containers through portainer.
But I also tried with the basic command from the wiki:
`docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:latest`
Does not make a difference.

docker inspect says "bridge" for both old and new container.

I also tried to run the container in my docker macvlan network, so the container gets an ip address from the same subnet as my tasmota devices.

When I click "Settings" in TasmoAdmin, I get another error that could be a hint for a network issue:
`Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Could not resolve host: api.github.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.github.com/repos/arendst/Tasmota/releases/latest in /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() #2 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish() #3 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #4 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #5 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #6 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke() #7 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #8 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke() #9 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #10 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke() #11 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer() #12 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync() #13 /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request() #14 /var/www/tasmoadmin/src/Helper/TasmotaHelper.php(131): GuzzleHttp\Client->get() #15 /var/www/tasmoadmin/src/Helper/TasmotaHelper.php(74): TasmoAdmin\Helper\TasmotaHelper->getLatestRelease() #16 /var/www/tasmoadmin/pages/site_config.php(55): TasmoAdmin\Helper\TasmotaHelper->getReleases() #17 /var/www/tasmoadmin/index.php(55): include_once('...') #18 {main} thrown in /var/www/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210`

**Comment by inverse** [comment]
Def seems suspect - the fact it cannot query the GitHub API implies network/DNS issues.

The backend was overhauled to instead of using curl directly to use guzzle. Which in theory should be using `0` as the default timeouts meaning indefinitely.

**Comment by inverse** [comment]
Just pushed a new dev build which adapted the curl timeouts in the sonoff class to how they were before. you can test it with `ghcr.io/tasmoadmin/tasmoadmin:dev`. Let me know how it works

**Comment by Th0maz** [comment]
Thanks, just tried that, but I could not see any difference.
All the errors appear after 1-2 seconds, so I don't think it's a real timeout.
However I cannot find any network issues in my environment. Everything else is working fine.
Any hints on how to troubleshoot this from within the docker container? Some commands I can try?

**Comment by Th0maz** [comment]
I can see in my DNS servers log, that the container sends some requests (to raw.githubusercontent.com or api.github.com) and gets correct responses. But it shows these errors anyway:
[..] Could not resolve host: raw.githubusercontent.com [..]

**Comment by inverse** [comment]
Very strange - you could try shelling into the container.

```bash
docker exec -it <container-name> bash
```

And then see if you can curl those URL's directly

```bash
curl -I https://raw.githubusercontent.com/arendst/Tasmota/development/RELEASENOTES.md
```

Which would isolate the issue to to PHP and not the container itself.

**Comment by Th0maz** [comment]
bash-5.1# curl -I https://raw.githubusercontent.com/arendst/Tasmota/development/RELEASENOTES.md
curl: (6) Could not resolve host: raw.githubusercontent.com

bash-5.1# ping google.de
ping: bad address 'google.de'

bash-5.1# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: clock_gettime(MONOTONIC) failed

Could be something with alpine linux and ARM. My docker host is a raspberry pi 4 running raspbian buster.

**Comment by inverse** [comment]
Another user reported issues in the past with the changes to Alpine.

See: https://github.com/TasmoAdmin/TasmoAdmin/issues/488#issuecomment-1172199029

Perhaps this will help you too. I wasn't able to reproduce it on a PI3 running dietpi.

**Comment by Th0maz** [comment]
> Another user reported issues in the past with the changes to Alpine.
> 
> See: [#488 (comment)](https://github.com/TasmoAdmin/TasmoAdmin/issues/488#issuecomment-1172199029)
> 
> Perhaps this will help you too. I wasn't able to reproduce it on a PI3 running dietpi.

Thanks for the link, that did the trick 🥳
