### ISSUE TITLE
PHP8.1 und v2.1.0-beta5

### ISSUE THREAD

**Issue by detafun** [TasmoAdmin/TasmoAdmin#609]
Hallo,
habe gerade mal alles neu installiert und gleich mal die aktuelle Beta.
Folgende Fehler:
1. Beim suchen von neuen Modulen (Auto-Scan) kommt dieses:
 Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/tasmoadmin/src/Sonoff.php on line 112

Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/tasmoadmin/src/Sonoff.php on line 112

Findet aber alle Module uns speichert diese auch.

2. Wenn ich die Liste Aufrufe ( Module - Liste )
Zeigt er mir die Liste, aber es rödelt bei den Infos weiter ohne das was dann Angezeigt wird:

![image](https://user-images.githubusercontent.com/44980055/181202494-34796c77-3b35-423a-b596-3f9a74ee3431.png)

Auch wenn ich auf Detailansicht geht, passiert nichts. Keine Änderung. er zeigt keine Details an.

cu

**Comment by alexdelprete** [comment]
I confirm the issue.

**Comment by inverse** [comment]
Just published `v2.1.0-beta6` which should fix the broken JavaScript.

Will need to look into the PHP 8.1 problems - The base image is currently only built against PHP 8.0 so I haven't tested it with 8.1 yet.

**Comment by alexdelprete** [comment]
> Just published `v2.1.0-beta6` which should fix the broken JavaScript.

Thanks, I confirm it's fixed.

**Comment by inverse** [comment]
Should be fixed in https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0-beta12
