### ISSUE TITLE
TasmoAdmin 2.0.0 not able to write changes to devices.csv

### ISSUE THREAD

**Issue by turbo112** [TasmoAdmin/TasmoAdmin#624]
Hi @ all,
when I try to unselect for example  "Einbeziehen in 'ALLE AUS'" and save that. It dosn't work.

## Expected Behavior
I think it has to be saved in devices.csv

## Current Behavior
The Line for this Device is not complete anymore, like that:
2,luefter,x.x.x.x,admin,,bulb_1,2

## Possible Solution
No idea ...

## Steps to Reproduce

1. Go Module --> List
2. go Change device
3. Save the change
4. Check
Still the same, but the devices.csv is not correct anymore.

## Context (Environment)
It's a docker container

## Context (Device)
All devieces I have

I also tried that in Version 1.8.0 and in 2-1.0-beta allover the same.
In version 1.7.0 it works ...

A friend off mine tried the same on an Installation on a normal Web server with the same result.

So I hope that all information's here.
Sorry when not, it's my first Bug report in here.

Regards

Turbo112

**Comment by rubberduck09** [comment]
I have the same behavior at my system (no docker - only php on apache). If i manually edit the line of the device the tickmark goes away in the device edit page. But if i klick on save then the edit goes away and when i go to the device edit page again the tickmark is here again.

**Comment by inverse** [comment]
Should be fixed in https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0-beta9

Let me know if that solves it for you. We're def getting close to releasing `v2.1.0`

I must have missed that when reworking the device layer. Thanks for the report.

**Comment by turbo112** [comment]
> Should be fixed in https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0-beta9
> 
> Let me know if that solves it for you. We're def getting close to releasing `v2.1.0`
> 
> I must have missed that when reworking the device layer. Thanks for the report.

Thanks for fixing that quick!
I'm testing on 2.1.0-beta9 and I think I'll stay on it for now ...
So, I think it's solved for me.
