### ISSUE TITLE
Unintended Click when swiping/scrolling on android device

### ISSUE THREAD

**Issue by Th0maz** [TasmoAdmin/TasmoAdmin#632]
## Expected Behavior

Swiping and scrolling is possible without switching devices on or off.
## Current Behavior

Items are clicked unintentionally when swiping or scrolling on mobile devices or touch screens.
## Steps to Reproduce

1. Have 30 or more devices added to TasmoAdmin
2. Open TasmoAdmin on mobile device
3. Swipe up / scroll down to reach lower items
4. Device that you put your finger on to swipe is toggled unintentionally

## Context (Environment)

TasmoAdmin 2.0.0 running in docker
## Context (Device)

Android 12 mobile phone with Chrome browser
## Possible Implementation

I did not have this issue with TasmoAdmin version 1.6.3

**Comment by inverse** [comment]
Should be resolved in the next release

**Comment by inverse** [comment]
You can try the https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0-beta15 release which will is almost ready for release out of beta.

**Comment by Th0maz** [comment]
Just tried this version. Bug is fixed, works as expected for me now. Thanks!

**Comment by inverse** [comment]
Awesome :+1: Glad it worked out!
