### ISSUE TITLE
.version not working in 2.1.0-beta16

### ISSUE THREAD

**Issue by SOliver78** [TasmoAdmin/TasmoAdmin#653]
@inverse i have tested the beta version, unfortunately it was not successful. In the document root there is the .version, which is also readable.
![Screenshot_20220906_210102](https://user-images.githubusercontent.com/107271539/188718822-d7f453a6-b74d-4273-8a24-e14d2ce2849f.png)

**Comment by inverse** [comment]
Sorry about that - I was setting the defaults not writing out the version.

https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0-beta.17

This should fix it - give it ~3 minutes to publish the assets :crossed_fingers:

**Comment by SOliver78** [comment]
Now it looks like ok ;)
![Screenshot_20220906_213906](https://user-images.githubusercontent.com/107271539/188723945-08026b89-b91d-4bd2-a975-860ea4b8410a.png)

I will test it with the next tasmota update of my 62 devices ;)

**Comment by inverse** [comment]
That's a lot of devices - good luck :crossed_fingers: The whole update process was changed too and it should provide feedback a lot quicker.

However for that many devices perhaps I should also add some overview showing like

```
6/62 devices updated
```

as the page would get quite big with that many.

**Comment by inverse** [comment]
Probably would be best to try the upgrade with a few devices at first and see how that goes :+1:
