### ISSUE TITLE
Fatal error: Allowed memory size exhausted during AutoScan #255

### ISSUE THREAD

**Issue by llluis** [TasmoAdmin/TasmoAdmin#667]
Application crashes with an out of memory error when attempting an AutoScan spanning accross multiple subnets.
It was discovered because an user error when inputing the range, but it would be nice to validate the user input or protect the application from crashing.

## Expected Behavior
Receive an "unsupported" notification if range in AutoScan spans accros multiple subnets or something else preventing the exception to be shown to user and alerting about the mistake.

## Current Behavior
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 149

@inverse, even setting the log level in the addon to trace, I don't have any output in the addon log in HomeAssistant. Any ideas how I can extract the full stack?

## Steps to Reproduce
Open the interface and select Autoscan.
Select from IP as 192.168.44.1
Select To IP as 192.168.66.254

## Context (Environment)
HomeAssitant OS running on Raspi 4 4GB
TasmoAdmin Addon 0.20.0

**Comment by inverse** [comment]
Added a limit on the max number of IPs to scan - also found the IP range generation code was broken.

Thanks for raising!
