### ISSUE TITLE
Protect from powering on/off / include in all off not working

### ISSUE THREAD

**Issue by woessmich** [TasmoAdmin/TasmoAdmin#673]
## Expected Behavior
Ticking or unticking and save should change setting for device

## Current Behavior
No change

## Possible Solution
Fix as it was working in 1.8.0

## Context (Environment)
TasmoAdmin V2.0.0

**Comment by inverse** [comment]
I believe this is fixed in the latest unreleased version.

How are you currently running it? If docker you could try one of the 2.1.0 beta releases?

**Comment by inverse** [comment]
https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0

Published new version let me know if it fixes your issue

**Comment by woessmich** [comment]
Ok, I can confirm, the issue is fixed in v2.1.0. Thank you!
