### ISSUE TITLE
Uncaught Error in 2.1.0

### ISSUE THREAD

**Issue by arteck** [TasmoAdmin/TasmoAdmin#679]
![grafik](https://user-images.githubusercontent.com/6681528/194470186-6da9ce3a-6b4b-4f7e-9fa9-4f8e9d702d5c.png)

**Comment by inverse** [comment]
What's your setup? 

Looks like  you need to include the php-dom extension ?

**Comment by arteck** [comment]
very simple lxc Ubuntu 20.04.5 LTS in proxmox

**Comment by alexdelprete** [comment]
> Perhaps installing `php-xml` via `apt`?

It was discussed: https://github.com/TasmoAdmin/TasmoAdmin/issues/573#issuecomment-1221331721

Can you include it in the image?

**Comment by inverse** [comment]
its in the image, just not fir people running stand alone.

**Comment by JF62** [comment]
I have same problem with all devices offline - what do you mean by version 2.0 works? Did you moved back to this Version or found a solution to solve it?

**Comment by inverse** [comment]
Is there anything suspect in the browser developer console? Seems strange indeed :/ I'm not able to reproduce so far.

**Comment by JF62** [comment]
No, console looks ok
It's running standalone on raspberry pi linux 11, appache and not in docker

**Comment by inverse** [comment]
Anything suspect when you call the endpoint directly?

```
curl -X POST http://yourhost:yourport/index.php?doAjaxAll
```

**Comment by JF62** [comment]
Getting just the output and looks ok

**Comment by JF62** [comment]
Ok, tested in Edge now and there console shows: following:
Form elements must have labels: Element has no title attribute Element has no placeholder attribute (19 - times (number of my modules)  <input type="checkbox">

And also this:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

bootstrap.bundle.js:1

http://myipofhost:myport/node_modules/bootstrap/dist/js/bootstrap.bundle.js?_=v210



</body>
</html>

**Comment by inverse** [comment]
Wonder what it could be :/

I just spun up a Ubuntu 20.04 Vagrant box setting up Apache + PHP downloading the code from https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0 here and it works for me :/

**Comment by JF62** [comment]
It all happend after update from 2.0 to 2.1.0 via your update mechanism. Before all was working smooth and easy

**Comment by inverse** [comment]
Just did the same process and was unable to reproduce :/ 

Was there any errors during the update process?  or in `/var/log/apache2/error.log`?

**Comment by JF62** [comment]
[Sun Oct 09 00:00:09.234195 2022] [mpm_prefork:notice] [pid 663] AH00163: Apache/2.4.54 (Raspbian) configured -- resuming normal operations
[Sun Oct 09 00:00:09.234303 2022] [core:notice] [pid 663] AH00094: Command line: '/usr/sbin/apache2'
[Sun Oct 09 20:47:28.790705 2022] [php7:error] [pid 17128] [client 192.168.10.159:58030] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/tasmoadmin/tasmoadmin/ve
ndor/symfony/dom-crawler/Crawler.php:1166\nStack trace:\n#0 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(1289): Symfony\\Component\\DomCrawler\\Crawler->parseXhtml(
)\n#1 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(198): Symfony\\Component\\DomCrawler\\Crawler->parseHtmlString()\n#2 /var/www/tasmoadmin/tasmoadmin/vendor/symfon
y/dom-crawler/Crawler.php(182): Symfony\\Component\\DomCrawler\\Crawler->addHtmlContent()\n#3 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(519): Symfony\\Co
mponent\\DomCrawler\\Crawler->addContent()\n#4 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(419): Symfony\\Component\\BrowserKit\\AbstractBrowser->createCra
wlerFromContent()\n#5 /var/www/tasmoadmin/tasmoadmin/src/Helper/TasmotaOtaScraper.php(28): Symfony\\Component\\BrowserKit\\AbstractBrowser->request()\n#6 /var/www/tasmoadmin/tasmoadmin/src/
Helper/TasmotaHelper.ph in /var/www/tasmoadmin/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php on line 1166, referer: http://192.168.10.20:9999/devices
[Sun Oct 09 20:51:00.162296 2022] [php7:error] [pid 17128] [client 192.168.10.159:58116] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/tasmoadmin/tasmoadmin/ve
ndor/symfony/dom-crawler/Crawler.php:1166\nStack trace:\n#0 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(1289): Symfony\\Component\\DomCrawler\\Crawler->parseXhtml(
)\n#1 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(198): Symfony\\Component\\DomCrawler\\Crawler->parseHtmlString()\n#2 /var/www/tasmoadmin/tasmoadmin/vendor/symfon
y/dom-crawler/Crawler.php(182): Symfony\\Component\\DomCrawler\\Crawler->addHtmlContent()\n#3 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(519): Symfony\\Co
mponent\\DomCrawler\\Crawler->addContent()\n#4 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(419): Symfony\\Component\\BrowserKit\\AbstractBrowser->createCra
wlerFromContent()\n#5 /var/www/tasmoadmin/tasmoadmin/src/Helper/TasmotaOtaScraper.php(28): Symfony\\Component\\BrowserKit\\AbstractBrowser->request()\n#6 /var/www/tasmoadmin/tasmoadmin/src/
Helper/TasmotaHelper.ph in /var/www/tasmoadmin/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php on line 1166, referer: http://192.168.10.20:9999/start
[Sun Oct 09 20:51:02.262643 2022] [php7:error] [pid 17128] [client 192.168.10.159:58116] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/tasmoadmin/tasmoadmin/ve
ndor/symfony/dom-crawler/Crawler.php:1166\nStack trace:\n#0 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(1289): Symfony\\Component\\DomCrawler\\Crawler->parseXhtml(
)\n#1 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(198): Symfony\\Component\\DomCrawler\\Crawler->parseHtmlString()\n#2 /var/www/tasmoadmin/tasmoadmin/vendor/symfon
y/dom-crawler/Crawler.php(182): Symfony\\Component\\DomCrawler\\Crawler->addHtmlContent()\n#3 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(519): Symfony\\Co
mponent\\DomCrawler\\Crawler->addContent()\n#4 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(419): Symfony\\Component\\BrowserKit\\AbstractBrowser->createCra
wlerFromContent()\n#5 /var/www/tasmoadmin/tasmoadmin/src/Helper/TasmotaOtaScraper.php(28): Symfony\\Component\\BrowserKit\\AbstractBrowser->request()\n#6 /var/www/tasmoadmin/tasmoadmin/src/
Helper/TasmotaHelper.ph in /var/www/tasmoadmin/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php on line 1166, referer: http://192.168.10.20:9999/start
[Sun Oct 09 20:52:30.986884 2022] [mpm_prefork:notice] [pid 663] AH00170: caught SIGWINCH, shutting down gracefully
[Sun Oct 09 20:52:31.200772 2022] [mpm_prefork:notice] [pid 20406] AH00163: Apache/2.4.54 (Raspbian) configured -- resuming normal operations
[Sun Oct 09 20:52:31.200979 2022] [core:notice] [pid 20406] AH00094: Command line: '/usr/sbin/apache2'
[Sun Oct 09 20:55:39.891928 2022] [php7:notice] [pid 20423] [client 192.168.10.159:58224] PHP Notice:  Undefined variable: targerVersion in /var/www/tasmoadmin/tasmoadmin/pages/upload.php o
n line 308, referer: http://192.168.10.20:9999/upload_form

**Comment by JF62** [comment]
DOM (php-xml) I installed after update manually because got same error as thread starter

**Comment by alexdelprete** [comment]
Did you install php-xml ?

`apt install php-xml`

**Comment by JF62** [comment]
yes, but after autoupdate

**Comment by alexdelprete** [comment]
> yes, but after autoupdate

did you restart tasmoadmin after installing pxp-xml?

**Comment by JF62** [comment]
I restarted appache and also did a complete system reboot - No change

**Comment by alexdelprete** [comment]
can you post the output of:

```
apt list --installed | grep php-xml
```

**Comment by JF62** [comment]
php-xml/stable,now 2:7.4+76 all  [installiert]

**Comment by alexdelprete** [comment]
so, without php-xml, you had the same problem of the OP, then you installed it and you see the spinning wheel for all devices?

**Comment by alexdelprete** [comment]
can you post the output of `php -m` please?

**Comment by JF62** [comment]
Yes and not only spinning - also dont see that they are on or off or can't switch

**Comment by JF62** [comment]
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by alexdelprete** [comment]
can you please check if in php.ini you have this: `extension=dom.so `

**Comment by JF62** [comment]
I don't had, even if I put in it doesn't work

**Comment by alexdelprete** [comment]
what version of php are you running? can you post the output of phpinfo()

**Comment by inverse** [comment]
Feels like it could be something with the JavaScript side of things if the `doAjaxAll`endoint is returning correctly.

It didn't change that much since the two versions and there should be some cache busting going on with query.. `?_=v210` but perhaps performing a hard refresh of the cache... in chrome it's ctrl + shift + r I believe.

**Comment by alexdelprete** [comment]
Malachi, can you check this?

![image](https://user-images.githubusercontent.com/7027842/194779294-97db87e7-e822-4849-880b-3de913906213.png)

**Comment by JF62** [comment]
> what version of php are you running? can you post the output of phpinfo()

![Screenshot_83](https://user-images.githubusercontent.com/34992835/194779402-dcef24de-729d-4c05-b124-e0c72dff5608.png)

**Comment by alexdelprete** [comment]
I don't see these sections:

![image](https://user-images.githubusercontent.com/7027842/194779676-fa4f5b7a-4ff0-444a-81ea-73eddd2281c7.png)

![image](https://user-images.githubusercontent.com/7027842/194779669-ca45cd59-4fa3-4d19-884e-a9de2c9923b6.png)

**Comment by JF62** [comment]
![Screenshot_84](https://user-images.githubusercontent.com/34992835/194779768-09911338-2438-4d06-9b99-67fb5f852b84.png)
![Screenshot_86](https://user-images.githubusercontent.com/34992835/194779769-c307665e-2d9c-4348-b832-fd3481f9cba4.png)

**Comment by alexdelprete** [comment]
Ok, so DOM is installed correctly.

did you leave `extension=dom.so` in php.ini? if so, please remove it.

**Comment by JF62** [comment]
> Ok, so DOM is installed correctly.
> 
> did you leave `extension=dom.so` in php.ini? if so, please remove it.

done

**Comment by JF62** [comment]
should I just reinstall? But I expect others will have same problem after update

**Comment by alexdelprete** [comment]
> But I expect others will have same problem after update

up to now, there are only 2 people: you and the OP.

**Comment by JF62** [comment]
> > But I expect others will have same problem after update
> 
> up to now, there are only 2 people: you and the OP.

Now ... ;-)

**Comment by alexdelprete** [comment]
> Now ... ;-)

you predict the future? interesting...:)

**Comment by JF62** [comment]
Guys, I only liked to help to find a error. I can just reinstall and then it's gone

**Comment by alexdelprete** [comment]
> Guys, I only liked to help to find a error. I can just reinstall and then it's gone

yes it would be good to catch the bug actually.

do you have another RPi to try a fresh install?

**Comment by JF62** [comment]
> > Guys, I only liked to help to find a error. I can just reinstall and then it's gone
> 
> yes it would be good to catch the bug actually.
> 
> do you have another RPi to try a fresh install?

I can try, but maybe not tonight

**Comment by alexdelprete** [comment]
> I can try, but maybe not tonight

let us know. thanks for the help.

**Comment by JF62** [comment]
> Feels like it could be something with the JavaScript side of things if the `doAjaxAll`endoint is returning correctly.
> 
> It didn't change that much since the two versions and there should be some cache busting going on with query.. `?_=v210` but perhaps performing a hard refresh of the cache... in chrome it's ctrl + shift + r I believe.

I expect the problem also here

**Comment by JF62** [comment]
Installed new on a test pi and works without problems

**Comment by alexdelprete** [comment]
> Installed new on a test pi and works without problems

so it's something related to apache/php installation in that one.

you might uninstall apache+php and reinstall on that one.

**Comment by JF62** [comment]
> > Installed new on a test pi and works without problems
> 
> so it's something related to apache/php installation in that one.
> 
> you might uninstall apache+php and reinstall on that one.

for sure not, because there are two other virtual servers running on this system and they work like a charm

**Comment by JF62** [comment]
Next problem if I try to update clients with the new Version getting this error:

![Screenshot_88](https://user-images.githubusercontent.com/34992835/194926453-6654d7e1-1e7a-4387-98a9-12aac8875f35.png)

**Comment by alexdelprete** [comment]
Can you show the current version of that device and the version you're trying to update with?

**Comment by alexdelprete** [comment]
> for sure not, because there are two other virtual servers running on this system and they work like a charm

this leads me to think that the configuration you made for those two other virtual servers created the problem.

**Comment by JF62** [comment]
> Can you show the current version of that device and the version you're trying to update with?


Doing the update via webinterface of Module all works fine.
I compile by myself the tasmota but anyway. Version actual is: 
12.1.1.2 DE and new is 12.1.1.4 lite (gz)

**Comment by alexdelprete** [comment]
> Doing the update via webinterface of Module all works fine.

If the device has the same fw version and you want to upgrade it anyway, you need to enable this in the settings:

![image](https://user-images.githubusercontent.com/7027842/194932769-312f8336-7f4c-4554-9ddd-0d30eb07eea0.png)

**Comment by JF62** [comment]
> > for sure not, because there are two other virtual servers running on this system and they work like a charm
> 
> this leads me to think that the configuration you made for those two other virtual servers created the problem.

This is a nice try ;-) , but why did it work before and now doesn't and other guy had same errors?

**Comment by alexdelprete** [comment]
> This is a nice try ;-) , but why did it work before and now doesn't and other guy had same errors?

Very simple: Because you and the other guy have something configured that creates the issue.

DOM has been introduced in tha latest versions. The fact that you installed from scratch and everything worked should confirm that there's no bug, it's a specific configuration issue. Would be good to find it, but we tried and didn't.

**Comment by JF62** [comment]
> > Doing the update via webinterface of Module all works fine.
> 
> That's not a proper test, TasmoAdmin has a little bit of logic behind the updates. If the device has the same fw version and you want to upgrade it anyway, you need to enable this in the settings:
> 
> ![image](https://user-images.githubusercontent.com/7027842/194932769-312f8336-7f4c-4554-9ddd-0d30eb07eea0.png)

little bit? Can you explain then the tests you do?
Because change from a DE 12.1.1.2 to a Lite 12.1.1.4 is for sure a release change and if you like to test new versions, what's then?

**Comment by alexdelprete** [comment]
> 12.1.1.2 DE and new is 12.1.1.4 lite (gz)

@inverse Malachi, he's upgrading two different versions, but he reports that the upgrade was not done. I asked him to try a forced upgrade with the appropriate setting, but shouldn't the upgrade have been done anyways?

**Comment by JF62** [comment]
> > Doing the update via webinterface of Module all works fine.
> 
> That's not a proper test, TasmoAdmin has a little bit of logic behind the updates. If the device has the same fw version and you want to upgrade it anyway, you need to enable this in the settings:
> 
> ![image](https://user-images.githubusercontent.com/7027842/194932769-312f8336-7f4c-4554-9ddd-0d30eb07eea0.png)

Even with force upgrade getting this error:

![Uploading Screenshot_89.png…]()

**Comment by alexdelprete** [comment]
> little bit? Can you explain then the tests you do?
> Because change from a DE 12.1.1.2 to a Lite 12.1.1.4 is for sure a release change and if you like to test new versions, what's then?

I've done tests locally and the fw version check worked fine. But it's a new feature, so a bug could certainly be there, in order to debug it, next time DON'T UPGRADE MANUALLY and show us the fw version through screenshot of tasmota interface of the device and screenshot of which version you are upgrading to in TasmoAdmin interface.

With forced upgrade setting you are telling TasmoAdmin: don't care about versions, just flash. Exactly like it does with device web interface.

**Comment by alexdelprete** [comment]
> Even with force upgrade getting this error:

This is interesting. So the problem is not the version check. Can you try another device please? Just to make sure it's not a specific thing with that device.

**Comment by JF62** [comment]
> > little bit? Can you explain then the tests you do?
> > Because change from a DE 12.1.1.2 to a Lite 12.1.1.4 is for sure a release change and if you like to test new versions, what's then?
> 
> I've done tests locally and the fw version check worked fine. But it's a new feature, so a bug could certainly be there, in order to debug it, next time DON'T UPGRADE MANUALLY and show us the fw version through screenshot of tasmota interface of the device and screenshot of which version you are upgrading to in TasmoAdmin interface.
> 
> With forced upgrade setting you are telling TasmoAdmin: don't care about versions, just flash. Exactly like it does with device web interface.

see my post before...
It's other device **2**

**Comment by inverse** [comment]
Looks like we're missing a lot of translations - I assumed it would fallback to English in the JavaScript ones - I'll see what can be done there.


p.s. We have totally hijacked @arteck 's thread

**Comment by alexdelprete** [comment]
OMG, you're right. :(

@JF62 can you please open separate issues with all relevant info? Thanks.

**Comment by alexdelprete** [comment]
> Will do - but error still exists if we do a autoaupdate ;-)

I don't understand what you're saying, I just asked to discuss it in an appropriate thread since this is a totally **different** issue.

**Comment by alexdelprete** [comment]
@inverse the original problem was not solved in the end, we know that installing from scratch works, but if other users have this same problem we still don't know how to solve it. it's certainly related to DOM, but the installation looked ok. How can we make sure that Symfony configuration/prerequirements are ok?

**Comment by inverse** [comment]
The manual upgrade is a tough one to test personally as I've been primarily working with the dockerized app (which is also nice for discovering those dependency ones) 

We could have some preflight checks before doing the swap - the problem with that is that we will require users to first upgrade to a newer version which allows those hooks to be included.

**Comment by JF62** [comment]
Should I stay with the 'broken' version or can I fix my main server now by new installation? Do you need additional information?

**Comment by JF62** [comment]
> The manual upgrade is a tough one to test personally as I've been primarily working with the dockerized app (which is also nice for discovering those dependency ones)
> 
> We could have some preflight checks before doing the swap - the problem with that is that we will require users to first upgrade to a newer version which allows those hooks to be included.

A good and clear information with a warning before start maybe is enough

**Comment by inverse** [comment]
@JF62 Added some basic hook to test this that'll be in the next beta - it's nothing fancy but should suffice
