### ISSUE TITLE
No RSSI, version or Execution behind a Cloudflare Argo Tunnel and docker

### ISSUE THREAD

**Issue by sochartgit** [TasmoAdmin/TasmoAdmin#682]
## Expected Behavior
Get RSSI, version and execution filled after a few moments

## Current Behavior
Get an infinite animation on the devices page

## Possible Solution
Get that resolved

## Steps to Reproduce
1. Start a regular container with TA
2. Start another container using ArgoTunnel (works the same as reverse proxy)
3. Open the page from reverse address like  ta.domain.com/devices. It does not work
4. Open the page from private address like 192.168.X.X/devices:   It works

**Comment by sochartgit** [comment]
![image](https://user-images.githubusercontent.com/83184203/194726030-ca37fe9f-8501-4cd0-81c9-a7dd4941f60b.png)
![image](https://user-images.githubusercontent.com/83184203/194726038-b9aefe6a-84fd-449f-905e-9985e9eb5e82.png)

**Comment by inverse** [comment]
I'm unable to reproduce this - is there anything in the browser developer console? 

![image](https://user-images.githubusercontent.com/713525/194747618-eaebd22d-abf5-4be9-bdde-9ba8cf6577df.png)

**Comment by Gahanaho** [comment]
I have the them problem. My TA is in a vhost on the apache. Maybe there is a problem with the rewrite-rules.
I get no answer for this Get: "https://tasmoadmin.**********.***/node_modules/tablesaw/dist/stackonly/tablesaw.stackonly.jquery.js?_=v210" and others (Browser-Debugconsole)

**Comment by inverse** [comment]
@Gahanaho How did you upgrade? In v2.1.0 the whole asset pipeline was changed to leverage npm to ensure we have an easier upgrade path and CVE tracking.

We provide pre-baked releases to make things easier https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0

**Comment by Gahanaho** [comment]
OK, fine it works. The Selfupdate, that i used first, seems to generate the problem. I install TA new from the package and it works. Thank you

**Comment by inverse** [comment]
@sochartgit still experiencing issues?
