### ISSUE TITLE
Cannot upgrade from my own binary full firmware

### ISSUE THREAD

**Issue by DavidFW1960** [TasmoAdmin/TasmoAdmin#693]
## Expected Behavior

Previously until recently I could specify a firmware file for a full firmware and leave the minimal firmware field blank. 
## Current Behavior

Now if I do this I get a message:
"Minimal Firmware is not accessible on the server at http://10.90.11.100:9541/data/firmwares/
Please check the OTA IP address and port are correct"
## Possible Solution

For some reason it no longer allows minimal firmware to be skipped. My binaries are around 480kb and always used to update perfectly without minimal first. I can use the tasmota web interface to just upload the full firmware with no issues
## Steps to Reproduce

1. Select Update from devices menu
2. Navigate to select the full firmware file
3.Click next
4.

## Context (Environment)

Via a Home Assistant Addon
## Context (Device)

All sonoff and nodemcu's I have. All recent Tasmo admin version 2.1 of the addon
## Detailed Description

as above. I want to just be able to skip minimal firmware

**Comment by inverse** [comment]
I created a PR to address this but it might be a while before it's in the Home Assistant addon.

#633 discusses the removal of the minimal logic since it's not actually wired up in the JS OTA logic anymore for a few years now.

**Comment by DavidFW1960** [comment]
I think it will need to be in a Tasmoadmin release before the addon will be updated
