### ISSUE TITLE
List View Devices Are Getting Mixed Up and Duplicated

### ISSUE THREAD

**Issue by trichromic-ab** [TasmoAdmin/TasmoAdmin#700]
The list view seems to be getting corrupted so that the device lines are not showing the correct information for the device, there are duplications and the wrong device can be switched in error.
This is quite repeatable but I'm not sure the exact behaviour going on here. I believe its something to do with the position number being corrupted or implemented incorrectly.

## Expected Behavior

- The Version, Runtime and Energy values should be shown against the correct device.
- When selecting on/off switch, only the one correct device should be switched.
- When opening the Config, the correct device details should be opened for editing.
- When deleting a device, only the one correct device should be deleted and any subsequent device's position numbers should be decremented to take up the gap
- When adding a device, the position number should define where in the list the device is inserted and any subsequent devices position numbers should increment to make space.

## Current Behavior

- The List view and Detail view are unreliable because the row entries do not always correspond to the device named.
- The Version, Runtime and Energy values can sometimes be duplicated from a row above.
- The switch can switch another device
- The Config icon can open the configuration from the wrong device
- When adding a device, the position number given seems to be changed or ignored
- Multiple devices can have the same position number, as shown when opening Edit.

## Possible Solution
Investigation into the way position numbers are assigned to devices and how they are then used for the list view display.

## Steps to Reproduce

Sorry its difficult to pin down to specific steps because the exact pattern of behaviour isn't clear.
- In List view, add a device. Where it appears in the list may not be the bottom
- Click Config for a device and maybe the configuration shown is actually from another device.
- Click Edit for a device and the position number may be one already used by another device.
- Delete a device, sometimes 2 devices get deleted.
- Switch a device and maybe a different physical device actually switches

## Context (Environment)
TasmoAdmin add in on HA

## Context (Device)
Seems to be happening with all devices but I'm mainly using Athom with Tasmota 12.2.0.2

## Detailed Description
Provide a reliable means of determining which row each device is displayed according to position number.
Ensure that only properties for that one device are included in the grid row
Ensure that changing a device's position number is actually reflected in its display position.

**Comment by rdeserm** [comment]
I'm having this issue too

**Comment by inverse** [comment]
There was a bug with the ID generation  when devices were removed which will be fixed in the next release.

Unfortunately this will take some time to get to the Home Assistant addon
