### ISSUE TITLE
Provide multi-device delete

### ISSUE THREAD

**Issue by trichromic-ab** [TasmoAdmin/TasmoAdmin#701]
Please prodice a means of selecting multiple devices and then deleting.
Its very tedious to have to work through a a lot of clicks to delete a bunch of devices one by one.

## What should we implement
Maybe a checkbox to the left of each device row in List view to select multiple devices and a "Delete Selected" button.

**Comment by chapiosh** [comment]
+1

**Comment by inverse** [comment]
Added support in https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v3.2.0-beta.1
