### ISSUE TITLE
Docker didnt start up

### ISSUE THREAD

**Issue by nocomment-bln** [TasmoAdmin/TasmoAdmin#703]
hi guys

I used: **docker run -d -p 8811:80 -v /home/docker/tasmoadmin:/data [ghcr.io/tasmoadmin/tasmoadmin:latest](http://ghcr.io/tasmoadmin/tasmoadmin:latest) --restart=unless-stopped --name tasmotaadmin**
to start it
but got:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 12-patches.sh: executing... 
[cont-init.d] 12-patches.sh: exited 0.
[cont-init.d] 13-persistent-data-nginx.sh: executing... 
Symlinking /etc/nginx.conf to persistent storage location...
[cont-init.d] 13-persistent-data-nginx.sh: exited 0.
[cont-init.d] 14-nginx-ssl.sh: executing... 
[cont-init.d] 14-nginx-ssl.sh: exited 0.
[cont-init.d] 15-docker-environment.sh: executing... 
Docker env does not exist, doing that now...
[cont-init.d] 15-docker-environment.sh: exited 0.
[cont-init.d] 16-persistent-data-tasmoadmin.sh: executing... 
Symlinking /data/tasmoadmin directory to persistent storage location...
[cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec --name: No such file or directory
[cmd] --name exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 12-patches.sh: executing... 
[cont-init.d] 12-patches.sh: exited 0.
[cont-init.d] 13-persistent-data-nginx.sh: executing... 
Symlinking /etc/nginx.conf to persistent storage location...
[cont-init.d] 13-persistent-data-nginx.sh: exited 0.
[cont-init.d] 14-nginx-ssl.sh: executing... 
[cont-init.d] 14-nginx-ssl.sh: exited 0.
[cont-init.d] 15-docker-environment.sh: executing... 
[cont-init.d] 15-docker-environment.sh: exited 0.
[cont-init.d] 16-persistent-data-tasmoadmin.sh: executing... 
Symlinking /data/tasmoadmin directory to persistent storage location...
[cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec --name: No such file or directory
[cmd] --name exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by inverse** [comment]
The problem looks to be with the command you're running. The image should be the last command unless you plan on overriding the command that's actually executed within the docker container.

Running something like this should work

```
docker run -d -p 8811:80 -v /home/docker/tasmoadmin:/data  --restart=unless-stopped --name tasmotaadmin ghcr.io/tasmoadmin/tasmoadmin:latest
```

**Comment by nocomment-bln** [comment]
Thanks Von meinem iPhone gesendetAm 12.11.2022 um 22:30 schrieb Malachi Soord ***@***.***>:﻿
The problem looks to be with the command you're running. The image should be the last command unless you plan on overriding the command that's actually executed within the docker container.
Running something like this should work
docker run -d -p 8811:80 -v /home/docker/tasmoadmin:/data  --restart=unless-stopped --name tasmotaadmin ghcr.io/tasmoadmin/tasmoadmin:latest
