### ISSUE TITLE
How can I update TasmoAdmin in a synology docker container

### ISSUE THREAD

**Issue by radebold** [TasmoAdmin/TasmoAdmin#707]
Can any of you explain it to me, how I can update Tasmoadmin in a docker container?

**Comment by inverse** [comment]
Not familiar with running Docker on Synology - how did you currently setup Tasmoadmin on there?

**Comment by joka222** [comment]
make sure that you set persistent paths before!

delete container

reinstall new version

Tasmoadmin - Install TasmoAdmin on a Synology NAS running Docker
----------------------------------------------------------------
Docker UI (Synology): Login to DSM Go To Docker -> Registry Add https://ghcr.io/ (will end in an error but the image will appear in the Synology Docker app later and it even recognizes the registry (https://ghcr.io/))
Terminal: SSH login to DSM
--------------------------
sudo -i docker pull ghcr.io/tasmoadmin/tasmoadmin:latest
Docker UI (Synology): Login to DSM Go to Docker -> image/launch Advanced Settings Enable auto-restart set Local Ports (not automatic) Volume -> persistent path

create new container

set persistent paths:
docker/tasmoadmin  /data

set ports

**Comment by inverse** [comment]
Thanks @joka222 perhaps we could take these and put them on the WIKI

See: https://github.com/TasmoAdmin/TasmoAdmin/wiki
