### ISSUE TITLE
Send tasmota commands to all devices

### ISSUE THREAD

**Issue by SOliver78** [TasmoAdmin/TasmoAdmin#714]
Is its possible, to add console commands to all selected devices in one step?

Eg to send "Backlog PowerOnState 3; Sleep 0; WifiConfig 5;" to all devices.

**Comment by inverse** [comment]
You can already send single commands to all devices.


![image](https://user-images.githubusercontent.com/713525/203410832-18326ccc-369d-468a-8d97-aa55bd0e6787.png)

**Comment by SOliver78** [comment]
Oh sorry, this is exactly what I was looking for, multiple commands also work with it ;)

**Comment by inverse** [comment]
Interesting so you can chain commands like you described?

**Comment by SOliver78** [comment]
Yes, it works well.

**Comment by inverse** [comment]
Nice - didnt know that!
