### ISSUE TITLE
Support ESPurna

### ISSUE THREAD

**Issue by reloxx13** [TasmoAdmin/TasmoAdmin#72]
Support ESPurna with RestAPI

- radios to select tasmota or espurna
- save type in csv (dont forget to migrate already added devices)

additional if possible:
- diffrent config pages

**Comment by seetendra** [comment]
Yes this would be good since lot of users have a mix of both the devices

**Comment by seetendra** [comment]
If possible can we see the Power Usage information when clicked on a Sonoff POW.

**Comment by seetendra** [comment]
Any update on this?

**Comment by inverse** [comment]
Closing as out of scope unless someone wants to implement this..
