### ISSUE TITLE
Custom Firmware

### ISSUE THREAD

**Issue by Kedryn** [TasmoAdmin/TasmoAdmin#725]
I didn't find any way, with TasmoAdmin, to update a custom built firmware massively.
It could be nice to select a custom firmware and upload it to all devices, using old->minimal->new path.

**Comment by inverse** [comment]
![image](https://user-images.githubusercontent.com/713525/219496423-5805ec1c-fbc9-4bc5-9e85-94c8203210b8.png)


You should be able to upload the default minimal + custom and click next - does that not work?
