### ISSUE TITLE
Aktualisierungsrate

### ISSUE THREAD

**Issue by mafrei2019** [TasmoAdmin/TasmoAdmin#726]
Seit einigen Version wird, beim Auschalten eines Geätes, diese Zustandsänderung in TasmoAdmin nicht mehr angezeigt. Das Anzeigen bei ON ist OK geht das Gerät auf OFF bleibt ON stehen. Wenn der Broswer aktualisiert wird stimmt es wieder. Mehrere Browser zeigen das gleiche Verhalten.
Ich habe von Standard Aktualiserungsrate von 8 Sekunden auf 5 reduziert, ohne Erfolg

**Comment by slimline33** [comment]
Ich kann diesen Fehler bestätigen! Ist bei mir auch schon länger so... :)

**Comment by mafrei2019** [comment]
Problem besteht noch immer auch in Version 2.4.0 (Variannte Docker)

**Comment by inverse** [comment]
@mafrei2019 sorry for the delay in getting to this issue.

I managed to reproduce it locally and it seems like the toggling off worked but going back on didn't

I just pushed  change to master which has the fix in. Could you verify things are working correct at your end on the dev build? (`ghcr.io/tasmoadmin/tasmoadmin:dev`)

**Comment by mafrei2019** [comment]
Hi, version x:dev is OK, thanks

Problem fixed and can be closed

(Issue #726)

 

Von: Malachi Soord ***@***.*** 
Gesendet: 10 Februar 2023 23:32
An: TasmoAdmin/TasmoAdmin
Cc: mafrei2019; Mention
Betreff: Re: [TasmoAdmin/TasmoAdmin] Aktualisierungsrate (Issue #726)

 

@mafrei2019 <https://github.com/mafrei2019>  sorry for the delay in getting to this issue.

I managed to reproduce it locally and it seems like the toggling off worked but going back on didn't

I just pushed change to master which has the fix in. Could you verify things are working correct at your end on the dev build? (ghcr.io/tasmoadmin/tasmoadmin:dev)

**Comment by inverse** [comment]
Published version https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.4.1
