### ISSUE TITLE
mistake Error add Device

### ISSUE THREAD

**Issue by DRIOB** [TasmoAdmin/TasmoAdmin#727]
Hello, i wanted to add a device and i get this message.

[1.pdf](https://github.com/TasmoAdmin/TasmoAdmin/files/10202526/1.pdf)

Please help.

Thanks

**Comment by inverse** [comment]
Sounds like there is some formatting issue with the response back from the device?

How did you this error? We def need to improve reporting these issues as it's not clear from what's provided.

What's the return of calling this on your device? It should mimic what TasmoAdmin does to get status informaiton.

http://<ip>/cm?user=admin&password=password&cmnd=Status%200

**Comment by DRIOB** [comment]
Hello,

 

i get this:

 

SyntaxError: JSON.parse: bad control character in string literal at line 1 column 115 of the JSON data

 

{"Status":{"Module":0,"DeviceName":"SonoffDRNr4-NetAtmo","FriendlyName":["SonoffDRNr4-NetAtmo"],"Topic":"266pic�������T","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":0,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"sonoffs","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota-DE.bin","RestartReason":"Software/System restart","Uptime":"8T00:02:17","StartupUTC":"2022-12-11T15:53:31","Sleep":50,"CfgHolder":4617,"BootCount":89,"BCResetTime":"2020-06-18T19:43:52","SaveCount":556,"SaveAddress":"FA000"},"StatusFWR":{"Version":"12.2.0(tasmota)","BuildDateTime":"2022.10.17 08:43:02","Boot":7,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"434/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["FBFR","FBFR Gastzugang"],"TelePeriod":10,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A002800000000","00000080","00006000","00004000","00000000"]},"StatusMEM":{"ProgramSize":627,"Free":376,"Heap":20,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000407","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"xtopic--6373","IPAddress":"192.168.178.214","Gateway":"192.168.178.111","Subnetmask":"255.255.255.0","DNSServer1":"192.168.178.111","DNSServer2":"0.0.0.0","Mac":"24:62:AB:2F:98:E5","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.178.124","MqttPort":1883,"MqttClientMask":"SonoffDRNr4-NetAtmo","MqttClient":"SonoffDRNr4-NetAtmo","MqttUser":"admindr","MqttCount":7,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4},"StatusTIM":{"UTC":"2022-12-19T15:55:48","Local":"2022-12-19T16:55:48","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"08:39","Sunset":"16:54"},"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0},"StatusSNS":{"Time":"2022-12-19T16:55:48","ENERGY":{"TotalStartTime":"2019-12-01T17:37:24","Total":0.815,"Yesterday":0.004,"Today":0.003,"Power":0,"ApparentPower":5,"ReactivePower":5,"Factor":0.04,"Voltage":239,"Current":0.019}},"StatusSTS":{"Time":"2022-12-19T16:55:48","Uptime":"8T00:02:17","UptimeSec":691337,"Heap":20,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":7,"POWER":"ON","Wifi":{"AP":1,"SSId":"FBFR","BSSId":"44:4E:6D:D1:A6:B9","Channel":13,"Mode":"11n","RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:03"}}}

 

Accept-Ranges: none

Cache-Control: no-cache, no-store, must-revalidate

Connection: close

Content-Type: application/json

Expires: -1

Pragma: no-cache

Server: Tasmota/12.2.0 (ESP8285)

Transfer-Encoding: chunked

 

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8

Accept-Encoding: gzip, deflate

Accept-Language: de,en-US;q=0.7,en;q=0.3

Authorization: Basic YWRtaW46MjIwMQ==

Connection: keep-alive

Host: 192.168.178.214

Upgrade-Insecure-Requests: 1

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0

 

Von: Malachi Soord ***@***.***> 
Gesendet: Sonntag, 18. Dezember 2022 22:41
An: TasmoAdmin/TasmoAdmin ***@***.***>
Cc: DRIOB ***@***.***>; Author ***@***.***>
Betreff: Re: [TasmoAdmin/TasmoAdmin] mistake Error add Device (Issue #727)

 

Sounds like there is some formatting issue with the response back from the device?

How did you this error? We def need to improve reporting these issues as it's not clear from what's provided.

What's the return of calling this on your device? It should mimic what TasmoAdmin does to get status informaiton.

http:///cm?user=admin <http://cm?user=admin&password=password&cmnd=Status%200> &password=password&cmnd=Status%200

**Comment by inverse** [comment]
It looks like it's an issue with the MQTT topic containing characters that it's unable to decode.

![image](https://user-images.githubusercontent.com/713525/209005021-9ca5acfb-1d62-4bbc-afa9-0144fac57126.png)


For me this is being rendered like above.

**Comment by inverse** [comment]
Any luck with the issue?
