### ISSUE TITLE
Having issues with login when connected to home assistant docker

### ISSUE THREAD

**Issue by carefulcomputer** [TasmoAdmin/TasmoAdmin#737]
My tasmoadmin docker image is working fine and I am able to login when I directly hit the login page of tasmoadmin from browser.
However, when i try to access it from my home assistant (added a left nav button) , I am not able to logic. In network tab I see that after I submit the login information, it tries to fetch '/devices' page but that redirects back to login page. This behavior is not shown when I directly load the tasmoadmin page.

## Context (Environment)

TasmoAdmin and home assistants are both running in docker

**Comment by inverse** [comment]
Could be related to https://github.com/hassio-addons/addon-tasmoadmin/issues/125

**Comment by carefulcomputer** [comment]
Yes! That was exactly the issue. IP address vs host name. After matching them up it worked fine.
Meanwhile I am wondering if it is limitation of platform ? or can it be fixed with a nginx config (i.e. allow iframe logins with either hostname or ip address)? If we could access it either way, then it would be nice.

**Comment by inverse** [comment]
Glad that fixed it - You'll need toask on the hassio-addon as AFAIK requires changing the nginx configuration there.

**Comment by carefulcomputer** [comment]
i am using tasmoadmin in docker container (not HAAS addon) so it is manual integration. I have other apps running in docker too (node-red/portainer etc). They all connect fine with either IP or hostname. Only tasmoadmin requires the name to match with ip. So something specific in tasmoadmin is causing this issue.

**Comment by inverse** [comment]
Ahh okays - I'm not sure what security feature is causing this to happen. There aren't any particular headers being sent to restrict this.

Also it seems to be only in Chrome - I can't reproduce it in Firefox.

**Comment by carefulcomputer** [comment]
Has to be something related to cookies/login functionality since login itself page loads fine initially, it is after login which doesn't like the difference in URL vs IP address.

**Comment by inverse** [comment]
Correct - seems like a security feature that Chrome mandates to probably prevent the frame hijacking things.

**Comment by carefulcomputer** [comment]
but it works fine on other integrations.  so my guess is some setting in nginx (maybe some default setting) which rewrites the url and redirect the user to login page if hostname doesn't match.

**Comment by inverse** [comment]
What other integrations are working?

**Comment by carefulcomputer** [comment]
node-red, code-server , portainer etc.
