### ISSUE TITLE
mDNS naming or other non-static addressing

### ISSUE THREAD

**Issue by Gamerayers** [TasmoAdmin/TasmoAdmin#739]
With MQTT setup for tasmota and all the methods to communicate, the only thing that requires a static IP configuration on my network is actually the TasmoAdmin.  If it could use mDNS naming or something like GuestNightStand.local, it would be helpful so that I don't have to statically assign EVERYTHING on my network.
I think others would benefit from this too.

**Comment by jbardi** [comment]
Agreed. My router has limited memory storage and I cannot afford to give all my 40 devices static IP addresses. I am constantly having to re-scan for devices as the IP addresses change on the network and tasmoadmin thinks they are now offline. I've started using tasmoadmin less and less for this exact reason.

**Comment by Gamerayers** [comment]
This works. Just need to type in the full dns name. It can be closed. I am however moving to ESPHome due to the better setup and linkage with the new beken chips.

Ie. For me I just set it as smart_bulb.local and it worked.
