### ISSUE TITLE
Liste in Dauerschleife 

### ISSUE THREAD

**Issue by mymeyer** [TasmoAdmin/TasmoAdmin#751]
Hallo , 
habe die aktuelle Version 2.2 installiert. Sobald ich mich einlogge sehe ich die Liste meiner Geräte , aber die Seite läuft in einer Dauerschleife. Siehe Anhang. Wo kann ich nach dem Fehler suchen ?

![image](https://user-images.githubusercontent.com/44463914/211625429-1564c7c1-b247-4fa1-9a21-818882aa2fb8.png)

MyMeyer

**Comment by inverse** [comment]
How are you running TasmoAdmin?  

Was it ever working or is this a fresh install?

Does http://<ip>:<port>/index.php?doAjaxAll return any errors?

**Comment by inverse** [comment]
Sorry there was a formatting bug. Could you visit `/index.php?doAjaxAll` on the host that is running TasmoAdmin

**Comment by mymeyer** [comment]
> Entschuldigung, es gab einen Formatierungsfehler. Könnten Sie den Host besuchen, `/index.php?doAjaxAll`auf dem TasmoAdmin ausgeführt wird

See image:
![image](https://user-images.githubusercontent.com/44463914/211913746-b36cb7e3-1766-47f0-bee5-dfc96455a35f.png)

**Comment by inverse** [comment]
Interesting it should yield JSON.

How is it setup? What web server are you using? What configuration for the host? 

![image](https://user-images.githubusercontent.com/713525/211914688-5d5015cb-6857-42bb-8fee-bf53d589224b.png)

**Comment by inverse** [comment]
Perhaps even calling `/doAjaxAll` would work depending on your webserver settings

**Comment by mymeyer** [comment]
> /index.php?doAjaxAll

Hi,
This is how it looks now. Web server is APACHE2. 
I went according to the instructions.

https://forum.smartapfel.de/forum/thread/3019-tasmoadmin-tasmota-verwalten-f%C3%BCr-faule/

![image](https://user-images.githubusercontent.com/44463914/212138327-5a52f075-f662-4e0f-b667-2f935825fc53.png)

**Comment by mymeyer** [comment]
Hi, reinstalled everything and now it works.

**Comment by inverse** [comment]
We have a guide for bare metal installs - Perhaps folks should reference that instead? 

https://github.com/TasmoAdmin/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04


Although it's using a somewhat out of date PHP + distro :/ Happy to have contributions if it makes it easier for others.

Glad it worked out :pray:
