### ISSUE TITLE
Backup does not work when there is a slash character in the device name

### ISSUE THREAD

**Issue by SnDsound** [TasmoAdmin/TasmoAdmin#776]
Backup does not work when there is a slash character in the device name.
For example I've device named "Salon/Gniazdko/TV"

## Expected Behavior
Unsupported characters should be replaced by "_" or other, supported character.

## Current Behavior
"/" is treated as folder separator in a path. Backup mechanism is trying to create "TV.dmp" file in "backups/1-Salon/Gniazdko" path.

Fatal error: Uncaught RuntimeException: Directory /var/www/tasmoadmin/tmp/backups/1-Salon/Gniazdko does not exist for sink value of /var/www/tasmoadmin/tmp/backups/1-Salon/Gniazdko/TV.dmp

## Possible Solution
Replace unsupported characters like "/"  by "_" or other.

## Steps to Reproduce

1. Use "/" character in device name
2. Try to do a backup

## Context (Environment)
- v.2.4.1
- Dockerised

**Comment by inverse** [comment]
Thanks for the report! I've pushed a fix which will be in the next beta for `3.0.0` if you're already running dockerized setup there shouldn't be any issues upgrading - it's a major bump as the PHP + web-server config needed changing.

**Comment by inverse** [comment]
https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v3.0.0-beta.5

**Comment by SnDsound** [comment]
Problem solved. Thanks for fast response! 👍
