### ISSUE TITLE
3.0.0 Beta1 shows no Data from devices

### ISSUE THREAD

**Issue by Joylancer** [TasmoAdmin/TasmoAdmin#787]
## Current Behavior

![grafik](https://user-images.githubusercontent.com/99641044/219868482-ecdee847-5719-49c8-896f-3cab028db682.png)
PHP 8.2 is installed and active
and under Settings show Message: (also in stable version)
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/tasmoadmin_test/tasmoadmin/src/Helper/TasmotaHelper.php on line 115

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

PHP 8.2
Raspi Bullseye, Apache2
Tasmoadmin v3.0.0-beta.1

**Comment by inverse** [comment]
Should be fixed in https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v3.0.0-beta.2

**Comment by Joylancer** [comment]
Hi,
sorry, after Update shows no devicedata
Beta-2

deleted cache and myconfig.json and devices.csv

add new module, shows no data

***@***.***

***@***.***

You need addintional infos?

Version 2.4.x running without problems

***@***.***





Update:
when i open the website shows:


***@***.***

then go to device page
shows no data from devices
go back to start-page
shows always no data
***@***.***


Von: Malachi Soord ***@***.***>
Gesendet: Sonntag, 19. Februar 2023 22:09
An: TasmoAdmin/TasmoAdmin ***@***.***>
Cc: Joylancer ***@***.***>; Author ***@***.***>
Betreff: Re: [TasmoAdmin/TasmoAdmin] 3.0.0 Beta1 shows no Data from devices (Issue #787)


Should be fixed in https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v3.0.0-beta.2<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTasmoAdmin%2FTasmoAdmin%2Freleases%2Ftag%2Fv3.0.0-beta.2&data=05%7C01%7C%7Cbb026396cb544394c07408db12bd8f8d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638124377581297063%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a9pENUrLC4Hexu%2BK5rIwX7kT%2B6v002QXOOhhfQ0Sbn4%3D&reserved=0>

-

**Comment by inverse** [comment]
Sounds like an issue with the ajax request to get status infomation.

Does calling `/devices?doAjaxAll` produce any errors?

**Comment by Joylancer** [comment]
No Errors, same Problem
tested with Firefox, Chrom and Opera

Von: Malachi ***@***.***>
Gesendet: Sonntag, 19. Februar 2023 22:40
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [TasmoAdmin/TasmoAdmin] 3.0.0 Beta1 shows no Data from devices (Issue #787)


Sounds like an issue with the ajax request to get status infomation.

Does calling /devices?doAjaxAll produce any errors?

**Comment by inverse** [comment]
any errors in the developer console of the browser? how did you configure your server? 

there was some changes with 3 with how routing is done but for apache it should be solved with the provided htaccess file.

**Comment by Joylancer** [comment]
Compare both .htaccess files, no difference (2.4.2 and 3.0.x beta2)
developer console shows:

***@***.***

***@***.***
Von: Malachi Soord ***@***.***>
Gesendet: Sonntag, 19. Februar 2023 22:54
An: TasmoAdmin/TasmoAdmin ***@***.***>
Cc: Joylancer ***@***.***>; Author ***@***.***>
Betreff: Re: [TasmoAdmin/TasmoAdmin] 3.0.0 Beta1 shows no Data from devices (Issue #787)


any errors in the developer console of the browser? how did you configure your server?

there was some changes with 3 with how routing is done but for apache it should be solved with the provided htaccess file.

-

**Comment by Joylancer** [comment]
[LIST][updateAllStatus][1][ERROR] DATA => undefined 2 devices.js:388:28

Von: Malachi Soord ***@***.***>
Gesendet: Sonntag, 19. Februar 2023 22:54
An: TasmoAdmin/TasmoAdmin ***@***.***>
Cc: Joylancer ***@***.***>; Author ***@***.***>
Betreff: Re: [TasmoAdmin/TasmoAdmin] 3.0.0 Beta1 shows no Data from devices (Issue #787)


any errors in the developer console of the browser? how did you configure your server?

there was some changes with 3 with how routing is done but for apache it should be solved with the provided htaccess file.

-

**Comment by inverse** [comment]
Are the requests in the network tab all fine? 

Sounds like something is wrong with the ajax request to update state.

**Comment by Joylancer** [comment]
All ok,
no Errors,
***@***.***

Von: Malachi ***@***.***>
Gesendet: Montag, 20. Februar 2023 09:38
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [TasmoAdmin/TasmoAdmin] 3.0.0 Beta1 shows no Data from devices (Issue #787)


Are the requests in the network tab all fine?

Sounds like something is wrong with the ajax request to update state.

**Comment by Joylancer** [comment]
*   how did you configure your server?

PHP Version 8.2.3

System
Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64
Build Date
Feb 14 2023 16:53:07
Build System
Linux
Server API
Apache 2.0 Handler
Virtual Directory Support
disabled
Configuration File (php.ini) Path
/etc/php/8.2/apache2
Loaded Configuration File
/etc/php/8.2/apache2/php.ini
Scan this dir for additional .ini files
/etc/php/8.2/apache2/conf.d
Additional .ini files parsed
/etc/php/8.2/apache2/conf.d/10-mysqlnd.ini, /etc/php/8.2/apache2/conf.d/10-pdo.ini, /etc/php/8.2/apache2/conf.d/15-xml.ini, /etc/php/8.2/apache2/conf.d/20-bz2.ini, /etc/php/8.2/apache2/conf.d/20-calendar.ini, /etc/php/8.2/apache2/conf.d/20-ctype.ini, /etc/php/8.2/apache2/conf.d/20-curl.ini, /etc/php/8.2/apache2/conf.d/20-dom.ini, /etc/php/8.2/apache2/conf.d/20-exif.ini, /etc/php/8.2/apache2/conf.d/20-ffi.ini, /etc/php/8.2/apache2/conf.d/20-fileinfo.ini, /etc/php/8.2/apache2/conf.d/20-ftp.ini, /etc/php/8.2/apache2/conf.d/20-gd.ini, /etc/php/8.2/apache2/conf.d/20-gettext.ini, /etc/php/8.2/apache2/conf.d/20-iconv.ini, /etc/php/8.2/apache2/conf.d/20-intl.ini, /etc/php/8.2/apache2/conf.d/20-mbstring.ini, /etc/php/8.2/apache2/conf.d/20-mysqli.ini, /etc/php/8.2/apache2/conf.d/20-pdo_mysql.ini, /etc/php/8.2/apache2/conf.d/20-pdo_sqlite.ini, /etc/php/8.2/apache2/conf.d/20-phar.ini, /etc/php/8.2/apache2/conf.d/20-posix.ini, /etc/php/8.2/apache2/conf.d/20-readline.ini, /etc/php/8.2/apache2/conf.d/20-shmop.ini, /etc/php/8.2/apache2/conf.d/20-simplexml.ini, /etc/php/8.2/apache2/conf.d/20-sockets.ini, /etc/php/8.2/apache2/conf.d/20-sqlite3.ini, /etc/php/8.2/apache2/conf.d/20-sysvmsg.ini, /etc/php/8.2/apache2/conf.d/20-sysvsem.ini, /etc/php/8.2/apache2/conf.d/20-sysvshm.ini, /etc/php/8.2/apache2/conf.d/20-tokenizer.ini, /etc/php/8.2/apache2/conf.d/20-xmlreader.ini, /etc/php/8.2/apache2/conf.d/20-xmlwriter.ini, /etc/php/8.2/apache2/conf.d/20-xsl.ini, /etc/php/8.2/apache2/conf.d/20-zip.ini
PHP API
20220829
PHP Extension
20220829
Zend Extension
420220829
Zend Extension Build
API420220829,NTS
PHP Extension Build
API20220829,NTS
Debug Build
no
Thread Safety
disabled
Zend Signal Handling
enabled
Zend Memory Manager
enabled
Zend Multibyte Support
provided by mbstring
IPv6 Support
enabled
DTrace Support
disabled
Registered PHP Streams
https, ftps, compress.zlib, php, file, glob, data, http, ftp, compress.bzip2, phar, zip
Registered Stream Socket Transports
tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters
zlib.*, string.rot13, string.toupper, string.tolower, convert.*, consumed, dechunk, bzip2.*, convert.iconv.*

***@***.***<http://www.zend.com/>This program makes use of the Zend Scripting Language Engine:
Zend Engine v4.2.3, Copyright (c) Zend Technologies

Configuration
apache2handler<http://192.168.178.100:9998/info.php#module_apache2handler>
Apache Version
Apache/2.4.54 (Debian)
Apache API Version
20120211
Server Administrator
***@***.***
Hostname:Port
tasmoadmin_test:0
User/Group
www-data(33)/33
Max Requests
Per Child: 0 - Keep Alive: on - Max Per Connection: 100
Timeouts
Connection: 300 - Keep-Alive: 5
Virtual Server
Yes
Server Root
/etc/apache2
Loaded Modules
core mod_so mod_watchdog http_core mod_log_config mod_logio mod_version mod_unixd mod_access_compat mod_alias mod_auth_basic mod_authn_core mod_authn_file mod_authz_core mod_authz_host mod_authz_user mod_autoindex mod_deflate mod_dir mod_env mod_filter mod_mime prefork mod_negotiation mod_php mod_reqtimeout mod_rewrite mod_setenvif mod_status

Directive
Local Value
Master Value
engine
On
On
last_modified
Off
Off
xbithack
Off
Off
Apache Environment
Variable
Value
SUFFIX
info.php
BASE
/
HTTP_HOST
192.168.178.100:9998
HTTP_USER_AGENT
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
HTTP_ACCEPT
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
HTTP_ACCEPT_LANGUAGE
de
HTTP_ACCEPT_ENCODING
gzip, deflate
HTTP_DNT
1
HTTP_CONNECTION
keep-alive
HTTP_COOKIE
TASMO_SESSION=hdn7pnsuhfgol4egamveohhepk; session-id=133-1949661-7250829; session-id-time=2298906552l; csm-hit=tb:9H6PZQR775R4EZJBRT1X+s-SZEEDS2JBEHPQ6AT3DD5|1668186534288&t:1668186534288&adb:adblk_no; ubid-main=134-3441445-8248042; session-token=5NEreqyCMxkL454EKZnMtskZJ+VxgTMsHhkkIyeolQd1qNNsDLxZaX9mMPxKPPtm7Uwig0Mkg0wVAsvrn7lbC6cvqWXiYnxjMBciF38a5PH2wgS8/0EawHZvXG8LwUXpPALZ8Zj2KuYSbZ6E9gEC4aLMpXy2cSxdNSRyElCqueL952Q8DgDqO256oxNZX4Kb0CXCgNOoygZq/kYBf317tQNkytJCpLHAYxkobPOBtSgsi0/Z3hSDg2qQOtyPrskC; sid="lvaz3pivqD/Sc5g0/T9RrQ==|49SZCFjbnscaWFxraq7Jjlv/alC0ppZWN3IbA343YMM="; x-main=zw5Nl03thzy9h7bvjNHFjVgXMtZj3j1Z; at-main=Atza|IwEBIMimLhujmDxmrTNeDJdKjyTfmJaF6KtudEWjicABDDZUbct8WWRqWNvCka-djH3awF_s2YEk4Zd-nUYo7GCvhWzOS0d30JWyC_zNfA_JIxw7oW6zOTiBkSWYbw1aoLy1eSo1URryotSVzUxw9eqIrdK3ini7V8XUFVQEHAfjWNdu6DfwI5qy2_-TSdLq2D5U6Ynis2tRqpb2XWUW0Y5gtAOI4JYz8-JJD-xk8t_G9W8hb-T-Q5wkPrhvLjTfGIfxRJ4dORJWB3ZM0YOPqEB7ywbHR5bXR8pCXBDeNnXWEhM46w; sess-at-main="htp+A8toc9g+87+6H/Cw/t7hINoKqGw4/P4CQjp3Pq8="
HTTP_UPGRADE_INSECURE_REQUESTS
1
HTTP_PRAGMA
no-cache
HTTP_CACHE_CONTROL
no-cache
PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVER_SIGNATURE
<address>Apache/2.4.54 (Debian) Server at 192.168.178.100 Port 9998</address>
SERVER_SOFTWARE
Apache/2.4.54 (Debian)
SERVER_NAME
192.168.178.100
SERVER_ADDR
192.168.178.100
SERVER_PORT
9998
REMOTE_ADDR
192.168.178.52
DOCUMENT_ROOT
/var/www/html/tasmoadmin_test/tasmoadmin
REQUEST_SCHEME
http
CONTEXT_PREFIX
no value
CONTEXT_DOCUMENT_ROOT
/var/www/html/tasmoadmin_test/tasmoadmin
SERVER_ADMIN
***@***.***
SCRIPT_FILENAME
/var/www/html/tasmoadmin_test/tasmoadmin/info.php
REMOTE_PORT
55118
GATEWAY_INTERFACE
CGI/1.1
SERVER_PROTOCOL
HTTP/1.1
REQUEST_METHOD
GET
QUERY_STRING
no value
REQUEST_URI
/info.php
SCRIPT_NAME
/info.php
HTTP Headers Information
HTTP Request Headers
HTTP Request
GET /info.php HTTP/1.1
Host
192.168.178.100:9998
User-Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
Accept
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language
de
Accept-Encoding
gzip, deflate
DNT
1
Connection
keep-alive
Cookie
TASMO_SESSION=hdn7pnsuhfgol4egamveohhepk; session-id=133-1949661-7250829; session-id-time=2298906552l; csm-hit=tb:9H6PZQR775R4EZJBRT1X+s-SZEEDS2JBEHPQ6AT3DD5|1668186534288&t:1668186534288&adb:adblk_no; ubid-main=134-3441445-8248042; session-token=5NEreqyCMxkL454EKZnMtskZJ+VxgTMsHhkkIyeolQd1qNNsDLxZaX9mMPxKPPtm7Uwig0Mkg0wVAsvrn7lbC6cvqWXiYnxjMBciF38a5PH2wgS8/0EawHZvXG8LwUXpPALZ8Zj2KuYSbZ6E9gEC4aLMpXy2cSxdNSRyElCqueL952Q8DgDqO256oxNZX4Kb0CXCgNOoygZq/kYBf317tQNkytJCpLHAYxkobPOBtSgsi0/Z3hSDg2qQOtyPrskC; sid="lvaz3pivqD/Sc5g0/T9RrQ==|49SZCFjbnscaWFxraq7Jjlv/alC0ppZWN3IbA343YMM="; x-main=zw5Nl03thzy9h7bvjNHFjVgXMtZj3j1Z; at-main=Atza|IwEBIMimLhujmDxmrTNeDJdKjyTfmJaF6KtudEWjicABDDZUbct8WWRqWNvCka-djH3awF_s2YEk4Zd-nUYo7GCvhWzOS0d30JWyC_zNfA_JIxw7oW6zOTiBkSWYbw1aoLy1eSo1URryotSVzUxw9eqIrdK3ini7V8XUFVQEHAfjWNdu6DfwI5qy2_-TSdLq2D5U6Ynis2tRqpb2XWUW0Y5gtAOI4JYz8-JJD-xk8t_G9W8hb-T-Q5wkPrhvLjTfGIfxRJ4dORJWB3ZM0YOPqEB7ywbHR5bXR8pCXBDeNnXWEhM46w; sess-at-main="htp+A8toc9g+87+6H/Cw/t7hINoKqGw4/P4CQjp3Pq8="
Upgrade-Insecure-Requests
1
Pragma
no-cache
Cache-Control
no-cache


Von: Malachi ***@***.***>
Gesendet: Sonntag, 19. Februar 2023 22:54
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [TasmoAdmin/TasmoAdmin] 3.0.0 Beta1 shows no Data from devices (Issue #787)


any errors in the developer console of the browser? how did you configure your server?

there was some changes with 3 with how routing is done but for apache it should be solved with the provided htaccess file.

**Comment by Joylancer** [comment]
Apache Access log:

Difference between 242 and 3xx-beta2

***@***.***

**Comment by davlaw** [comment]
Just a note to confirm that I have the same problem, it was working fine before pulling the trigger on the beta

I know this does not help much with a "me too" statement.

**Comment by inverse** [comment]
@davlaw are you on Apache too?

I think I forgot to include the required `.htaccess` that would make this work. Let me see if I can get a `dev` build working.

**Comment by inverse** [comment]
@Joylancer are you able to try this file in your repo? 

https://github.com/TasmoAdmin/TasmoAdmin/blob/master/tasmoadmin/.htaccess

**Comment by Joylancer** [comment]
Yes, it works

**Comment by Joylancer** [comment]
yes, now works fine but new bug found, i open new issue

**Comment by inverse** [comment]
Glad that fixed it :)
