### ISSUE TITLE
powermeter shows energy-yesterday instead of energytotal (php8.2)

### ISSUE THREAD

**Issue by Joylancer** [TasmoAdmin/TasmoAdmin#796]
or ist it: as designed

![grafik](https://user-images.githubusercontent.com/99641044/220504516-de4080f4-56fd-4718-b0c0-3e264d07524b.png)
![grafik](https://user-images.githubusercontent.com/99641044/220505077-a951e25c-6ffd-4f04-9e46-f44d782d4549.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by inverse** [comment]
That's by design and been that way for a long time. 

Has some overlap with #678 on how to make that section a bit more usable as you're right it might be nice to see this in more detail

**Comment by inverse** [comment]
![image](https://user-images.githubusercontent.com/713525/220766744-4f9167f6-0791-420e-bd17-336eab17d183.png)

Could do something like this to put `today / yesterday / total`
