### ISSUE TITLE
Traduction francaise inversé

### ISSUE THREAD

**Issue by AlainBRUNEL** [TasmoAdmin/TasmoAdmin#803]
Bonjour,
Les traductions des OPTION_2 et 3 de CONFIG_POWERONSTATE sont inversées dans la traduction francaise

**Comment by inverse** [comment]
Been thinking about improving the way translations are managed by the community. 

Before they have been ini files in this repo and was thinking of moving them to transifex.

Started working on it on #785

That way I could sync them down when folks modify them.

**Comment by inverse** [comment]
Are you able to see the translations on https://www.transifex.com/tasmoadmin/tasmoadmin/translate/#fr/lang/450743028

**Comment by AlainBRUNEL** [comment]
No I have a 404

Bien cordialement.

***@***.***
Alain BRUNEL
Château d'Arigès
48400 BEDOUES-COCURES
Tel : 06 74 71 29 83
***@***.******@***.***>


De : Malachi Soord ***@***.***>
Envoyé : dimanche 26 février 2023 11:15
À : TasmoAdmin/TasmoAdmin ***@***.***>
Cc : Alain BRUNEL ***@***.***>; Author ***@***.***>
Objet : Re: [TasmoAdmin/TasmoAdmin] Traduction francaise inversé (Issue #803)


Are you able to see the translations on https://www.transifex.com/tasmoadmin/tasmoadmin/translate/#fr/lang/450743028<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.transifex.com%2Ftasmoadmin%2Ftasmoadmin%2Ftranslate%2F%23fr%2Flang%2F450743028&data=05%7C01%7C%7Cf0281b4673104180719508db17e243de%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638130032787152563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mCfKAuN8tFDGvOYZYfxcn0%2FpQupx6PDU%2FrqlRcaDDwg%3D&reserved=0>

-

**Comment by AlainBRUNEL** [comment]
It's still relevant

**Comment by inverse** [comment]
@AlainBRUNEL would you be able to correct the translations on https://app.transifex.com/tasmoadmin/tasmoadmin/translate/#fr/lang/450743025 so I can sync them down?
