### ISSUE TITLE
Unable to access OTA URL for Update

### ISSUE THREAD

**Issue by Gosuwaldbear** [TasmoAdmin/TasmoAdmin#810]
I can't Update my Devices since Update to 2.4.x

## Expected Behavior
Update my Tasmota Devices

## Current Behavior
Unable to access OTA URL @ http://192.168.178.206:9999/data/firmwares/tasmota-DE.bin.gz - TypeError: Load failed

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
Debian 11
Tasmoadmin 3.0.0
PHP 8.2
Apache2

## Context (Device)
All Devices

## Detailed Description
Since the update to 2.4.1 or 2.4.2 I can no longer run the OTA update.

/var/www/html/tasmoadmin/data/firmwares
-rw-r--r-- 1 www-data www-data 454146 Mar  5 08:39 tasmota-DE.bin.gz
-rw-r--r-- 1 www-data www-data 265839 Mar  5 08:39 tasmota-minimal.bin.gz

**Comment by evanrich** [comment]
same here.  If i click the link it complains about, i can successfully download the firmware from the tasmoadmin link, but the webpage shows 

```
Full Firmware is not accessible on the server at https://10.10.2.18:443/data/firmwares/tasmota.bin.gz
Please check the OTA IP address and port are correct
```

**Comment by inverse** [comment]
There was some additional validation added to TasmoAdmin to check if the firmware is accessible to TasmoAdmin itself  from both the backend code and front-end JavaScript.

By default only the backend check is active.

![image](https://user-images.githubusercontent.com/713525/222957433-d0e2882c-6a99-48d4-aeb9-82a03f65b4c4.png)


@Gosuwaldbear looks like you're being blocked by the frontend one - are you able to download that file just fine from your browser? 

All we're doing with this is some HEAD request to the firmware - could you try disabling the FE check to see if that has any improvement?


@evanrich your warning is the same but for the backend check - where TasmoAdmin tries to make a head request to the URL internally - that seems strange that it's not working if you're able to download the file from your browser.

**Comment by Gosuwaldbear** [comment]
FE and BE Check was enabled. I can download the File from my browser without any Problems.
If I turned off the FE check, the OTA works fine.

Thx for the quick help

**Comment by inverse** [comment]
@Gosuwaldbear could be some CORS error which is why it failed :/

For nginx this was required https://github.com/TasmoAdmin/TasmoAdmin/blob/master/.docker/rootfs/etc/nginx/nginx.conf#L56

Not sure what the equivalent would be for Apache

**Comment by inverse** [comment]
```
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
</IfModule>
```

Could be adding something that to the `.htaccess` file within the firmware dir or setting it on the firmware folder in your apache config.

**Comment by evanrich** [comment]
@inverse  thanks man that fixed it for me!

**Comment by lobomau76** [comment]
I am new to TasmoAdmin. Everything went fine during installation until this step of OTA update.
It is running as a docker container on Synology. TasmoAdmin is reachabel over the same IP as the Synology.
Also strange .. I have tried the normal .bin and the bin.gz. After trying the update afterwards there are always bin.gz. files under data/firmwares.

![image](https://user-images.githubusercontent.com/35029301/236619202-37bb5143-acda-4e67-9ba1-d0f0717ca79e.png)

![image](https://user-images.githubusercontent.com/35029301/236619253-c97282d9-163c-473d-a702-8c44f0a5aee7.png)

**Comment by inverse** [comment]
@lobomau76 so it updates fine without backend check? Interesting - the backend check is just asserting if it can access the firmware from itself :/

**Comment by lobomau76** [comment]
It seems so. But only worked for the minimum firmware.

**Comment by inverse** [comment]
@lobomau76 There was a bug with the messaging - perhaps the backend was also failing for minimal too... It's fixed on master now.

Still odd that it was failing

**Comment by quadcom** [comment]
Just up and running with this and I am seeing this exact issue.

I am able to download the firmware from Github when backend is turned off. 

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/7085931/60a6f5b8-4a55-413f-951a-d51c8e4a7de3)

But starting the update and it fails with the same error message;

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/7085931/291ba7ff-5ac7-494f-a759-edbd063702d7)


What I noticed, and maybe it's nothing, is the URL is different that what is being shown in the message.

"/upload_form" vs "
