### ISSUE TITLE
File not found after upgrade to V3.0.0

### ISSUE THREAD

**Issue by bobybobybob** [TasmoAdmin/TasmoAdmin#811]
## Expected Behavior
to see the TasoAdmin GUI

## Current Behavior
Portainer TasoAdmin Update to 3.0.0 show after enter the IP =>   IP:3004/login   and a blank website with text "File not found."

**Comment by inverse** [comment]
What volume(s) do you have mounted to the container? I've heard that if you mount `/data` this also includes the nginx configurations which need to be replaced.


See: https://github.com/TasmoAdmin/TasmoAdmin/blob/master/UPGRADE.md#from-2---3

**Comment by bobybobybob** [comment]
dont know. just stop container and click recreate with pull new image.... as i have done more times the last months with no problem. But OK, i wil try to remove all and build new up

**Comment by inverse** [comment]
You don't need to remove all your configuration - just if there is an nginx folder in there you'll need to nuke that.

**Comment by bobybobybob** [comment]
dont know, too much english text. I remove all and reinstall and now all is ok. Only have to add the devices new again but i can life with it. Thank you for fast answer and best Regards.
