### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by mafrei2019** [TasmoAdmin/TasmoAdmin#818]
Startseite in Einstellungen läßt sich zwar ändern, wird aber ignoriert. 
Es meldet sich immer die Startseite nicht die Liste wie eingestellt.
(Version 3.0.0 in Docker)

**Comment by inverse** [comment]
Thanks for the bug report - It should be fixed now.

I published a new beta build with the fix in:  https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v3.0.1-beta.1
