### ISSUE TITLE
Tasmoadmin keeps redirecting to google.com with valid user agent

### ISSUE THREAD

**Issue by hakan42** [TasmoAdmin/TasmoAdmin#821]
Tasmoadmin docker image as of 08.03.2023 redirects any requests to google.com, be they with a valid browser (chrome in my case), be they via curl ("User-Agent: curl/7.47.0")

## Expected Behavior

The web pages should be accessible.

## Current Behavior

301 redirects to www.google.com

## Steps to Reproduce

1. Start docker image
2. access via curl ("curl -v http://192.168.42.42:5555")
3. Observe 301 redirect

## Context (Environment)

Dockerized, data directory mounted, started via systemd, port 5555 remapped to 80 ("-p 0.0.0.0:5555:80")

**Comment by hakan42** [comment]
For clarity, I have also completely removed the "data" directory and started a fresh deployment. Does not change the reported behaviour.

**Comment by inverse** [comment]
What version are you using?

**Comment by hakan42** [comment]
First I noticed this with the docker image "latest" which seems to contain 3.0.1.beta.1.

I would need to retest to see which version started putting those checks into nginx.conf

**Comment by inverse** [comment]
Sounds like you're hitting this https://github.com/TasmoAdmin/TasmoAdmin/blob/master/.docker/rootfs/etc/nginx/nginx.conf#L16

Not sure why it was added in the first place :/ 

Weird though that Chrome is blocking it though

**Comment by inverse** [comment]
Published https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v3.0.1-beta.2 which should help

**Comment by hakan42** [comment]
works now.
