### ISSUE TITLE
Protect from powering on/off not working 3.0.1

### ISSUE THREAD

**Issue by serbasan** [TasmoAdmin/TasmoAdmin#834]
## Expected Behavior
Ticking or unticking and save should change setting for device in verion 3.0.1 

## Current Behavior
No change

## Possible Solution
Fix as it was working in 1.7.0

## Context (Environment)
Tasmoadmin 3.0.1

**Comment by inverse** [comment]
Unable to reproduce this one - I check and save and reload and it persists.

**Comment by mafrei2019** [comment]
Kann ich bestätigen.
 Wird z.B der Schalter "Vor ausschalten schützen" aktiviert, kann man dennoch auschalten.

**Comment by serbasan** [comment]
Comment that on the home page it does look blocked. It is not seen on the listing page. The status switch does not change at all. In previous versions the switch was disabled and greyed out. Tasmotta 3.0.2 also fails
