### ISSUE TITLE
Container unhealthy: "sh: ]: unknown operand"

### ISSUE THREAD

**Issue by IntExCZ** [TasmoAdmin/TasmoAdmin#842]
When checking container status Portainer, health status reports "unhealthy"

## Expected Behavior
Container healthy

## Current Behavior
Container unhealthy, Last output:  "sh: ]: unknown operand"

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
Home Assistant OS 9.5
Home Assistant Core 2023.3.6

**Comment by IntExCZ** [comment]
Sorry, this is related to fork: https://github.com/hassio-addons/addon-tasmoadmin

**Comment by inverse** [comment]
Ahh I see you published https://github.com/hassio-addons/addon-tasmoadmin/issues/301

**Comment by IntExCZ** [comment]
> Ahh I see you published [hassio-addons/addon-tasmoadmin#301](https://github.com/hassio-addons/addon-tasmoadmin/issues/301)

Yes, sorry, I have chosen wrong branch.
I would like to delete it here but there is no option for that.

**Comment by inverse** [comment]
We can close it here :)
