### ISSUE TITLE
[docker image] TasmoAdmin does not start correct

### ISSUE THREAD

**Issue by udo1toni** [TasmoAdmin/TasmoAdmin#844]
## Expected Behavior
TasmoAdmin as docker image should run out-of-the-box :)

## Current Behavior
instead of the normal web UI, I'm getting errors

## Possible Solution
Problem is the symbolic link from /data/tasmoadmin/ to /var/www/tasmoadmin/data. When this is created, the folder /var/www/tasmoadmin/data/ is already there, so instead of creating the correct link, it leads to a symbolic link within the folder.

## Steps to Reproduce
1. setup a new container with tasmoadmin with portainer (I even tried a completely new docker machine to ensure that there is no issue with the machine itself)

## Context (Environment)
Host System is a Proxmox LXC Container, running docker 23.0.1 (API: 1.42) and Portainer 2.17.1. 

## Detailed Description
Problem emerged a while ago (~ TasmoAdmin v2.1 ?) Did work before.
As the folder /var/www/tasmoadmin/data can't be deleted, my workaround is to delete all files within the folder and create symbolic links to the files and folders in /data/tasmoadmin/, which works fine, but has to be done on every startup of the container (obviously)

**Comment by inverse** [comment]
Thanks for the bug report! This sounds strange.

https://github.com/TasmoAdmin/TasmoAdmin/blob/master/.docker/rootfs/etc/cont-init.d/16-persistent-data-tasmoadmin.sh#L55-L57

It should be deleting ` /var/www/tasmoadmin/data` before doing the symlink :/

**Comment by udo1toni** [comment]
Maybe that's the point. I'm, not able to delete the folder at all:
from container shell (as root)
`bash-5.1# rm -rf /var/www/tasmoadmin/data/
rm: can't remove '/var/www/tasmoadmin/data': Invalid argument`
I have no idea what invalid argument there should be...

**Comment by hpannenb** [comment]
Same issue here with nearly identical setup (Proxmox LXC, Docker 23.0.3, Portainer 2.17.1) and a vanilla tasmoadmin docker image.
From the log:
```
...
2023-04-11T15:41:20.898607746Z [cont-init.d] 15-docker-environment.sh: exited 0.
2023-04-11T15:41:20.899720161Z [cont-init.d] 16-persistent-data-tasmoadmin.sh: executing... 
2023-04-11T15:41:20.902073718Z Symlinking /data/tasmoadmin directory to persistent storage location...
2023-04-11T15:41:20.902718104Z rm: can't remove '/var/www/tasmoadmin/data': Invalid argument
2023-04-11T15:41:20.905772305Z [cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
2023-04-11T15:41:20.906491140Z [cont-init.d] done.
2023-04-11T15:41:20.907307988Z [services.d] starting services
2023-04-11T15:41:20.913358661Z [services.d] done.
```
After start-up:
```
bash-5.1# ls -laR /var/www/tasmoadmin/data/
/var/www/tasmoadmin/data/:
total 2
drwxr-xr-x    1 root     root             5 Apr 11 15:41 .
drwxr-xr-x    1 root     root             5 Apr 10 14:33 ..
lrwxrwxrwx    1 root     root            16 Apr 11 15:41 tasmoadmin -> /data/tasmoadmin
```
BTW: Manually creating an empty directory in `/var/www/tasmoadmin/`and removing it works fine.

**Comment by inverse** [comment]
Does your container have any particular environment variables for mounting the data volume?

**Comment by hpannenb** [comment]
> How are you mounting persistent storage to the container? to `/data/tasmoadmin` on the container?
> 
> I'm unable to reproduce this with such volume mounted like:
> 
> ```
> docker run -it -v $(pwd)/mount:/data/tasmoadmin -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:v3.0.2-beta.2
> ```

I copied Your approach and this is what has been logged:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 12-patches.sh: executing... 
[cont-init.d] 12-patches.sh: exited 0.
[cont-init.d] 13-persistent-data-nginx.sh: executing... 
Data nginx directory not initialized, doing that now...
'/etc/nginx/nginx.conf' -> '/etc/nginx/nginx.conf.org'
'/etc/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf.org'
'/data/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf'
'/etc/nginx/nginx-ssl.conf' -> '/data/nginx/nginx-ssl.conf'
'/etc/nginx/certs/README.md' -> '/data/nginx/certs/README.md'
'/etc/nginx/certs/tasmoadmin.conf' -> '/data/nginx/certs/tasmoadmin.conf'
'/etc/nginx/certs/tasmoadmin.crt' -> '/data/nginx/certs/tasmoadmin.crt'
'/etc/nginx/certs/tasmoadmin.key' -> '/data/nginx/certs/tasmoadmin.key'
Symlinking /etc/nginx.conf from persistent storage location...
[cont-init.d] 13-persistent-data-nginx.sh: exited 0.
[cont-init.d] 14-nginx-ssl.sh: executing... 
[cont-init.d] 14-nginx-ssl.sh: exited 0.
[cont-init.d] 15-docker-environment.sh: executing... 
Docker env does not exist, doing that now...
[cont-init.d] 15-docker-environment.sh: exited 0.
[cont-init.d] 16-persistent-data-tasmoadmin.sh: executing... 
/data/tasmoadmin/firmwares created.
/data/tasmoadmin/updates created.
Symlinking /data/tasmoadmin directory to persistent storage location...
rm: can't remove '/var/www/tasmoadmin/data': Invalid argument
[cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12-Apr-2023 13:48:11] NOTICE: fpm is running, pid 374
[12-Apr-2023 13:48:11] NOTICE: ready to handle connections
```
In the working directory a `mount` directory has been created as supposed to (including the firmwares and updates folders). Besides using Portainer within an LXC container there is IMHO nothing else "special" to the environment.

**Comment by hpannenb** [comment]
Checked on a fresh Debian 11 VM with docker installed: No issue as shown above. Might be related to something else in my case.

**Comment by inverse** [comment]
Not familiar with LXC containers at all - hope you manage to find a solution!

**Comment by Tschak77** [comment]
I had similar problem with same system Docker on LXC with following web error:

```
array(3) { [0]=> array(7) { ["file"]=> string(42) "/var/www/tasmoadmin/includes/container.php" ["line"]=> int(13) ["function"]=> string(11) "__construct" ["class"]=> string(17) "TasmoAdmin\Config" ["object"]=> object(TasmoAdmin\Config)#4 (6) { ["debug":"TasmoAdmin\Config":private]=> bool(false) ["dataDir":"TasmoAdmin\Config":private]=> string(25) "/var/www/tasmoadmin/data/" ["appRoot":"TasmoAdmin\Config":private]=> string(20) "/var/www/tasmoadmin/" ["cfgFile":"TasmoAdmin\Config":private]=> string(38) "/var/www/tasmoadmin/data/MyConfig.json" ["filesystem":"TasmoAdmin\Config":private]=> object(Symfony\Component\Filesystem\Filesystem)#5 (0) { } ["defaultConfigs":"TasmoAdmin\Config":private]=> array(22) { ["ota_server_ssl"]=> string(1) "0" ["ota_server_ip"]=> string(12) "192.168.96.2" ["ota_server_port"]=> string(2) "80" ["username"]=> string(0) "" ["password"]=> string(0) "" ["refreshtime"]=> string(1) "8" ["current_git_tag"]=> string(0) "" ["update_automatic_lang"]=> string(15) "tasmota-sensors" ["nightmode"]=> string(4) "auto" ["login"]=> string(1) "1" ["scan_from_ip"]=> string(12) "192.168.96.2" ["scan_to_ip"]=> string(14) "192.168.96.254" ["homepage"]=> string(5) "start" ["check_for_updates"]=> string(1) "3" ["minimize_resources"]=> string(1) "1" ["update_channel"]=> string(6) "docker" ["hide_copyright"]=> string(1) "1" ["show_search"]=> string(1) "1" ["update_fe_check"]=> string(1) "0" ["update_be_check"]=> string(1) "1" ["auto_update_channel"]=> string(6) "stable" ["force_upgrade"]=> string(1) "0" } } ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(25) "/var/www/tasmoadmin/data/" [1]=> string(20) "/var/www/tasmoadmin/" } } [1]=> array(4) { ["file"]=> string(42) "/var/www/tasmoadmin/includes/bootstrap.php" ["line"]=> int(69) ["args"]=> array(1) { [0]=> string(42) "/var/www/tasmoadmin/includes/container.php" } ["function"]=> string(7) "require" } [2]=> array(4) { ["file"]=> string(29) "/var/www/tasmoadmin/index.php" ["line"]=> int(12) ["args"]=> array(1) { [0]=> string(42) "/var/www/tasmoadmin/includes/bootstrap.php" } ["function"]=> string(12) "include_once" } } /var/www/tasmoadmin/data/ is NOT WRITEABLE! | __construct()
```

In my case it is an access problem on /var/www/tasmoadmin/data

```
bash-5.1# ls -laR /var/www/tasmoadmin/data/
/var/www/tasmoadmin/data/:
total 15
drwxr-xr-x    1 nginx    nginx            7 May  5 23:29 .
drwxr-xr-x    1 root     root             5 May  5 23:02 ..
-rw-------    1 nginx    nginx          643 May  5 23:29 MyConfig.json
-rw-r--r--    1 nginx    nginx            0 May  5 23:22 devices.csv
lrwxrwxrwx    1 nginx    nginx           16 May  5 23:22 tasmoadmin -> /data/tasmoadmin
```

this worked for me

```
chown -R nginx:nginx /var/www/tasmoadmin/data/
```

**Comment by Tschak77** [comment]
Hi my solution was with proxmox LXC and docker

the problem ist LXC and docker and Storage driver overlay2 with ZFS not working, changing to fuse-overlayfs

install fuse-overlayfs on host
activate FUSE on container

LXC container
install fuse-overlayfs
ln -s /usr/bin/fuse-overlayfs /usr/local/bin/fuse-overlayfs
create /etc/docker/daemon.json
  {
    "storage-driver": "fuse-overlayfs"
  }

more details
https://c-goes.github.io/posts/proxmox-lxc-docker-fuse-overlayfs/
https://benheater.com/proxmox-run-docker-on-linux-containers-lxc/
https://docs.docker.com/storage/storagedriver/overlayfs-driver/

**Comment by oywino** [comment]
Excuse me for jumping in, but is TasmoAdmin v3.0.5 available on Docker Hub ?

**Comment by inverse** [comment]
@oywino  We migrated to Github CR as it's easier to maintain for OSS.


See: https://github.com/TasmoAdmin/TasmoAdmin/pkgs/container/tasmoadmin/95983043?tag=v3.0.5
