### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by kinslayer1982** [TasmoAdmin/TasmoAdmin#845]
Except for accessing the start page nothing works.

## Expected Behavior

really?

## Current Behavior

error messages for everything

## Steps to Reproduce

1. install docker
2. pull tasmoadmin
3. run tasmoadmin (according to https://github.com/TasmoAdmin/TasmoAdmin/wiki/Guide-for-TasmoAdmin-on-Docker)
4. error

## Context (Environment)

Docker, all Tasmoadmin versions I tried (2.x -> 3.x)

## Context (Device)

Raspberry Pi4 (4GB)

## Detailed Description

After logging in nothing works. Auto scan will detect 0 devices (No devices found!), manually trying to add device results in instant timeout (Device not found CURL ERROR => cURL error 28: Failed to connect to 192.162.172.26 port 80 after -400000 ms: Operation timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://192.162.172.26/cm?cmnd=status+0), settings page just throws an error message (object(Symfony\Component\HttpClient\Exception\TransportException)#105 (7) { ["message":protected]=> string(87) "Could not resolve host: ota.tasmota.com for "https://ota.tasmota.com/tasmota/release/"." ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(67) "/var/www/tasmoadmin/vendor/symfony/http-client/Chunk/ErrorChunk.php" ["line":protected]=> int(56) ["trace":"Exception":private]=> array(10) { [0]=> array(5) { ["file"]=> string(79) "/var/www/tasmoadmin/vendor/symfony/http-client/Response/CommonResponseTrait.php" ["line"]=> int(141) ["function"]=> string(7) "isFirst" ["class"]=> string(45) "Symfony\Component\HttpClient\Chunk\ErrorChunk" ["type"]=> string(2) "->" } [1]=> array(5) { ["file"]=> string(79) "/var/www/tasmoadmin/vendor/symfony/http-client/Response/CommonResponseTrait.php" ["line"]=> int(41) ["function"]=> string(10) "initialize" ["class"]=> string(50) "Symfony\Component\HttpClient\Response\CurlResponse" ["type"]=> string(2) "::" } [2]=> array(5) { ["file"]=> string(72) "/var/www/tasmoadmin/vendor/symfony/http-client/Response/CurlResponse.php" ["line"]=> int(241) ["function"]=> string(12) "doGetContent" ["class"]=> string(50) "Symfony\Component\HttpClient\Response\CurlResponse" ["type"]=> string(2) "->" } [3]=> array(5) { ["file"]=> string(62) "/var/www/tasmoadmin/vendor/symfony/browser-kit/HttpBrowser.php" ["line"]=> int(56) ["function"]=> string(10) "getContent" ["class"]=> string(50) "Symfony\Component\HttpClient\Response\CurlResponse" ["type"]=> string(2) "->" } [4]=> array(5) { ["file"]=> string(66) "/var/www/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php" ["line"]=> int(370) ["function"]=> string(9) "doRequest" ["class"]=> string(40) "Symfony\Component\BrowserKit\HttpBrowser" ["type"]=> string(2) "->" } [5]=> array(5) { ["file"]=> string(52) "/var/www/tasmoadmin/src/Helper/TasmotaOtaScraper.php" ["line"]=> int(28) ["function"]=> string(7) "request" ["class"]=> string(44) "Symfony\Component\BrowserKit\AbstractBrowser" ["type"]=> string(2) "->" } [6]=> array(5) { ["file"]=> string(48) "/var/www/tasmoadmin/src/Helper/TasmotaHelper.php" ["line"]=> int(109) ["function"]=> string(11) "getFirmware" ["class"]=> string(35) "TasmoAdmin\Helper\TasmotaOtaScraper" ["type"]=> string(2) "->" } [7]=> array(5) { ["file"]=> string(48) "/var/www/tasmoadmin/src/Helper/TasmotaHelper.php" ["line"]=> int(70) ["function"]=> string(16) "getLatestRelease" ["class"]=> string(31) "TasmoAdmin\Helper\TasmotaHelper" ["type"]=> string(2) "->" } [8]=> array(5) { ["file"]=> string(41) "/var/www/tasmoadmin/pages/site_config.php" ["line"]=> int(70) ["function"]=> string(11) "getReleases" ["class"]=> string(31) "TasmoAdmin\Helper\TasmotaHelper" ["type"]=> string(2) "->" } [9]=> array(4) { ["file"]=> string(29) "/var/www/tasmoadmin/index.php" ["line"]=> int(85) ["args"]=> array(1) { [0]=> string(41) "/var/www/tasmoadmin/pages/site_config.php" } ["function"]=> string(7) "include" } } ["previous":"Exception":private]=> object(Symfony\Component\HttpClient\Exception\TransportException)#112 (7) { ["message":protected]=> string(87) "Could not resolve host: ota.tasmota.com for "https://ota.tasmota.com/tasmota/release/"." ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(72) "/var/www/tasmoadmin/vendor/symfony/http-client/Response/CurlResponse.php" ["line":protected]=> int(327) ["trace":"Exception":private]=> array(11) { [0]=> array(5) { ["file"]=> string(82) "/var/www/tasmoadmin/vendor/symfony/http-client/Response/TransportResponseTrait.php" ["line"]=> int(167) ["function"]=> string(7) "perform" ["class"]=> string(50) "Symfony\Component\HttpClient\Response\CurlResponse" ["type"]=> string(2) "::" } [1]=> array(5) { ["file"]=> string(79) "/var/www/tasmoadmin/vendor/symfony/http-client/Response/CommonResponseTrait.php" ["line"]=> int(140) ["function"]=> string(6) "stream" ["class"]=> string(50) "Symfony\Component\HttpClient\Response\CurlResponse" ["type"]=> string(2) "::" } [2]=> array(5) { ["file"]=> string(79) "/var/www/tasmoadmin/vendor/symfony/http-client/Response/CommonResponseTrait.php" ["line"]=> int(41) ["function"]=> string(10) "initialize" ["class"]=> string(50) "Symfony\Component\HttpClient\Response\CurlResponse" ["type"]=> string(2) "::" } [3]=> array(5) { ["file"]=> string(72) "/var/www/tasmoadmin/vendor/symfony/http-client/Response/CurlResponse.php" ["line"]=> int(241) ["function"]=> string(12) "doGetContent" ["class"]=> string(50) "Symfony\Component\HttpClient\Response\CurlResponse" ["type"]=> string(2) "->" } [4]=> array(5) { ["file"]=> string(62) "/var/www/tasmoadmin/vendor/symfony/browser-kit/HttpBrowser.php" ["line"]=> int(56) ["function"]=> string(10) "getContent" ["class"]=> string(50) "Symfony\Component\HttpClient\Response\CurlResponse" ["type"]=> string(2) "->" } [5]=> array(5) { ["file"]=> string(66) "/var/www/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php" ["line"]=> int(370) ["function"]=> string(9) "doRequest" ["class"]=> string(40) "Symfony\Component\BrowserKit\HttpBrowser" ["type"]=> string(2) "->" } [6]=> array(5) { ["file"]=> string(52) "/var/www/tasmoadmin/src/Helper/TasmotaOtaScraper.php" ["line"]=> int(28) ["function"]=> string(7) "request" ["class"]=> string(44) "Symfony\Component\BrowserKit\AbstractBrowser" ["type"]=> string(2) "->" } [7]=> array(5) { ["file"]=> string(48) "/var/www/tasmoadmin/src/Helper/TasmotaHelper.php" ["line"]=> int(109) ["function"]=> string(11) "getFirmware" ["class"]=> string(35) "TasmoAdmin\Helper\TasmotaOtaScraper" ["type"]=> string(2) "->" } [8]=> array(5) { ["file"]=> string(48) "/var/www/tasmoadmin/src/Helper/TasmotaHelper.php" ["line"]=> int(70) ["function"]=> string(16) "getLatestRelease" ["class"]=> string(31) "TasmoAdmin\Helper\TasmotaHelper" ["type"]=> string(2) "->" } [9]=> array(5) { ["file"]=> string(41) "/var/www/tasmoadmin/pages/site_config.php" ["line"]=> int(70) ["function"]=> string(11) "getReleases" ["class"]=> string(31) "TasmoAdmin\Helper\TasmotaHelper" ["type"]=> string(2) "->" } [10]=> array(4) { ["file"]=> string(29) "/var/www/tasmoadmin/index.php" ["line"]=> int(85) ["args"]=> array(1) { [0]=> string(41) "/var/www/tasmoadmin/pages/site_config.php" } ["function"]=> string(7) "include" } } ["previous":"Exception":private]=> NULL } })

**Comment by inverse** [comment]
Sounds like an issue with the network on the PI What do you get when you run this from there?

```
docker run -it curlimages/curl -I https://ota.tasmota.com/tasmota/release
```

**Comment by kinslayer1982** [comment]
curl: (6) Could not resolve host: ota.tasmota.com

**Comment by inverse** [comment]
Sounds like something is up with your PI or docker network.

If you run `curl -I https://ota.tasmota.com/tasmota/release` and that works than it would isolate it to docker.

**Comment by kinslayer1982** [comment]
Running curl from the host works fine. I also have no problem with dns resolution on any other docker container, no matter if it's on the same host or others...

**Comment by inverse** [comment]
At least that isolates the problem to do with docker.

Are the ones that are working in the same docker network?

**Comment by kinslayer1982** [comment]
Almost every container uses it's own default docker network.

I just tried to run tasmoadmin with network="host" but still same problem.

**Comment by inverse** [comment]
I can't think of anything special about TasmotaAdmin that would give this issue :/ Running TasmoAdmin on the different machine would confirm that.

The fact that the basic curl one failed highlights an issue on that machine.

**Comment by kinslayer1982** [comment]
Stupid me. Never tried to run it on a different machine... damn. Works on a different host. Sorry for not trying that earlier. Now to find out whats going on with docker...

**Comment by inverse** [comment]
No worries :) 

Sounds super odd :/ hope you can figure it out soon!

**Comment by kinslayer1982** [comment]
I think I have found the solution. It seems to be related to Raspbian and images based on Alpine 3.1.3 and onwards. 64 bit version of Raspbian is fine, on 32 bit version isn't.

On the 32 bit version this happens with Alpine based images:
nslookup google.de
nslookup: clock_gettime(MONOTONIC) failed

Thought I'd share it here.
