### ISSUE TITLE
Add an URL to tasmota32-allsensors bin

### ISSUE THREAD

**Issue by SOliver78** [TasmoAdmin/TasmoAdmin#852]
Hello,

is it possible to add an second URL for unoffical tasmota32-allsensors bin?

https://github.com/tasmota/install/blob/firmware/firmware/unofficial/tasmota32-allsensors.bin

The official tamsota32-sensors doesnt include the IKEA Vindriktning sensor.

Thanks.

**Comment by inverse** [comment]
Will be quite hard to implement as we're currently scraping firmware's from https://ota.tasmota.com/tasmota/

**Comment by SOliver78** [comment]
I Have ask Theo Arends, if it possible, to create an oto url for unoffical binaries ;)

**Comment by inverse** [comment]
if thats possible itll def make it easier to handle! we're currently scraping that OTA page too. would be nice also for that data to be served up as JSON too.
