### ISSUE TITLE
PHP 7.x or 8.x and how to manage

### ISSUE THREAD

**Issue by edegraaff** [TasmoAdmin/TasmoAdmin#875]
I got an error i should run php 8 but, in the manual is php 7 mentioned
https://github.com/TasmoAdmin/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04
sudo apt-get update && \
sudo apt-get install \
apache2 \
php \
libapache2-mod-php \
php7.0-curl \
php7.0-zip \
php7.0-mbstring \
git \
unzip \
vim

## Expected Behavior

Documentation outdated or installation demand 8.x but is wrong
on the main page php 8 is mentioned

## Current Behavior

I have now a broken installation with php 8 and this error on the start screen
ERROR: PHP Curl is missing.Please install PHP Curlsudo apt-get install php7.0-curland restart webserver

## Possible Solution

Make clear what php should be installed, and or, suggestions to do a reinstall procedure? 
## Steps to Reproduce

1. update to php8
2. remove php7
3. reboot
4. system error ERROR: PHP Curl is missing.Please install PHP Curlsudo apt-get install php7.0-curland restart webserver

## Context (Environment)

Raspbian Bullseye, normal installation web and php8
## Context (Device)

...
## Detailed Description

see above
## Possible Implementation

check script that advives on the right versions, readme with prereq

**Comment by inverse** [comment]
i put a note at the top of the wiki page stating it's out of date due to the PHP version.

I don't have time to maintain this so feel free to contribute with the updated steps for PHP 8.1. 

or should i just remove it to avoid confusion?

**Comment by edegraaff** [comment]
> i put a note at the top of the wiki page stating it's out of date due to the PHP version.
> 
> I don't have time to maintain this so feel free to contribute with the updated steps for PHP 8.1.
> 
> or should i just remove it to avoid confusion?
I think it is good to at least make a note. 
What i have done is some tricks to get the whole working
tweek here with php 8.2 and a reboot solved the issue 
php7.0-curl \
php7.0-zip \
php7.0-mbstring \

**Comment by sp2003** [comment]
hi, i don't understand how you solved it. i also have php 8.2.5 installed, but i get the same error.

**Comment by edegraaff** [comment]
i will write tonight how i resolved this issue. i am currently not behind the machine.

**Comment by inverse** [comment]
Yeah the error message displayed inst that helpful - I should change it to be more generic about missing the curl PHP extension.

**Comment by edegraaff** [comment]
This is how i solved the issue:
apt-get update && apt-get upgrade -y   
curl https://packages.sury.org/php/apt.gpg | sudo tee /usr/share/keyrings/suryphp-archive-keyring.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/suryphp-archive-keyring.gpg] https://packages.sury.org/php/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/sury-php.list
sudo apt update
sudo apt install php8.1-cli
sudo apt-get purge php7.*
apt-get install php8.2-curl
apt-get install libapache2-mod-php
apt-get install php8.2-zip
apt-get autoremove
apt-get install php8.2-curland
reboot

**Comment by inverse** [comment]
@edegraaff sounds like you could add this to the wiki :) 

Also should  `sudo apt install php8.1-cli`  be `sudo apt install php8.2-cli` - although not sure we need the cli package for TasmoAdmin but good to have for debugging/running scripts manually

**Comment by edegraaff** [comment]
> @edegraaff sounds like you could add this to the wiki :)
> 
> Also should `sudo apt install php8.1-cli` be `sudo apt install php8.2-cli` - although not sure we need the cli package for TasmoAdmin but good to have for debugging/running scripts manually
Hi, i am nat that good to write to the wiki, if some others can reproduce the procedure we could make some changes at the wiki witht he right modules to be installed. At least after some puzzeling last night i had it all working. 

i think the error message needs to be updated and when the procedure is confirmed we could make one quick installation document with all the installers behind in one line like: 

procedure to install php8.2 on existing php 7.x system:

sudo apt-get update && apt-get upgrade -y

sudo curl https://packages.sury.org/php/apt.gpg | sudo tee /usr/share/keyrings/suryphp-archive-keyring.gpg >/dev/null

sudo echo "deb [signed-by=/usr/share/keyrings/suryphp-archive-keyring.gpg] https://packages.sury.org/php/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/sury-php.list

sudo apt update
sudo apt install php8.1-cli php8.2-curl libapache2-mod-php php8.2-zip php8.2-curland
sudo apt-get purge php7.*
sudo apt-get autoremove
sudo reboot

**Comment by Schnup89** [comment]
Created a guide for Debian 10, maybe this is helpful:
https://github.com/TasmoAdmin/TasmoAdmin/wiki/Guide-for-Debian-Server-10-(Buster)
