### ISSUE TITLE
Redirect to still same login page after  input correct login/password

### ISSUE THREAD

**Issue by Zbeed** [TasmoAdmin/TasmoAdmin#886]
Hi, I have the following problem with TasmoAdmin 0.24.2 on HA 2023.5.2 on a Synology virtual machine:
the installation of TasmoaAdmin went well, the choice of name and password as well. If I open the web UI by clicking in Add-ons (opens in a new browser window) then everything is fine. But if I open the web UI in the home-assistant from the left sidebar and fill in the correct name and password, it doesn't open the device list, but comes back to the same login page. The name and password are correct, no error message will appear (if I type it wrong, an error message will appear).
I searched here but couldn't find anything. Thanks for the help.

**Comment by Zbeed** [comment]
Thank you, but I'm not sure I understood the advice. The IP address of my HA is the same as the IP address that is in the yaml configuration for the panel-iframe, only the ports are different. Although, there is one more difference. In yaml I must wrote https://192.168...., because http cause only error message "The plain HTTP request was sent to HTTPS port" and will not open login page. If it is mistake, then I dont know to do now to prevent https error...

**Comment by inverse** [comment]
I've not tried with TLS as for TA to flash devices it needs to serve the firmware over plain HTTP.
