### ISSUE TITLE
Unable to discover/add device configured ad TuyaMCU

### ISSUE THREAD

**Issue by alexlia** [TasmoAdmin/TasmoAdmin#893]
A device with latest (12.5.0) firmware is not automatically discoverd, if I try to add it manually I've got a JSON_ERROR

## Expected Behavior
The device will be added by autodiscovery

## Current Behavior
The device is not discovered and trying to add it manually give the following error:

Risposta JSON => {s}Mode{m}0{e}{"Status":{"Module":54,"DeviceName":"Lampada baule","FriendlyName":["Lampada baule"],"Topic":"light_02","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0},"StatusPRM":{"Baudrate":9600,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:04:45","StartupUTC":"2023-05-16T07:52:03","Sleep":50,"CfgHolder":4617,"BootCount":40,"BCResetTime":"2022-04-17T17:29:06","SaveCount":2386,"SaveAddress":"F9000"},"StatusFWR":{"Version":"12.5.0(tasmota)","BuildDateTime":"2023-04-17T08:03:54","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"363/699"},"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["pupinet",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A002800000000","00000080","00006000","00004000","00000000"]},"StatusMEM":{"ProgramSize":632,"Free":368,"Heap":21,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540C8","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000080"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6","I2CDriver":"7"},"StatusNET":{"Hostname":"light-02-1647","IPAddress":"192.168.1.57","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.254","DNSServer2":"0.0.0.0","Mac":"EC:FA:BC:69:E6:6F","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.1.2","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_69E66F","MqttUser":"tasmota","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4},"StatusTIM":{"UTC":"2023-05-16T07:56:48","Local":"2023-05-16T08:56:48","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+01:00","Sunrise":"05:07","Sunset":"20:25"},"StatusSNS":{"Time":"2023-05-16T08:56:48"},"StatusSTS":{"Time":"2023-05-16T08:56:48","Uptime":"0T00:04:45","UptimeSec":285,"Heap":21,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":1,"POWER":"ON","Dimmer":100,"Color":"00FF000000","HSBColor":"120,100,100","White":0,"CT":153,"Channel":[0,100,0,0,0],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"pupinet","BSSId":"30:42:40:84:E1:4C","Channel":2,"Mode":"11n","RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:05"}}}

## Steps to Reproduce
Try to add device using IP

## Context (Environment)
TasmoAdmin 0.24.2 ad HomeAssistant add-on

## Context (Device)
Desktop light based on ESP8266 and TuyaMCU

**Comment by inverse** [comment]
The normal payload seems normal except the ` {s}Mode{m}0{e}` leading - that's what's breaking it as it's not valid JSON.

Do you get the same output when you invoke `http://<device-ip>/cm?cmnd=status%200`?

**Comment by alexlia** [comment]
Hello, yes, invoking directly the url I've got the same payload; so is probably a Tasmota problem, correct?
Thank you for the response

**Comment by inverse** [comment]
Looks like it's a similar issue to #887 which was reported upstream - it looks like a fix is in the works which might resolve it.
