### ISSUE TITLE
Parse error: syntax error, unexpected '' => ''

### ISSUE THREAD

**Issue by halambre** [TasmoAdmin/TasmoAdmin#91]
Hello! first I would like to thank the community and especially the creator of this project and Tasmota! Worthy of admiration!

well, I have installed SonWeb in pi3 with apache2 and php7. Everything works fine, but after a while I get an error:

Parse error: syntax error, unexpected '' => '' (T_CONSTANT_ENCAPSED_STRING) in /var/www/html/includes/Config.php(57): eval () 'd code on line 3

I think there is something that corrupts the MyConfig.php file because after this error it looks like this:

<? php return array (
  'ota_server_ip' => '',
); ?> rname '=>' admin ',
  'password' => '6c4bbe20e34bd8e86a33c656be11b004',
  'refreshtime' => '5',
  'current_git_sha' => 'e4126d505dbc93b5e2083bac2a4a9daf5a327e49',
  'update_automatic_lang' => '',
  'nightmode' => 'auto',
  'login' => '1',
); ?>

If I rebuild this file everything works fine again. Do you have to have a special MyConfig.php permission?

thank you very much to all!

**Comment by reloxx13** [comment]
hey,

did you disable the opcache?

`sudo rm /etc/php/7.0/mods-available/opcache.ini`

path depending of your php version ( /php7.2/ ....)

**Comment by reloxx13** [comment]
heya,

their was a wrong path in the wiki tutorials. 

after an update of the system, the opcache.ini file is back.

i corrected it in the wiki.

please check if this file exists and delete it:

sudo rm /etc/php/7.0/apache2/conf.d/10-opcache.ini

restart apache after that
 /etc/init.d/apache2 restart

**Comment by halambre** [comment]
today the same error has appeared:

Parse error: syntax error, unexpected '' => '' (T_CONSTANT_ENCAPSED_STRING) in /var/www/html/includes/Config.php(63) : eval()'d code on line 3

and the file MyConfig.php corrupt. i deleted it and i can access

**Comment by halambre** [comment]
after 5 min again error, for the moment I have modified the function "write" of /includes/Config.php
,so that it doesn`t write the file, it only returns true.

 public function write( $key, $value ) {
                        return TRUE;
                }

**Comment by reloxx13** [comment]
Add a site on the root directory of sonweb "info.php"
Enter this content in the file:
<?php phpinfo();

Call the site in your webbroser
http://sonweb_ip/info.php

Ctrl+F on the page for opcache and see if it is disabled.

You did not forgot to restart apache after deleting those file links?

**Comment by frenck** [comment]
I've received 2 reports regarding this issue:
https://community.home-assistant.io/t/community-hass-io-add-on-sonweb/54155/10?u=frenck
https://community.home-assistant.io/t/community-hass-io-add-on-sonweb/54155/22?u=frenck

**Comment by inverse** [comment]
Closing as stale
