### ISSUE TITLE
TasmoAdmin - Die Tasmota Firmware hat vermutlich einen nicht verständlichen JSON String geantwortet, welcher in TasmoAdmin angepasst werden muss

### ISSUE THREAD

**Issue by harrysam** [TasmoAdmin/TasmoAdmin#910]
Hello, I hope I am right here in this forum. I am newly using TasmoAdmin in the web browser to configure my Tasmo devices. When searching for a device, I received an error message advising me to do the following: 
Please copy the complete error message and share this with the developer (GitHub/CreationX forum). The Tasmota firmware probably answered a not understandable JSON string which needs to be adjusted in TasmoAdmin. 
Can somebody help? Vielen Dank im Voraus! 

Here the error message: 

`Modul nicht gefunden
JSON FEHLER => 4: Syntax error
Bitte kopiere die komplette Fehlermeldung und teile dies dem Entwickler mit (GitHub/CreationX Forum). Die Tasmota Firmware hat vermutlich einen nicht verständlichen JSON String geantwortet welcher in TasmoAdmin angepasst werden muss.
JSON Antwort => {"Status":{"Module":39,"DeviceName":"Computerzimmer-Rollo","FriendlyName":["Computerzimmer-AUF","Computerzimmer-AB"],"Topic":"Computerzimmer-Rollo","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"15T20:48:57","StartupUTC":"2023-05-22T16:13:33","Sleep":50,"CfgHolder":4620,"BootCount":60,"BCResetTime":"2020-09-20T19:06:14","SaveCount":3234,"SaveAddress":"F4000"},"StatusFWR":{"Version":"8.5.0(tasmota)","BuildDateTime":"2020.09.26 13:25:41","Boot":7,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"452/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Fritz7590",""],"TelePeriod":10,"Resolution":"55C180C0","SetOption":["0000C029","2805C8000100060000005A00000000000000","40000001","00006000","00000000"]},"StatusMEM":{"ProgramSize":597,"Free":404,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000407","8FDAE797","04368001","000000CF","010013C0","C000F981","00004005","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,36,37","Sensors":"1,3,4,5,6"},"StatusNET":{"Hostname":"Computerzimmer-Rollo-2409","IPAddress":"192.168.188.183","Gateway":"192.168.188.200","Subnetmask":"255.255.255.0","DNSServer":"192.168.188.200","Mac":"D8:F1:5B:B3:49:69","Webserver":2,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.188.123","MqttPort":1884,"MqttClientMask":"Computerzimmer-Rollo","MqttClient":"Computerzimmer-Rollo","MqttUser":"harry.sam","MqttCount":55,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2023-06-07T13:02:30","Local":"2023-06-07T15:02:30","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":99,"Sunrise":"04:50","Sunset":"21:46"},"StatusSNS":{"Time":"2023-06-07T15:02:30","Shutter1":{"Position":100,"Direction":0,"Target":100}},"StatusSTS":{"Time":"2023-06-07T15:02:30","Uptime":"15T20:48:57","UptimeSec":1370937,"Vcc":3.435,"Heap":21,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":55,"POWER1":"AUS","POWER2":"AUS","Wifi":{"AP":1,"SSId":"Fritz7590","BSSId":"3C:37:12:4A:3A:BE","Channel":11,"RSSI":40,"Signal":-80,"LinkCount":32,"Downtime":"0T00:03:03"}},"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":300,"Close":300,"50perc":50,"Delay":0,"Opt":"0000","Calib":"300:500:700:900:1000"}}
`

**Comment by inverse** [comment]
This is an interesting one - the JSON provided is indeed invalid but there was a fix for this version of Tasmota (8.5.0).

**Comment by inverse** [comment]
What version of TasmoAdmin are you running?

**Comment by harrysam** [comment]
I am using tasmoadmin_v3.0.5. 
My device has Tasmota v8.5.0. 
I will try now Tasmota v12.5.0.

**Comment by inverse** [comment]
Did you have any luck?
