### ISSUE TITLE
Is the Update Feature working ? 

### ISSUE THREAD

**Issue by BlueWings172** [TasmoAdmin/TasmoAdmin#934]
I had TasmoAdmin for over 2 years and currently on version 3.07 on docker (with compose).

I installed it to help update my Tasmota devices. for over 2 years it has never worked for me. Not once.

I'm giving this a last try before deleting it.

When I try to update, TasmoAdmin says update is successful. I tried the automatic feature where it fetches the latest Tasmota version itself and I tried manual and upload the minimal and full versions. Both never worked.

Below are the screenshots.

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/65966061/b14fc59a-9c39-43e4-ab4e-95e5b4bfbbab)

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/65966061/a46f509f-93ea-42a3-b7ea-beaa3e4df4e0)

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/65966061/5d6344ca-d429-4a4a-a45a-5f7adc18d264)

On the device console I see the below lines:
```
stat/tasmota_3C9CC2/RESULT = {"Upgrade":"Version 12.4.0 from http://172.18.0.2:80/data/firmwares/tasmota.bin"}
stat/tasmota_3C9CC2/UPGRADE = {"Upgrade":"Failed HTTP error: connection failed"}
```

While TasmoAdmin says the update was successful, the device fails to update. I tried on all devices, same story.

TasmoAdmin sounds useful but it never worked for me so I would appreciate any help.

Thank you.

**Comment by inverse** [comment]
ahh manual upgrades we dont know the target version. 

thanks for reporting this!

looks like the IP is your docker ones. you'll need to set it to your host ip, i assume you've running it in hosr mode tooo. so other devices on your lan can discover it

**Comment by inverse** [comment]
@BlueWings172 did you manage to fix it by providing the IP address of your host/port running docker?

What's the docker command you're using to run TasmoAdmin?

**Comment by BlueWings172** [comment]
@inverse
Thank you for your replies.

I managed to get it working by clicking both checkboxes under Update Check in Settings. I have previously added my host IP address but that alone was not enough. 

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/65966061/00d37632-444e-42fc-b2f0-e34517cc97d3)

I was able to finally update all my devices except my Sonoff Zigbee Bridge Pro.
The reason is that in the dropdown menu of the "Firmware version for automatic update", there was only tasmota-zbbridge version of Tastmota which did not work and resulted in SAFEBOOT whatever that means. 

I manually downloaded tasmota32-zbbridgepro.bin and manually upgraded. Hopefully that version will be available in TasmoAdmin in the future.

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/65966061/ccbcef4f-e139-44d1-9952-0e1169e6732b)

**Comment by inverse** [comment]
Glad you got it fixed - not sure why you would need those two checked - those are just additional validation.

As for your firmware - we just scrape the available ones from the official OTA - https://ota.tasmota.com/tasmota/release/

**Comment by BlueWings172** [comment]
@inverse 

The Sonoff Zigbee Bridge Pro uses ESP32 not ESP8266 and the Tasmota firmware for it is available on http://ota.tasmota.com/tasmota32/release/ not in https://ota.tasmota.com/tasmota/release/

Is it by design that TasmoAdmin only support Tasmota firmware updates for ESP8266 devices ?

**Comment by inverse** [comment]
we could add support for that ota server!
