### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by FrankSuFra** [TasmoAdmin/TasmoAdmin#945]
Installed version: V3.1.0
operating system: Ubuntu 22.04

Hi, I get the following error messages:

adjust settings:

`Fatal error: Uncaught Error: Class "DOMDocument" not found in /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php:1096 Stack trace: #0 /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(1214): Symfony\Component\DomCrawler\Crawler->parseXhtml() #1 /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(185): Symfony\Component\DomCrawler\Crawler->parseHtmlString() #2 /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(167): Symfony\Component\DomCrawler\Crawler->addHtmlContent() #3 /var/www/html/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(524): Symfony\Component\DomCrawler\Crawler->addContent() #4 /var/www/html/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(424): Symfony\Component\BrowserKit\AbstractBrowser->createCrawlerFromContent() #5 /var/www/html/tasmoadmin/src/Helper/TasmotaOtaScraper.php(56): Symfony\Component\BrowserKit\AbstractBrowser->request() #6 /var/www/html/tasmoadmin/src/Helper/TasmotaOtaScraper.php(46): TasmoAdmin\Helper\TasmotaOtaScraper->getFirmware() #7 /var/www/html/tasmoadmin/src/Helper/TasmotaHelper.php(70): TasmoAdmin\Helper\TasmotaOtaScraper->getEsp8266Firmware() #8 /var/www/html/tasmoadmin/pages/site_config.php(63): TasmoAdmin\Helper\TasmotaHelper->getReleases() #9 /var/www/html/tasmoadmin/index.php(82): include('...') #10 {main} thrown in /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php on line 1096`

selfupdate:

`object(GuzzleHttp\Exception\RequestException)#115 (10) { ["message":protected]=> string(262) "cURL error 60: SSL: no alternative certificate subject name matches target host name 'raw.githubusercontent.com' (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://raw.githubusercontent.com/TasmoAdmin/TasmoAdmin/master/CHANGELOG.md?r=1690014279" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(77) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php" ["line":protected]=> int(211) ["trace":"Exception":private]=> array(17) { [0]=> array(5) { ["file"]=> string(77) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php" ["line"]=> int(158) ["function"]=> string(15) "createRejection" ["class"]=> string(30) "GuzzleHttp\Handler\CurlFactory" ["type"]=> string(2) "::" } [1]=> array(5) { ["file"]=> string(77) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php" ["line"]=> int(110) ["function"]=> string(11) "finishError" ["class"]=> string(30) "GuzzleHttp\Handler\CurlFactory" ["type"]=> string(2) "::" } [2]=> array(5) { ["file"]=> string(77) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php" ["line"]=> int(47) ["function"]=> string(6) "finish" ["class"]=> string(30) "GuzzleHttp\Handler\CurlFactory" ["type"]=> string(2) "::" } [3]=> array(5) { ["file"]=> string(71) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php" ["line"]=> int(28) ["function"]=> string(8) "__invoke" ["class"]=> string(30) "GuzzleHttp\Handler\CurlHandler" ["type"]=> string(2) "->" } [4]=> array(5) { ["file"]=> string(71) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php" ["line"]=> int(48) ["function"]=> string(28) "GuzzleHttp\Handler\{closure}" ["class"]=> string(24) "GuzzleHttp\Handler\Proxy" ["type"]=> string(2) "::" } [5]=> array(5) { ["file"]=> string(79) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php" ["line"]=> int(35) ["function"]=> string(28) "GuzzleHttp\Handler\{closure}" ["class"]=> string(24) "GuzzleHttp\Handler\Proxy" ["type"]=> string(2) "::" } [6]=> array(5) { ["file"]=> string(68) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php" ["line"]=> int(31) ["function"]=> string(8) "__invoke" ["class"]=> string(32) "GuzzleHttp\PrepareBodyMiddleware" ["type"]=> string(2) "->" } [7]=> array(5) { ["file"]=> string(76) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php" ["line"]=> int(71) ["function"]=> string(20) "GuzzleHttp\{closure}" ["class"]=> string(21) "GuzzleHttp\Middleware" ["type"]=> string(2) "::" } [8]=> array(5) { ["file"]=> string(68) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php" ["line"]=> int(66) ["function"]=> string(8) "__invoke" ["class"]=> string(29) "GuzzleHttp\RedirectMiddleware" ["type"]=> string(2) "->" } [9]=> array(5) { ["file"]=> string(70) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/HandlerStack.php" ["line"]=> int(75) ["function"]=> string(20) "GuzzleHttp\{closure}" ["class"]=> string(21) "GuzzleHttp\Middleware" ["type"]=> string(2) "::" } [10]=> array(5) { ["file"]=> string(64) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php" ["line"]=> int(333) ["function"]=> string(8) "__invoke" ["class"]=> string(23) "GuzzleHttp\HandlerStack" ["type"]=> string(2) "->" } [11]=> array(5) { ["file"]=> string(64) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php" ["line"]=> int(169) ["function"]=> string(8) "transfer" ["class"]=> string(17) "GuzzleHttp\Client" ["type"]=> string(2) "->" } [12]=> array(5) { ["file"]=> string(64) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php" ["line"]=> int(189) ["function"]=> string(12) "requestAsync" ["class"]=> string(17) "GuzzleHttp\Client" ["type"]=> string(2) "->" } [13]=> array(5) { ["file"]=> string(69) "/var/www/html/tasmoadmin/vendor/guzzlehttp/guzzle/src/ClientTrait.php" ["line"]=> int(44) ["function"]=> string(7) "request" ["class"]=> string(17) "GuzzleHttp\Client" ["type"]=> string(2) "->" } [14]=> array(5) { ["file"]=> string(56) "/var/www/html/tasmoadmin/src/Helper/TasmoAdminHelper.php" ["line"]=> int(24) ["function"]=> string(3) "get" ["class"]=> string(17) "GuzzleHttp\Client" ["type"]=> string(2) "->" } [15]=> array(5) { ["file"]=> string(45) "/var/www/html/tasmoadmin/pages/selfupdate.php" ["line"]=> int(28) ["function"]=> string(12) "getChangelog" ["class"]=> string(34) "TasmoAdmin\Helper\TasmoAdminHelper" ["type"]=> string(2) "->" } [16]=> array(4) { ["file"]=> string(34) "/var/www/html/tasmoadmin/index.php" ["line"]=> int(82) ["args"]=> array(1) { [0]=> string(45) "/var/www/html/tasmoadmin/pages/selfupdate.php" } ["function"]=> string(7) "include" } } ["previous":"Exception":private]=> NULL ["request":"GuzzleHttp\Exception\RequestException":private]=> object(GuzzleHttp\Psr7\Request)#109 (7) { ["method":"GuzzleHttp\Psr7\Request":private]=> string(3) "GET" ["requestTarget":"GuzzleHttp\Psr7\Request":private]=> NULL ["uri":"GuzzleHttp\Psr7\Request":private]=> object(GuzzleHttp\Psr7\Uri)#105 (8) { ["scheme":"GuzzleHttp\Psr7\Uri":private]=> string(5) "https" ["userInfo":"GuzzleHttp\Psr7\Uri":private]=> string(0) "" ["host":"GuzzleHttp\Psr7\Uri":private]=> string(25) "raw.githubusercontent.com" ["port":"GuzzleHttp\Psr7\Uri":private]=> NULL ["path":"GuzzleHttp\Psr7\Uri":private]=> string(42) "/TasmoAdmin/TasmoAdmin/master/CHANGELOG.md" ["query":"GuzzleHttp\Psr7\Uri":private]=> string(12) "r=1690014279" ["fragment":"GuzzleHttp\Psr7\Uri":private]=> string(0) "" ["composedComponents":"GuzzleHttp\Psr7\Uri":private]=> string(88) "https://raw.githubusercontent.com/TasmoAdmin/TasmoAdmin/master/CHANGELOG.md?r=1690014279" } ["headers":"GuzzleHttp\Psr7\Request":private]=> array(2) { ["User-Agent"]=> array(1) { [0]=> string(17) "TasmoAdmin/v3.1.0" } ["Host"]=> array(1) { [0]=> string(25) "raw.githubusercontent.com" } } ["headerNames":"GuzzleHttp\Psr7\Request":private]=> array(2) { ["user-agent"]=> string(10) "User-Agent" ["host"]=> string(4) "Host" } ["protocol":"GuzzleHttp\Psr7\Request":private]=> string(3) "1.1" ["stream":"GuzzleHttp\Psr7\Request":private]=> object(GuzzleHttp\Psr7\Stream)#108 (7) { ["stream":"GuzzleHttp\Psr7\Stream":private]=> resource(14) of type (stream) ["size":"GuzzleHttp\Psr7\Stream":private]=> int(0) ["seekable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["readable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["writable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["uri":"GuzzleHttp\Psr7\Stream":private]=> string(10) "php://temp" ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=> array(0) { } } } ["response":"GuzzleHttp\Exception\RequestException":private]=> NULL ["handlerContext":"GuzzleHttp\Exception\RequestException":private]=> array(41) { ["errno"]=> int(60) ["error"]=> string(97) "SSL: no alternative certificate subject name matches target host name 'raw.githubusercontent.com'" ["appconnect_time"]=> float(0) ["url"]=> string(88) "https://raw.githubusercontent.com/TasmoAdmin/TasmoAdmin/master/CHANGELOG.md?r=1690014279" ["content_type"]=> NULL ["http_code"]=> int(0) ["header_size"]=> int(0) ["request_size"]=> int(0) ["filetime"]=> int(-1) ["ssl_verify_result"]=> int(1) ["redirect_count"]=> int(0) ["total_time"]=> float(0.074479) ["namelookup_time"]=> float(0.001337) ["connect_time"]=> float(0.014404) ["pretransfer_time"]=> float(0) ["size_upload"]=> float(0) ["size_download"]=> float(0) ["speed_download"]=> float(0) ["speed_upload"]=> float(0) ["download_content_length"]=> float(-1) ["upload_content_length"]=> float(-1) ["starttransfer_time"]=> float(0) ["redirect_time"]=> float(0) ["redirect_url"]=> string(0) "" ["primary_ip"]=> string(15) "185.199.110.133" ["certinfo"]=> array(0) { } ["primary_port"]=> int(443) ["local_ip"]=> string(12) "10.10.30.115" ["local_port"]=> int(57436) ["http_version"]=> int(0) ["protocol"]=> int(2) ["ssl_verifyresult"]=> int(0) ["scheme"]=> string(5) "HTTPS" ["appconnect_time_us"]=> int(0) ["connect_time_us"]=> int(14404) ["namelookup_time_us"]=> int(1337) ["pretransfer_time_us"]=> int(0) ["redirect_time_us"]=> int(0) ["starttransfer_time_us"]=> int(0) ["total_time_us"]=> int(74479) ["curl_version"]=> string(6) "7.81.0" } }`

Modul update:

`Fatal error: Uncaught Error: Class "DOMDocument" not found in /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php:1096 Stack trace: #0 /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(1214): Symfony\Component\DomCrawler\Crawler->parseXhtml() #1 /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(185): Symfony\Component\DomCrawler\Crawler->parseHtmlString() #2 /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php(167): Symfony\Component\DomCrawler\Crawler->addHtmlContent() #3 /var/www/html/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(524): Symfony\Component\DomCrawler\Crawler->addContent() #4 /var/www/html/tasmoadmin/vendor/symfony/browser-kit/AbstractBrowser.php(424): Symfony\Component\BrowserKit\AbstractBrowser->createCrawlerFromContent() #5 /var/www/html/tasmoadmin/src/Helper/TasmotaOtaScraper.php(56): Symfony\Component\BrowserKit\AbstractBrowser->request() #6 /var/www/html/tasmoadmin/src/Helper/TasmotaOtaScraper.php(46): TasmoAdmin\Helper\TasmotaOtaScraper->getFirmware() #7 /var/www/html/tasmoadmin/src/Helper/TasmotaHelper.php(70): TasmoAdmin\Helper\TasmotaOtaScraper->getEsp8266Firmware() #8 /var/www/html/tasmoadmin/pages/upload_form.php(16): TasmoAdmin\Helper\TasmotaHelper->getReleases() #9 /var/www/html/tasmoadmin/index.php(82): include('...') #10 {main} thrown in /var/www/html/tasmoadmin/vendor/symfony/dom-crawler/Crawler.php on line 1096`

I hope someone can help me

Frank

**Comment by inverse** [comment]
The `DOMDocument` error comes from the missing of the `ext-dom` extension. 

I think that's the `php-xml` package on Ubuntu but I am not sure.

As for the curl issue - sounds like something with the CA cert

**Comment by FrankSuFra** [comment]
okay, I'll install Tasmoadmin on Debian and then report back.
Which PHP version is currently stable on Debian?

**Comment by inverse** [comment]
I'm not sure - I'm primarily supporting Docker as it's easier to maintain. 

TasmoAdmin requires PHP 8.1 as a minimum.

**Comment by FrankSuFra** [comment]
hi, i have now installed tasmoadmin in a debian lxc container.
Works right away.
php version 8.1
So there seems to be something wrong with the installation on Ubuntu.
