### ISSUE TITLE
Proxied connection using HTTPS cannot update devices

### ISSUE THREAD

**Issue by Taomyn** [TasmoAdmin/TasmoAdmin#957]
## Expected Behavior
When connected to TasmoAdmin via HTTPS using a proxy and the OTA URL is still using the HTTP port 8880 connection, the updater should be able to find the firmware file.
![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/4365929/ac0d4551-a32c-4535-8800-4d154cc61d58)

## Current Behavior
When I attempt the auto update my devices I receive the message: "`Unable to access OTA URL @ http://192.168.1.70:8880/data/firmwares/tasmota.bin.gz - TypeError: Failed to fetch`" 

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/4365929/c0f77a1a-0f5b-4650-bad6-c69e4d56e5b5)

## Steps to Reproduce

1. Set up TasmoAdmin access via proxy, I use HAProxy for HTTPS access pointing to HTTP port 8880
2. Connect to TasmoAdmin using HTTPS e.g. https://tasmoadmin.mydomain.com
3. HAProxy redirects to http://192.168.1.70:8880
4. Attempt to perform an auto-update

If I use just HTTP direct to TasmoAdmin the update is flawless

## Context (Environment)
v3.1.0, Docker version running on Fedora Server v38
HAProxy running on OPNsense firewall

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/4365929/ff6dbe4d-24df-4a75-b842-b5c30b033070)

## Context (Device)
Any

**Comment by inverse** [comment]
What it is doing is a HEAD request to the firmware to check that it exists. Are you able to load that URL in your browser?

```
http://192.168.1.70:8880/data/firmwares/tasmota.bin.gz 
```

There should be a "Frontend check" setting that you can disable to prevent this - it should be by default off.

**Comment by Taomyn** [comment]
Yes, that URL works fine, and after disabling the "Frontend check" now it works when I'm connected via HTTPS to TasmoAdmin.
